"""Tests for the style genome wired into `render/docx.py` and `render/pptx.py`.

Per the task this file exists for: both renderers used to hard-code one look
(`docx.py`'s `_HEADER_FILL`/`_SUBTOTAL_FILL`, fixed sizes, a fixed negative
colour); they now read `compiler.style.genome`, derived from the world seed at
render time (`docx.py::_genome_for` / `pptx.py::_genome_for`), so a world's
look is one point in the space `style.py` proves is large, coherent, and
always legible — never a second hand-kept template.

The two things worth proving here, mirroring the task's own five checks:

1. Replay: the same seed renders the same bytes, twice, and across two
   independent worlds — style is a pure function of the seed, not of when it
   happened to run.
2. Variation: two different seeds render *visibly* different documents (a
   different header fill, extracted from the actual package, not asserted by
   trusting a flag) while each individually stays byte-stable.
3. The contrast floor survives rendering — computed directly against the
   actual fills this renderer paints, the same way `test_style.py` computes
   it against `style.py`'s own sampled roles, never trusted from a flag.
4. The pptx font floor holds under a genome sample, not just the one genome
   `retail-close` happens to sample today.
5. pptx shapes stay in bounds and non-overlapping under that same sample.
6. Negative numbers follow the genome's own `number_negatives` convention.
"""

from __future__ import annotations

import io
import re
import zipfile
from datetime import datetime, timezone

import docx as python_docx
import pptx as python_pptx
import pytest

from worldloom.compiler.style import CONTRAST_FLOOR, StyleGenome, contrast_ratio, genome, genomes
from worldloom.models import ArtifactIR, ArtifactSection, Cell, Column, Row, Table
from worldloom.render import docx as docx_renderer
from worldloom.render import pptx as pptx_renderer
from worldloom.rng import Rng

# A page background this renderer never paints over per-genome (see both
# `_genome_for` modules' own comment on `background`): every `_PAPER_CANDIDATES`
# entry in `style.py` is near-white, and neither renderer sets an explicit page
# fill, so the *actual* canvas behind any "plain page" text is always this.
_PAGE_WHITE = "FFFFFF"

#: A genome sample large enough to catch a rare failure, small enough to stay
#: fast — the same size class `test_style.py` itself settles on for the same
#: reason.
_SAMPLE_SIZE = 25


# ---------------------------------------------------------------------------
# A minimal artifact — built directly from `models`, not through a whole
# `World`, so these tests exercise exactly what the renderer does with a
# genome without paying for a full build/narrate pipeline (`test_docx.py` and
# `test_pptx.py` already cover that end-to-end path).
# ---------------------------------------------------------------------------


def _table(negative: bool) -> Table:
    """A small variance table with one ordinary row and one subtotal
    (``emphasis``) row — enough surface to exercise header shading, subtotal
    shading, and (with *negative*) the negative-figure convention on both a
    plain row and a shaded one.
    """
    sign = -1 if negative else 1
    return Table(
        key="variance",
        title="Variance",
        columns=[Column(key="value", label="Value", number_format="#,##0")],
        rows=[
            Row(key="line", label="Line item", cells={"value": Cell(value=sign * 4_200)}),
            Row(
                key="total", label="Total", emphasis=True,
                cells={"value": Cell(value=sign * 9_800)},
            ),
        ],
    )


def _ir(seed: int, *, negative: bool = True) -> ArtifactIR:
    created = datetime(2026, 4, 1, tzinfo=timezone.utc).isoformat()
    return ArtifactIR(
        id="ART-STYLE",
        intent_id="ART-STYLE",
        title="Styling Fixture Memo",
        subtitle="A synthetic section for render/docx.py and render/pptx.py",
        sections=[
            ArtifactSection(heading="Summary", body="A fixed sentence with no bare figures at all."),
            ArtifactSection(heading="Variance", table=_table(negative)),
        ],
        metadata={
            "worldloom_synthetic": "true",
            "worldloom_seed": str(seed),
            "worldloom_created": created,
            "company": "Test Co",
            "author": "A. Author",
            "author_title": "Tester",
            "note": "Synthetic corpus generated by Worldloom. Not a real company.",
            "voice": "precise",
            "persona": "controller",
        },
    )


# ---------------------------------------------------------------------------
# 1. Replay: same seed -> identical bytes, twice and across independent IRs
# ---------------------------------------------------------------------------


def test_docx_replays_byte_identical_for_the_same_seed() -> None:
    ir = _ir(8128)
    assert docx_renderer.render(ir) == docx_renderer.render(ir)
    # Two independently constructed IRs of the same seed, not the same object
    # rendered twice — the stronger claim `test_pptx.py::
    # test_two_independent_builds_are_byte_identical` makes for the compiler
    # pipeline, made here for the genome alone.
    assert docx_renderer.render(_ir(8128)) == docx_renderer.render(_ir(8128))


def test_pptx_replays_byte_identical_for_the_same_seed() -> None:
    ir = _ir(8128)
    assert pptx_renderer.render(ir) == pptx_renderer.render(ir)
    assert pptx_renderer.render(_ir(8128)) == pptx_renderer.render(_ir(8128))


# ---------------------------------------------------------------------------
# 2. Variation: different seeds -> different bytes, and a different header
#    fill extracted from the rendered package itself
# ---------------------------------------------------------------------------


def _docx_header_fills(payload: bytes) -> set[str]:
    """Every ``w:shd w:fill="..."`` colour in the document part — the header
    row's shading is one of them, since `docx.py::_table` shades every header
    cell with `g.colour_roles["header_fill"]`."""
    document = python_docx.Document(io.BytesIO(payload))
    return {
        run.font.color.rgb and str(run.font.color.rgb)
        for table in document.tables
        for row in table.rows
        for cell in row.cells
        for paragraph in cell.paragraphs
        for run in paragraph.runs
    } - {None}


def _docx_header_fill_hex(payload: bytes) -> str:
    """The header row's own shading colour, read the same way `w:shd` is
    written by `docx.py::_shade` — a direct regex over the one attribute this
    module ever sets that way, rather than trusting a re-derivation."""
    document = python_docx.Document(io.BytesIO(payload))
    xml = document.element.xml
    fills = re.findall(r'w:fill="([0-9A-Fa-f]{6})"', xml)
    assert fills, "no shaded cell found in the fixture table at all"
    return fills[0]


def test_two_seeds_render_different_docx_bytes_and_a_different_header_fill() -> None:
    a, b = docx_renderer.render(_ir(1)), docx_renderer.render(_ir(2))
    assert a != b

    genome_a = genome(Rng(1).derive("style"))
    genome_b = genome(Rng(2).derive("style"))
    assert genome_a.colour_roles["header_fill"] != genome_b.colour_roles["header_fill"]

    assert _docx_header_fill_hex(a) == genome_a.colour_roles["header_fill"]
    assert _docx_header_fill_hex(b) == genome_b.colour_roles["header_fill"]


def test_two_seeds_render_different_pptx_bytes_and_a_different_header_fill() -> None:
    a, b = pptx_renderer.render(_ir(1)), pptx_renderer.render(_ir(2))
    assert a != b

    genome_a = genome(Rng(1).derive("style"))
    genome_b = genome(Rng(2).derive("style"))
    assert genome_a.colour_roles["header_fill"] != genome_b.colour_roles["header_fill"]

    def band_fill(payload: bytes) -> str:
        deck = python_pptx.Presentation(io.BytesIO(payload))
        # The first content slide's header band — every `_new_slide` call
        # shades it with `g.colour_roles["header_fill"]`.
        slide = deck.slides[1]
        band = next(shape for shape in slide.shapes if shape.has_text_frame and shape.fill.type is not None)
        return str(band.fill.fore_color.rgb)

    assert band_fill(a) == genome_a.colour_roles["header_fill"]
    assert band_fill(b) == genome_b.colour_roles["header_fill"]


def test_same_seed_looks_identical_across_docx_and_pptx() -> None:
    """The point of deriving the genome from the world seed alone: the memo
    and the deck for *one* world agree on how it looks, even though they are
    two different renderers reading the same value independently."""
    seed = 4242
    g = genome(Rng(seed).derive("style"))

    docx_fill = _docx_header_fill_hex(docx_renderer.render(_ir(seed)))
    deck = python_pptx.Presentation(io.BytesIO(pptx_renderer.render(_ir(seed))))
    slide = deck.slides[1]
    band = next(shape for shape in slide.shapes if shape.has_text_frame and shape.fill.type is not None)
    pptx_fill = str(band.fill.fore_color.rgb)

    assert docx_fill == g.colour_roles["header_fill"]
    assert pptx_fill == g.colour_roles["header_fill"]


# ---------------------------------------------------------------------------
# 3. The contrast floor survives rendering — computed, not trusted
# ---------------------------------------------------------------------------


def test_every_docx_text_colour_clears_the_contrast_floor_against_its_fill() -> None:
    """Walks the actual rendered XML: every shaded cell's own text runs
    against that cell's own fill, plus body text against the page (always
    white — neither renderer paints the page background, see `_PAGE_WHITE`)."""
    for seed in range(_SAMPLE_SIZE):
        ir = _ir(seed, negative=(seed % 2 == 0))
        payload = docx_renderer.render(ir)
        document = python_docx.Document(io.BytesIO(payload))

        for table in document.tables:
            for row in table.rows:
                for cell in row.cells:
                    tc_pr = cell._element.tcPr
                    shd = tc_pr.find("{http://schemas.openxmlformats.org/wordprocessingml/2006/main}shd") if tc_pr is not None else None
                    fill = shd.get("{http://schemas.openxmlformats.org/wordprocessingml/2006/main}fill") if shd is not None else _PAGE_WHITE
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            if not run.text.strip() or run.font.color.rgb is None:
                                continue
                            ratio = contrast_ratio(fill, str(run.font.color.rgb))
                            assert ratio >= CONTRAST_FLOOR, (
                                f"seed {seed}: {run.text!r} on {fill!r} scores {ratio:.2f}"
                            )


def test_every_pptx_text_colour_clears_the_contrast_floor_against_its_fill() -> None:
    for seed in range(_SAMPLE_SIZE):
        ir = _ir(seed, negative=(seed % 2 == 0))
        payload = pptx_renderer.render(ir)
        deck = python_pptx.Presentation(io.BytesIO(payload))

        for slide in deck.slides:
            for shape in slide.shapes:
                fill = _PAGE_WHITE
                if hasattr(shape, "fill") and shape.fill.type is not None:
                    try:
                        fill = str(shape.fill.fore_color.rgb)
                    except (AttributeError, TypeError):
                        fill = _PAGE_WHITE
                frames = []
                if getattr(shape, "has_table", False):
                    for row in shape.table.rows:
                        for cell in row.cells:
                            cell_fill = fill
                            if cell.fill.type is not None:
                                try:
                                    cell_fill = str(cell.fill.fore_color.rgb)
                                except (AttributeError, TypeError):
                                    cell_fill = fill
                            frames.append((cell.text_frame, cell_fill))
                elif getattr(shape, "has_text_frame", False):
                    frames.append((shape.text_frame, fill))
                for frame, frame_fill in frames:
                    for paragraph in frame.paragraphs:
                        for run in paragraph.runs:
                            if not run.text.strip() or run.font.color.rgb is None:
                                continue
                            ratio = contrast_ratio(frame_fill, str(run.font.color.rgb))
                            assert ratio >= CONTRAST_FLOOR, (
                                f"seed {seed}: {run.text!r} on {frame_fill!r} scores {ratio:.2f}"
                            )


# ---------------------------------------------------------------------------
# 4 & 5. The pptx font floor and the bounds/non-overlap gate, under a genome
# sample — not just whichever one genome `retail-close` happens to sample.
# ---------------------------------------------------------------------------


def _shape_rects(slide) -> list[tuple[int, int, int, int, int]]:  # type: ignore[no-untyped-def]
    return [
        (shape.left, shape.top, shape.left + shape.width, shape.top + shape.height, shape.shape_id)
        for shape in slide.shapes
    ]


def _assert_bounds_and_non_overlap(prs) -> None:  # type: ignore[no-untyped-def]
    """Same gate `test_pptx.py::assert_shapes_in_bounds_and_non_overlapping`
    checks — kept local rather than imported, since this module only owns
    itself, `docx.py`, and `pptx.py`, not `test_pptx.py`."""
    width, height = prs.slide_width, prs.slide_height
    for index, slide in enumerate(prs.slides):
        rects = _shape_rects(slide)
        for left, top, right, bottom, shape_id in rects:
            assert left >= 0 and top >= 0, f"slide {index} shape {shape_id} starts out of bounds"
            assert right <= width and bottom <= height, f"slide {index} shape {shape_id} exceeds the canvas"
        for i in range(len(rects)):
            for j in range(i + 1, len(rects)):
                l1, t1, r1, b1, id1 = rects[i]
                l2, t2, r2, b2, id2 = rects[j]
                overlaps = l1 < r2 and l2 < r1 and t1 < b2 and t2 < b1
                assert not overlaps, f"slide {index}: shapes {id1} and {id2} overlap"


def _assert_font_floor(prs) -> None:  # type: ignore[no-untyped-def]
    for slide in prs.slides:
        for shape in slide.shapes:
            frames = []
            if getattr(shape, "has_table", False):
                frames = [cell.text_frame for row in shape.table.rows for cell in row.cells]
            elif getattr(shape, "has_text_frame", False):
                frames = [shape.text_frame]
            for frame in frames:
                for paragraph in frame.paragraphs:
                    for run in paragraph.runs:
                        assert run.font.size is not None
                        assert run.font.size.pt >= pptx_renderer.MIN_FONT_PT, (
                            f"{run.text!r} is {run.font.size.pt}pt, below the {pptx_renderer.MIN_FONT_PT}pt floor"
                        )


def _exercise(g: StyleGenome):  # type: ignore[no-untyped-def]
    """One deck touching every genome-consuming draw path this renderer has:
    cover, divider, every `_PROSE_STYLE` treatment, a metric-card strip, and a
    table with both a plain and a subtotal row — the same components
    `test_pptx.py`'s own direct-component tests exercise, run here once per
    sampled genome instead of once for the shipped `_HOUSE_GENOME`.
    """
    presentation = python_pptx.Presentation()
    presentation.slide_width = pptx_renderer.SLIDE_W
    presentation.slide_height = pptx_renderer.SLIDE_H

    plan = pptx_renderer.PresentationPlan(
        title="A Test Deck", subtitle="A subtitle",
        metadata={"company": "Test Co", "author": "A. Person", "author_title": "Tester"},
        slides=(),
    )
    pptx_renderer._draw_cover(presentation, plan, g)
    pptx_renderer._draw_divider(presentation, "Appendix", g)

    for component_id in ("core.position", "core.executive_summary", "core.schedule", "mgmt.decision_panel"):
        slide_plan = pptx_renderer.SlidePlan(
            kind="content", component_id=component_id, heading="Test section",
            body="Body copy for a synthetic section used only to exercise this component's geometry.",
        )
        pptx_renderer._draw_prose_content(presentation, slide_plan, {}, footer_text="Test · Deck", g=g)

    metric_table = Table(
        key="headline", title="Headline measures",
        columns=[Column(key="value", label="Value", number_format="#,##0")],
        rows=[
            Row(key="revenue", label="Revenue", cells={"value": Cell(value=617_200)}),
            Row(key="variance", label="Variance", cells={"value": Cell(value=-4_800)}),
        ],
    )
    slide = presentation.slides.add_slide(presentation.slide_layouts[6])
    pptx_renderer.draw_metric_cards(slide, metric_table, g)

    variance_table = _table(negative=True)
    pptx_renderer._draw_table_content(
        presentation,
        pptx_renderer.SlidePlan(kind="content", component_id="finance.variance_table", heading="Variance", table=variance_table),
        footer_text="Test · Deck", g=g,
    )
    return presentation


def test_pptx_font_floor_holds_across_a_genome_sample() -> None:
    for g in genomes(_SAMPLE_SIZE, seed=8128):
        _assert_font_floor(_exercise(g))


def test_pptx_shapes_stay_in_bounds_and_non_overlapping_across_a_genome_sample() -> None:
    for g in genomes(_SAMPLE_SIZE, seed=8128):
        _assert_bounds_and_non_overlap(_exercise(g))


# ---------------------------------------------------------------------------
# 6. Negative numbers follow the genome's `number_negatives` convention
# ---------------------------------------------------------------------------


def _docx_body_text(payload: bytes) -> str:
    document = python_docx.Document(io.BytesIO(payload))
    parts = [p.text for p in document.paragraphs]
    for table in document.tables:
        for row in table.rows:
            parts.extend(cell.text for cell in row.cells)
    return "\n".join(parts)


def _pptx_deck_text(payload: bytes) -> str:
    deck = python_pptx.Presentation(io.BytesIO(payload))
    parts: list[str] = []
    for slide in deck.slides:
        for shape in slide.shapes:
            if getattr(shape, "has_table", False):
                parts.extend(cell.text for row in shape.table.rows for cell in row.cells)
            elif getattr(shape, "has_text_frame", False) and shape.text_frame.text:
                parts.append(shape.text_frame.text)
    return "\n".join(parts)


@pytest.mark.parametrize("seed", list(range(20)))
def test_negatives_read_the_same_in_every_format(seed: int) -> None:
    """The genome must NOT change how a number is spelled.

    This test used to assert the opposite — that DOCX and PPTX each followed
    the genome's `number_negatives`. That was wrong, and `test_docx.py` caught
    it: a table read `-10,200` in Word and `(10,200)` in the Markdown rendering
    of the same IR. `render/values.py` exists so that cannot happen ("one
    function, so there is one answer"), and a per-renderer override
    reintroduces exactly the divergence it was written to eliminate — silently,
    because each format stays internally consistent.

    Varying the convention is still legitimate diversity. It just has to be a
    corpus-wide decision expressed once, through the IR's own `number_format`,
    so every renderer reaches the same answer through `format_value`.
    """
    ir = _ir(seed, negative=True)
    docx_body = _docx_body_text(docx_renderer.render(ir))
    pptx_body = _pptx_deck_text(pptx_renderer.render(ir))

    for figure in ("(4,200)", "(9,800)"):
        assert figure in docx_body, f"seed {seed}: {figure} missing from Word"
        assert figure in pptx_body, f"seed {seed}: {figure} missing from the deck"
    for wrong in ("-4,200", "-9,800"):
        assert wrong not in docx_body, f"seed {seed}: Word diverged to {wrong}"
        assert wrong not in pptx_body, f"seed {seed}: the deck diverged to {wrong}"


def test_number_negatives_convention_varies_across_the_sample() -> None:
    """A convention nobody in the sample ever picks the other way is not
    actually being read from the genome — this is the same
    "not-a-constant-in-disguise" check `test_docx.py`/`test_pptx.py` run for
    other invariants."""
    # Note this checks the *genome* samples both conventions, not that any
    # renderer honours one — no renderer does, deliberately, per the test above.
    # It stays because the field is real and will be consumed once the
    # convention is expressed through the IR's `number_format`, where every
    # format reads it and they cannot disagree.
    conventions = {genome(Rng(seed).derive("style")).number_negatives for seed in range(20)}
    assert conventions == {"parenthesised", "minus"}
