"""Portable business-system bundles.

Jira, Confluence, and ServiceNow as **files**, not API calls. Publishers to live
instances come at build-order step 13, and starting there would have been a
mistake: a bundle can be diffed, reproduced byte for byte, tested without
credentials, and loaded into whatever system the reader actually has.

These are record sets rather than documents, so they render from the world's facts
and events directly rather than through a document IR. What they add over a
document is workflow — status history, ownership, comments, cross-system links —
which is exactly what makes a corpus testable for agents rather than only for
retrieval.

Every bundle is JSONL plus a JSON header, so a consumer needs no library at all.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

from ..models import Authority
from . import Rendered

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World

_SYNTHETIC = "Synthetic corpus generated by Worldloom. Not a real company."


def _jsonl(rows: list[dict[str, Any]]) -> bytes:
    return ("\n".join(json.dumps(row, sort_keys=True) for row in rows) + "\n").encode("utf-8")


def _json(payload: dict[str, Any]) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _incident_facts(world: World) -> list:
    """The operational facts, in time order."""
    return sorted(
        [f for f in world.facts if f.kind.startswith("ops.")],
        key=lambda f: f.valid_from,
    )


def render_servicenow(world: World) -> list[Rendered]:
    """ServiceNow tables: incident, problem, and the CMDB it points at.

    Work notes carry the full triage sequence including the hypothesis that was
    ruled out — the record of *what was believed when*, which is the thing a
    single "root cause" field cannot express.
    """
    intents = [i for i in world.artifact_intents if i.artifact_type == "servicenow_incident"]
    if not intents:
        return []

    intent = intents[0]
    facts = _incident_facts(world)
    if not facts:
        return []

    reference = next(
        (f.text_value.split()[0] for f in facts if f.kind == "ops.incident_opened" and f.text_value),
        "INC0000001",
    )
    opened = next((f for f in facts if f.kind == "ops.incident_opened"), None)
    resolved = next((f for f in facts if f.kind == "ops.valuation_status"), None)
    confirmed = next((f for f in facts if f.kind == "ops.cause" and not f.is_superseded), None)
    classification = next((f for f in facts if f.kind == "ops.root_cause_classification"), None)
    service = confirmed.subject if confirmed else (opened.subject if opened else None)
    service_name = world.services.get(service).name if service and world.services.get(service) else ""

    work_notes = [
        {
            "at": fact.valid_from.isoformat(),
            "fact_id": fact.id,
            "authority": fact.authority.value,
            "note": fact.text_value
            or (f"{fact.kind} = {fact.value.amount:,g} {fact.value.unit}" if fact.value else fact.kind),
            "superseded": fact.is_superseded,
        }
        for fact in facts
    ]

    incident = {
        "_note": _SYNTHETIC,
        "number": reference,
        "short_description": f"{service_name} failed - month-end close at risk",
        "priority": "2 - High",
        "state": "Resolved" if resolved else "In Progress",
        "category": "Data pipeline",
        "cmdb_ci": service,
        "opened_at": opened.valid_from.isoformat() if opened else None,
        "opened_by": intent.author_id,
        "resolved_at": resolved.valid_from.isoformat() if resolved else None,
        "close_code": "Resolved by workaround",
        "problem_id": f"PRB{reference[3:]}",
        "business_service": "Financial reporting",
        "worldloom_artifact_id": intent.id,
        "worldloom_seed": world.seed,
        "work_notes": work_notes,
    }

    problem = {
        "_note": _SYNTHETIC,
        "number": f"PRB{reference[3:]}",
        "short_description": "Product hierarchy mapping has no registered owner",
        "state": "Open",
        "related_incidents": [reference],
        "cause_notes": classification.text_value if classification else None,
        "worldloom_fact_ids": [f.id for f in facts if f.kind in ("ops.root_cause_classification", "ops.mapping_table_owner")],
    }

    cmdb = [
        {
            "sys_id": svc.id,
            "name": svc.name,
            "criticality": svc.criticality_tier,
            "owned_by": svc.owner_id,
            "operational_status": "Operational",
        }
        for svc in world.services
    ]
    relations = [
        {"parent": svc.id, "child": dependency, "type": "Depends on"}
        for svc in world.services
        for dependency in svc.depends_on
    ]

    return [
        Rendered(intent.id, "servicenow/incident.json", "application/json", _json(incident)),
        Rendered(intent.id, "servicenow/problem.json", "application/json", _json(problem)),
        Rendered(intent.id, "servicenow/cmdb_ci.jsonl", "application/jsonl", _jsonl(cmdb)),
        Rendered(intent.id, "servicenow/cmdb_rel_ci.jsonl", "application/jsonl", _jsonl(relations)),
    ]


def render_jira(world: World) -> list[Rendered]:
    """Jira projects, issues, changelog, and links.

    Two issues rather than one, because the distinction between them is the point:
    one closes the detection gap, one closes the control failure. A corpus where
    remediation is a single undifferentiated ticket cannot pose the question of
    which fix actually resolves the cause.
    """
    intents = [i for i in world.artifact_intents if i.artifact_type == "jira_issues"]
    if not intents:
        return []

    intent = intents[0]
    facts = {f.id: f for f in world.facts}
    scope = next((f for f in world.facts if f.kind == "ops.remediation_addresses"), None)
    classification = next((f for f in world.facts if f.kind == "ops.root_cause_classification"), None)
    owner_fact = next((f for f in world.facts if f.kind == "ops.mapping_table_owner"), None)
    raised = next((f for f in world.facts if f.kind == "ops.remediation"), None)
    at = raised.valid_from.isoformat() if raised else None

    merch_lead = next(
        (p.id for p in world.people if p.title.startswith("Head of Merchandising")), intent.author_id
    )
    engineer = next(
        (p.id for p in world.people if p.title == "Data Platform Engineer"), intent.author_id
    )

    project = {
        "_note": _SYNTHETIC,
        "key": "PLAT",
        "name": "Platform",
        "worldloom_seed": world.seed,
    }

    issues = [
        {
            "key": "PLAT-1",
            "type": "Task",
            "summary": "Automate validation of the product hierarchy mapping",
            "status": "In Progress",
            "priority": "High",
            "reporter": intent.author_id,
            "assignee": engineer,
            "created": at,
            "labels": ["data-quality", "month-end", "detection"],
            "addresses": "detection_gap",
            "worldloom_fact_ids": [f for f in (raised.id if raised else None, scope.id if scope else None) if f],
            "acceptance_criteria": [
                "Validation runs before the valuation job and reports unmapped record count",
                "A non-zero count blocks the job and notifies the on-call engineer",
            ],
        },
        {
            "key": "PLAT-2",
            "type": "Task",
            "summary": "Assign ownership of the hierarchy mapping and require a reviewer",
            "status": "Open",
            "priority": "Highest",
            "reporter": intent.author_id,
            "assignee": merch_lead,
            "created": at,
            "labels": ["control", "master-data", "governance"],
            "addresses": "control_failure",
            "worldloom_fact_ids": [
                f for f in (
                    classification.id if classification else None,
                    owner_fact.id if owner_fact else None,
                    scope.id if scope else None,
                ) if f
            ],
            "acceptance_criteria": [
                "A named owner is registered for the mapping in the service catalogue",
                "Changes require an approving reviewer from the owning team",
                "The manual override is persisted to the master or reverted with a documented decision",
            ],
        },
    ]

    changelog = [
        {"issue": "PLAT-1", "at": at, "field": "status", "from": None, "to": "Open", "by": intent.author_id},
        {"issue": "PLAT-1", "at": at, "field": "status", "from": "Open", "to": "In Progress", "by": engineer},
        {"issue": "PLAT-2", "at": at, "field": "status", "from": None, "to": "Open", "by": intent.author_id},
    ]

    incident_reference = next(
        (f.text_value.split()[0] for f in world.facts
         if f.kind == "ops.incident_opened" and f.text_value),
        None,
    )
    links = [
        {"from": issue["key"], "to": incident_reference, "type": "caused by", "system": "servicenow"}
        for issue in issues
        if incident_reference
    ]

    return [
        Rendered(intent.id, "jira/projects.json", "application/json", _json(project)),
        Rendered(intent.id, "jira/issues.jsonl", "application/jsonl", _jsonl(issues)),
        Rendered(intent.id, "jira/changelog.jsonl", "application/jsonl", _jsonl(changelog)),
        Rendered(intent.id, "jira/links.jsonl", "application/jsonl", _jsonl(links)),
    ]


def render_confluence(world: World) -> list[Rendered]:
    """A Confluence space: page tree, pages, and comments.

    Pages carry the Markdown rendering of their IR, so a page awaiting prose says
    so rather than shipping invented narrative. Page *hierarchy* is the thing this
    format adds — a reader arriving at a stale status page should be able to see
    what it hangs off.
    """
    from . import markdown

    page_types = {"confluence_page", "knowledge_article", "close_calendar", "working_note"}
    intents = [i for i in world.artifact_intents if i.artifact_type in page_types]
    if not intents:
        return []

    space = {
        "_note": _SYNTHETIC,
        "key": "FIN",
        "name": f"{world.company.name} — Finance and Operations",
        "worldloom_seed": world.seed,
    }

    root_intent = next((i for i in intents if i.artifact_type == "close_calendar"), None)
    pages: list[dict[str, Any]] = []
    comments: list[dict[str, Any]] = []
    facts = {f.id: f for f in world.facts}

    for intent in intents:
        ir = next((r for r in world.artifact_irs if r.intent_id == intent.id), None)
        if ir is None:
            continue
        manifest = world.artifacts.get(intent.id)
        stale = any(
            facts[f].is_superseded for f in intent.required_fact_ids if f in facts
        )
        pages.append(
            {
                "id": intent.id,
                "space": "FIN",
                "title": ir.title,
                "parent": None if intent is root_intent or root_intent is None else root_intent.id,
                "author": intent.author_id,
                "created": manifest.created_at.isoformat() if manifest else None,
                "version": 1,
                "body": markdown.render(ir).decode("utf-8"),
                "labels": [intent.domain, intent.artifact_type],
                "worldloom_fact_ids": list(intent.required_fact_ids),
                # A page whose facts have since been superseded is stale. Labelled
                # rather than corrected, so it can be a test case.
                "stale": stale,
            }
        )
        if stale:
            comments.append(
                {
                    "page": intent.id,
                    "author": intent.author_id,
                    "body": "Superseded by later findings. Left as written.",
                    "worldloom_label": "stale_by_construction",
                }
            )

    return [
        Rendered(intents[0].id, "confluence/spaces.json", "application/json", _json(space)),
        Rendered(intents[0].id, "confluence/pages.jsonl", "application/jsonl", _jsonl(pages)),
        Rendered(intents[0].id, "confluence/comments.jsonl", "application/jsonl", _jsonl(comments)),
    ]
