"""The DOCX renderer.

Word is where enterprise narrative actually lives. A retrieval corpus made of
Markdown is a corpus of a shape no enterprise has — the memo a controller writes
is a ``.docx`` with a byline, headings, and a table pasted out of the workbook,
and a system that has only ever been tested on Markdown has not been tested on
the thing it will meet.

Same rule as every other format: this reads the IR and nothing else. The prose it
writes is the prose the narrative compiler already produced and the harness
already validated; the figures it writes come from the same resolved cells the
workbook computes. Nothing here can introduce a number, because nothing here is
given the chance to compute one.

Hidden sections are rendered, marked. Markdown includes them and so must this —
a "supporting facts" appendix present in one format and absent in the other would
be two documents of one artifact disagreeing about what the artifact contains,
which is the failure this project exists to prevent. Hidden means *not part of
the readable surface*, not *not written down*.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..compiler.style import StyleGenome, genome
from ..locales import DEFAULT as DEFAULT_LOCALE
from ..locales import Locale
from ..models import ArtifactIR, ArtifactSection, CanonicalFact, Chart, ChartKind, Table
from ..narrative import references
from ..presentation import DEFAULT as DEFAULT_PRESENTATION
from ..presentation import Presentation
from ..presentation import of as presentation_of
from ..rng import Rng
from . import Rendered, RenderError, fonts, ooxml, slug_for
from .values import corpus_locale, format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World

MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

#: Artifact types that are documents. A Jira bundle and a workbook are not, and a
#: Confluence page belongs to Confluence — rendering it as Word would assert a
#: filing that does not exist. A mutable set, registered into by domain
#: modules (`register` below); the PDF renderer reads this same object, so a
#: registered type gains both formats at once — deliberately, since PDF is the
#: print form of the same document set.
HANDLES = {
    "cfo_variance_memo",
    "executive_summary",
    "incident_rca",
    "working_note",
    "knowledge_article",
    "close_calendar",
    # The filings a company's own claims put in the plan (`facets.FILING_PREFIX`,
    # `generators.planning`). Listed here rather than through `register` because
    # `documents.py` declares them in core for the same reason: none of them is a
    # vertical's vocabulary. A bank can be listed, a fund can own an insurer, and
    # a big estate makes an impact assessment whoever runs it. Absent from this
    # set they rendered as Markdown and were silently skipped by Word and PDF —
    # a document that exists in the plan, exists in the IR, and reaches none of
    # the formats a reader was promised.
    "service_impact_assessment",
    "remediation_scope_review",
    "peak_trading_review",
    "audit_committee_pack",
    "sponsor_pack",
    "member_report",
    "ministerial_brief",
}


def register(*artifact_types: str) -> None:
    """Claim *artifact_types* as Word documents (and therefore PDFs).

    Called at domain-module import, like every registration seam, so a corpus
    renders the same set of files in every process.
    """
    HANDLES.update(artifact_types)

_AWAITING = (
    "Awaiting narrative. Structure and supporting facts are resolved; "
    "prose is generated by the constrained compiler."
)

_HIDDEN_NOTE = "Not part of the readable surface."


def _require_docx():  # type: ignore[no-untyped-def]
    try:
        import docx
    except ImportError as exc:  # pragma: no cover - depends on install extras
        raise RenderError(
            "the docx format needs python-docx. Install it with: pip install 'worldloom[docx]'"
        ) from exc
    return docx


# ---------------------------------------------------------------------------
# Document furniture
# ---------------------------------------------------------------------------

#: The palette `genome(rng, archetype="house")` reproduces exactly — see
#: `compiler/style.py`'s own docstring on the `"house"` archetype and
#: `tests/test_style.py::test_house_archetype_reproduces_the_shipped_docx_palette`,
#: which imports these two names by their literal values. Kept as the fixed
#: reference point the sampling space is built around, but no longer read by
#: the renderer itself below — every document's actual fill now comes from
#: that document's own world-seeded genome (`_genome_for`), so two worlds
#: are free to land on two different points in the space this pair anchors.
_HEADER_FILL = "2F4858"
_SUBTOTAL_FILL = "EDF2F4"

#: A4, because the worlds this renders are not American. Margins are the ones a
#: corporate template actually uses rather than Word's defaults. Page geometry
#: is not part of the genome's declared surface (`StyleGenome` has no margin or
#: page-size field), so it stays fixed — the same reason `_page_setup` below is
#: untouched by `_genome_for`.
_PAGE = {"width_mm": 210, "height_mm": 297, "margin_mm": 22}

#: Below this many visible sections a contents page is furniture for its own sake.
_TOC_THRESHOLD = 4


# ---------------------------------------------------------------------------
# The style genome
# ---------------------------------------------------------------------------

#: `type_scale` band indices — see `compiler/style.py::_TYPE_BANDS` for the
#: pt ranges each one samples from. Named here rather than left as bare
#: `g.type_scale[1]` throughout this module, so a reader does not have to
#: cross-reference `style.py` to know which band a given piece of furniture
#: draws its size from.
_TS_TITLE, _TS_HEADING, _TS_SUBHEADING, _TS_BODY, _TS_CAPTION = range(5)

#: `spacing_scale` band indices — see `compiler/style.py::_SPACING_BANDS`.
_SP_HEADING, _SP_SUBHEADING, _SP_PARAGRAPH, _SP_CELL = range(4)

#: `table_density` scales the tightest spacing band (table cell padding)
#: further still — a genome that samples "tight" wants noticeably less air
#: in a table than one that samples "airy" even at the *same* sampled
#: `spacing_scale[_SP_CELL]`, since density and the numeric spacing scale are
#: two different knobs `style.py` exposes independently.
_DENSITY_FACTOR: dict[str, float] = {"airy": 1.4, "normal": 1.0, "tight": 0.65}


def _genome_for(ir: ArtifactIR) -> StyleGenome:
    """This artifact's world-derived style genome.

    Per the task's own instruction: derived from the world seed *at render
    time* rather than stored on the `World` or the IR, so the thin waist gains
    no new field and a corpus keeps looking the same every time it replays
    from its seed alone.

        from ..compiler.style import genome
        from ..rng import Rng
        g = genome(Rng(world.seed).derive("style"))

    `render(ir, facts)` — called directly by several tests without a `World`
    in hand — has no `world` object to read `.seed` off of, so this reads the
    same value a different way: `ir.metadata["worldloom_seed"]` is
    `str(world.seed)`, threaded onto every IR already by
    `documents.py`/`narrative/handshake.py`. Same seed, same derivation, same
    genome — this is not a second source of truth, just the one handle this
    function's signature actually has on it.
    """
    raw = ir.metadata.get("style_seed") or ir.metadata.get("worldloom_seed")
    seed = int(raw) if raw and raw != "None" else 0
    return genome(Rng(seed).derive("style"))


def _rgb(hex_colour: str):  # type: ignore[no-untyped-def]
    from docx.shared import RGBColor

    return RGBColor.from_string(hex_colour)


def _alignment(name: str):  # type: ignore[no-untyped-def]
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    return WD_ALIGN_PARAGRAPH.LEFT if name == "left" else WD_ALIGN_PARAGRAPH.CENTER


def _heading_pt(g: StyleGenome, band: int) -> float:
    """One `type_scale` band, in points — a thin wrapper purely so call sites
    read `_heading_pt(g, _TS_BODY)` rather than an unlabelled tuple index."""
    return g.type_scale[band]


def _space_pt(g: StyleGenome, band: int) -> float:
    """One `spacing_scale` band, converted from an abstract multiple into
    points by anchoring it to this genome's own body type size — the same
    unit every other font size in the document is expressed in. A fixed pt
    anchor (say, always multiplying by 11) would let a genome with a large
    type scale end up with cramped spacing relative to its own text; anchoring
    to `type_scale[_TS_BODY]` keeps the two scales proportionate to each other
    the way a real style guide would.
    """
    return g.spacing_scale[band] * g.type_scale[_TS_BODY]


def _cell_padding_pt(g: StyleGenome) -> float:
    """Table cell vertical padding: the tightest spacing band, scaled again by
    `table_density` — see `_DENSITY_FACTOR`'s own docstring for why density is
    a second multiplier rather than folded into the sampled scale itself."""
    return _space_pt(g, _SP_CELL) * _DENSITY_FACTOR[g.table_density]


def _style_heading(paragraph, *, size_pt: float, colour_hex: str, alignment: str, space_before_pt: float | None = None) -> None:  # type: ignore[no-untyped-def]
    """Apply genome-derived size/colour/alignment to a heading `python-docx`
    already created via `add_heading` (which otherwise leaves the Word
    template's own built-in Heading/Title style sizes and colours in force —
    exactly the kind of implicit constant this module exists to replace)."""
    from docx.shared import Pt

    paragraph.alignment = _alignment(alignment)
    if space_before_pt is not None:
        paragraph.paragraph_format.space_before = Pt(space_before_pt)
    for run in paragraph.runs:
        run.font.size = Pt(size_pt)
        run.font.color.rgb = _rgb(colour_hex)


def _negative_text(value: float, text: str, convention: str) -> str:
    """Return *text* unchanged. The genome's `number_negatives` is deliberately
    not applied here.

    It was, briefly, and `tests/test_docx.py` caught it: a table rendered
    `-10,200` in Word while the same table rendered `(10,200)` in Markdown, and
    `render/values.py` exists precisely so that cannot happen — "one function,
    so there is one answer". A per-renderer override of how a number is spelled
    reintroduces the divergence that module was written to eliminate, and it
    does so invisibly, because each format is internally consistent.

    Varying the convention is still legitimate diversity; it just has to be a
    corpus-wide decision applied in one place. That place now exists and it is
    not here: `locales.Locale.negative` is decided once for the corpus, recorded
    on the recipe, resolved once per render pass by `values.corpus_locale`, and
    spelled by `format_value` — so a locale whose negatives are signed prints
    `-1.234` in Word *and* in Markdown *and* in the BM25 index, which is the
    property this function refuses to break. A genome that varied the convention
    per document would still be a second answer to a question the corpus has
    already answered, so `number_negatives` stays unapplied.

    Kept as a function rather than deleted at the call sites so the reason
    survives next to the temptation.
    """
    del convention
    return text
def _apply_table_borders(table, policy: str, weight_pt: float) -> None:  # type: ignore[no-untyped-def]
    """Draw the table's own gridlines per the genome's `gridline_policy`,
    instead of relying on the "Table Grid" style's fixed hairline everywhere.

    A neutral grey rather than a genome colour role — `style.py` declares no
    "gridline colour" role of its own (only fills and text), and a rule this
    faint reads as structure, not as a fourth ink the contrast floor would
    need to account for.
    """
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    edges = {
        "all": ("top", "bottom", "left", "right", "insideH", "insideV"),
        "horizontal": ("top", "bottom", "insideH"),
        "none": (),
    }[policy]
    # `sz` is in eighths of a point; floored at 2 (a quarter point) so a
    # genome's lightest sampled `rule_weight` (0.25) still draws a visible
    # hairline rather than rounding away to nothing.
    sz = str(max(2, round(weight_pt * 8)))

    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "bottom", "left", "right", "insideH", "insideV"):
        element = OxmlElement(f"w:{edge}")
        if edge in edges:
            element.set(qn("w:val"), "single")
            element.set(qn("w:sz"), sz)
            element.set(qn("w:color"), "808080")
        else:
            element.set(qn("w:val"), "nil")
        borders.append(element)
    table._tbl.tblPr.append(borders)


def _apply_cell_padding(table, pad_pt: float) -> None:  # type: ignore[no-untyped-def]
    """Table-wide cell margins (`w:tblCellMar`) — `table_density`'s render-time
    effect. Left/right stay Word's own comfortable default; only top/bottom
    (the axis a genome's "airy" vs "tight" table actually changes) move."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Pt

    twips = str(round(Pt(pad_pt).twips))
    cell_mar = OxmlElement("w:tblCellMar")
    for edge, width in (("top", twips), ("bottom", twips), ("left", "115"), ("right", "115")):
        element = OxmlElement(f"w:{edge}")
        element.set(qn("w:w"), width)
        element.set(qn("w:type"), "dxa")
        cell_mar.append(element)
    table._tbl.tblPr.append(cell_mar)


def _shade(cell, colour: str) -> None:  # type: ignore[no-untyped-def]
    """Fill one table cell. There is no python-docx API for this; it is w:shd."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    element = OxmlElement("w:shd")
    element.set(qn("w:fill"), colour)
    cell._element.get_or_add_tcPr().append(element)


def _field(paragraph, instruction: str) -> None:  # type: ignore[no-untyped-def]
    """Append a Word field code — the begin / instrText / end triple.

    Fields are how Word expresses anything it computes when the document opens:
    a page number, a contents list. python-docx has no API for them, so the XML
    goes in directly. This is the same principle the workbook follows — a page
    number that was *written* is a number that goes stale the moment a section is
    added, and a contents list of literal text is a lie waiting to happen.
    """
    from docx.oxml import parse_xml
    from docx.oxml.ns import nsdecls

    element = paragraph._element
    for fragment in (
        f'<w:r {nsdecls("w")}><w:fldChar w:fldCharType="begin"/></w:r>',
        f'<w:r {nsdecls("w")}><w:instrText xml:space="preserve">{instruction}</w:instrText></w:r>',
        f'<w:r {nsdecls("w")}><w:fldChar w:fldCharType="end"/></w:r>',
    ):
        element.append(parse_xml(fragment))


def _apply_typeface(document, g: StyleGenome) -> None:  # type: ignore[no-untyped-def]
    """Set the document's default faces from the genome's typeface family.

    A style-default seam rather than per-run `font.name` assignment: this
    renderer styles every run explicitly for size and colour but never for
    face, so every run inherits its style's font — setting `Normal` (body) and
    the heading styles (display) once covers the whole document, and a family
    of ``None`` (house) sets nothing, which is exactly the theme-default face
    a house document always had.
    """
    faces = fonts.named(g.typeface)
    if faces.body:
        document.styles["Normal"].font.name = faces.body
    if faces.display:
        for style_name in ("Title", "Heading 1", "Heading 2"):
            document.styles[style_name].font.name = faces.display


def _page_setup(document) -> None:  # type: ignore[no-untyped-def]
    from docx.shared import Mm

    for section in document.sections:
        section.page_width = Mm(_PAGE["width_mm"])
        section.page_height = Mm(_PAGE["height_mm"])
        for edge in ("top_margin", "bottom_margin", "left_margin", "right_margin"):
            setattr(section, edge, Mm(_PAGE["margin_mm"]))


#: Footnote-grey used for running heads, notices, and table/figure notes.
#: `StyleGenome.colour_roles` declares no "muted" role — only fills and the
#: text that sits on them — and none of these sit on a genome fill (they
#: print on the bare page), so there is no contrast pair for `style.py`'s
#: floor to police here the way there is for a header or subtotal cell.
_MUTED = "6B747B"


def _running_heads(document, ir: ArtifactIR, g: StyleGenome) -> None:  # type: ignore[no-untyped-def]
    """A header naming the document and a footer that counts its own pages.

    Both are fields rather than text where Word will compute them. A page count
    written as a literal is wrong the moment a section is added, and this corpus
    is regenerated constantly.

    The header names the company as well as the document because a reader holding
    one printed page of a synthetic corpus should be able to tell which world it
    came from without finding the cover.
    """
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt

    size = Pt(_heading_pt(g, _TS_CAPTION))
    section = document.sections[0]

    head = section.header.paragraphs[0]
    head.text = " · ".join(
        part for part in (ir.metadata.get("company"), ir.title) if part
    )
    head.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    for run in head.runs:
        run.font.size = size
        run.font.color.rgb = _rgb(_MUTED)

    foot = section.footer.paragraphs[0]
    foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
    foot.text = ""
    label = foot.add_run(
        ir.metadata.get("note", "Synthetic corpus generated by Worldloom.") + "    Page "
    )
    label.font.size = size
    label.font.color.rgb = _rgb(_MUTED)
    _field(foot, " PAGE ")
    tail = foot.add_run(" of ")
    tail.font.size = size
    tail.font.color.rgb = _rgb(_MUTED)
    _field(foot, " NUMPAGES ")
    for run in foot.runs:
        run.font.size = size
        run.font.color.rgb = _rgb(_MUTED)


def _cover(document, ir: ArtifactIR, g: StyleGenome) -> None:  # type: ignore[no-untyped-def]
    from docx.shared import Pt

    title = document.add_heading(ir.title, level=0)
    _style_heading(
        title, size_pt=_heading_pt(g, _TS_TITLE), colour_hex=g.colour_roles["body_text"],
        alignment=g.title_alignment,
    )
    if ir.subtitle:
        subtitle = document.add_paragraph(ir.subtitle)
        subtitle.runs[0].italic = True
        subtitle.paragraph_format.space_before = Pt(_space_pt(g, _SP_SUBHEADING))
        subtitle.runs[0].font.size = Pt(_heading_pt(g, _TS_SUBHEADING))
        subtitle.runs[0].font.color.rgb = _rgb(_MUTED)

    author = ir.metadata.get("author")
    if author:
        byline = author
        if ir.metadata.get("author_title"):
            byline += f", {ir.metadata['author_title']}"
        byline_run = document.add_paragraph(byline).runs[0]
        byline_run.bold = True
        byline_run.font.size = Pt(_heading_pt(g, _TS_BODY))
        byline_run.font.color.rgb = _rgb(g.colour_roles["body_text"])

    notice = document.add_paragraph(
        ir.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")
    )
    notice.runs[0].italic = True
    notice.runs[0].font.size = Pt(_heading_pt(g, _TS_CAPTION))
    notice.runs[0].font.color.rgb = _rgb(_MUTED)



def _genre_front_matter(document, ir: ArtifactIR, g: StyleGenome) -> None:  # type: ignore[no-untyped-def]
    """Render native control rows from existing ecology metadata only."""
    if ir.metadata.get("realism_profile") != "ecology/v1":
        return
    genre = ir.metadata.get("artifact_genre")
    if genre not in {"decision_memo", "controlled_document", "incident_rca"}:
        return

    from datetime import datetime

    from docx.shared import Pt

    created = ir.metadata.get("worldloom_created")
    date = datetime.fromisoformat(created).strftime("%d %b %Y") if created else ""
    if genre == "decision_memo":
        rows = (("From", ir.metadata.get("author", "")), ("Date", date), ("Subject", ir.title))
    else:
        rows = (
            ("Status", ir.metadata.get("lifecycle", "").replace("_", " ").title()),
            ("Revision", ir.metadata.get("revision", "")),
            ("Date", date),
        )
    rows = tuple((label, value) for label, value in rows if value)
    if not rows:
        return

    table = document.add_table(rows=0, cols=2)
    _apply_table_borders(table, "horizontal", g.rule_weight)
    _apply_cell_padding(table, _cell_padding_pt(g))
    for label, value in rows:
        cells = table.add_row().cells
        cells[0].text = label
        cells[1].text = value
        for run in cells[0].paragraphs[0].runs:
            run.bold = True
        for cell in cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(_heading_pt(g, _TS_BODY))
                    run.font.color.rgb = _rgb(g.colour_roles["body_text"])


def _contents(document, ir: ArtifactIR, g: StyleGenome) -> None:  # type: ignore[no-untyped-def]
    """A contents field, on documents long enough to need one.

    A field rather than a written list: Word builds it from the headings actually
    present when the document opens, so it cannot drift from the document the way
    a typed list would.
    """
    visible = [s for s in ir.sections if not s.hidden]
    if len(visible) < _TOC_THRESHOLD:
        return

    heading = document.add_heading("Contents", level=1)
    _style_heading(
        heading, size_pt=_heading_pt(g, _TS_HEADING), colour_hex=g.colour_roles["body_text"],
        alignment=g.title_alignment, space_before_pt=_space_pt(g, _SP_HEADING),
    )
    _field(document.add_paragraph(), r' TOC \o "1-2" \h \z \u ')
    document.add_page_break()

def _table(document, table: Table, g: StyleGenome, locale: Locale = DEFAULT_LOCALE) -> None:  # type: ignore[no-untyped-def]
    """One IR table as a Word table.

    A label column then one column per measure, matching the Markdown rendering
    cell for cell — the values come from ``format_value``, which both formats
    share so neither can round differently from the other.

    Numbers are right-aligned and subtotal rows shaded, because a financial table
    that is not aligned on the decimal is one a finance reader cannot scan, and
    scanning is the only thing they will do with it.
    """
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt

    body_pt = Pt(_heading_pt(g, _TS_BODY))

    # No "Table Grid" style — `_apply_table_borders` below draws the actual
    # rules per `gridline_policy`/`rule_weight`, so starting from the style's
    # own fixed hairline would leave a border the genome never chose showing
    # through wherever our own borders say "none".
    grid = document.add_table(rows=1, cols=len(table.columns) + 1)
    _apply_table_borders(grid, g.gridline_policy, g.rule_weight)
    _apply_cell_padding(grid, _cell_padding_pt(g))

    header = grid.rows[0].cells
    header[0].text = table.title
    for index, column in enumerate(table.columns, start=1):
        header[index].text = column.label
    for cell in header:
        _shade(cell, g.colour_roles["header_fill"])
        for paragraph in cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            for run in paragraph.runs:
                run.bold = True
                run.font.size = body_pt
                run.font.color.rgb = _rgb(g.colour_roles["header_text"])
    header[0].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.LEFT

    for row in table.rows:
        cells = grid.add_row().cells
        cells[0].text = row.label
        # A subtotal row's own text colour, resolved once per row: `style.py`
        # only ever proves `subtotal_text` legible against `subtotal_fill`, so
        # it is the one colour every run in a shaded row is allowed to use —
        # painting `negative_text` there instead would be exactly the
        # "hard-code a colour over a genome fill" this module must not do.
        # The sign still shows: `number_negatives` still parenthesises or
        # minus-signs the figure, colour is only ever the *second* signal.
        row_colour = g.colour_roles["subtotal_text"] if row.emphasis else g.colour_roles["body_text"]

        negatives: list[bool] = [False]  # column 0 (the label) is never numeric
        for index, column in enumerate(table.columns, start=1):
            cell = row.cells.get(column.key)
            value = cell.value if cell else None
            negative = isinstance(value, (int, float)) and value < 0
            negatives.append(negative)
            text = format_value(value, column.number_format, locale=locale) if cell else ""
            if negative:
                text = _negative_text(value, text, g.number_negatives)
            cells[index].text = text
            if isinstance(value, (int, float)):
                cells[index].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

        for cell, negative in zip(cells, negatives):
            colour = g.colour_roles["negative_text"] if negative and not row.emphasis else row_colour
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = body_pt
                    run.bold = bool(row.emphasis)
                    run.font.color.rgb = _rgb(colour)
            if row.emphasis:
                _shade(cell, g.colour_roles["subtotal_fill"])

    if table.note:
        note = document.add_paragraph(table.note)
        note.runs[0].italic = True
        note.runs[0].font.size = Pt(_heading_pt(g, _TS_CAPTION))
        note.runs[0].font.color.rgb = _rgb(_MUTED)


#: A chart figure's size on the page — the full text column width (A4 minus
#: the corporate margins `_page_setup` sets), and a height chosen for a
#: legible legend/axis band under it rather than derived from anything in
#: the IR. 1mm is exactly 36,000 EMU (914,400 EMU/inch / 25.4mm/inch) — the
#: same unit `Box`/`_in` in `pptx.py` uses, spelled in mm here because
#: `_PAGE` already is.
_EMU_PER_MM = 36_000
_CHART_WIDTH_EMU = (_PAGE["width_mm"] - 2 * _PAGE["margin_mm"]) * _EMU_PER_MM
_CHART_HEIGHT_EMU = 95 * _EMU_PER_MM

#: The two axes' `c:axId` values inside one chart's own `c:chartSpace`. Fixed
#: rather than generated, because an axId only has to be unique *within the
#: chart part that declares it* (it is how that one chart's `c:catAx`/
#: `c:valAx` cross-reference each other, per `c:crossAx`) — every chart this
#: renderer writes gets a fresh, independent chart part, so reusing the same
#: pair everywhere introduces no collision and needs no counter.
_CAT_AXIS_ID, _VAL_AXIS_ID = "111111111", "222222222"

_CHART_NS = "http://schemas.openxmlformats.org/drawingml/2006/chart"


def _chart_rows(chart: Chart, table: Table) -> list[str]:
    """Row keys this chart plots, in the order they should appear.

    Same rule `pptx.py::_chart_rows` reads off `Chart.rows`'s own docstring:
    explicit rows keep the author's order; empty means every row that is not
    a subtotal, and there the table's own row order is the only order there
    is.
    """
    if chart.rows:
        return list(chart.rows)
    return [row.key for row in table.rows if not row.emphasis]


def _chart_series(
    chart: Chart, table: Table,
) -> tuple[list[str], list[tuple[str, list[float | None], str | None]]]:
    """Resolve a declared chart into categories and ``(label, values,
    number_format)`` series, reading nothing but cells already in *table* —
    see `Chart`'s own docstring: "a chart never introduces a number."

    Identical to `pptx.py::_chart_series` — both read `by_row` and `rows`
    the same way `xlsx.py::_chart_block` does, so no two of this project's
    three chart-drawing renderers can disagree about which cells a given
    chart plots.
    """
    row_keys = _chart_rows(chart, table)
    rows_by_key = {row.key: row for row in table.rows}

    def row_label(key: str) -> str:
        row = rows_by_key.get(key)
        return row.label if row else key

    def column_label(key: str) -> str:
        column = table.column(key)
        return column.label if column else key

    def value(row_key: str, column_key: str) -> float | None:
        row = rows_by_key.get(row_key)
        cell = row.cells.get(column_key) if row else None
        if cell is None or not isinstance(cell.value, (int, float)):
            return None
        raw = float(cell.value)
        column = table.column(column_key)
        # A percentage fact is stored as 24.94; Excel's own percent format
        # multiplies by 100 to display it, so a chart axis using that format
        # needs the same 24.94 -> 0.2494 conversion `xlsx.py::render` applies
        # to cells — see that function's own comment for why the format
        # string is what decides.
        if column and column.number_format and column.number_format.endswith("%"):
            return raw / 100
        return raw

    if chart.by_row:
        first_format = table.column(chart.series[0]).number_format if chart.series else None
        categories = [column_label(key) for key in chart.series]
        series = [
            (row_label(row_key), [value(row_key, col_key) for col_key in chart.series], first_format)
            for row_key in row_keys
        ]
    else:
        categories = [row_label(key) for key in row_keys]
        series = [
            (column_label(col_key),
             [value(row_key, col_key) for row_key in row_keys],
             table.column(col_key).number_format if table.column(col_key) else None)
            for col_key in chart.series
        ]
    return categories, series


def _column_letter(index: int) -> int | str:  # type: ignore[no-untyped-def]
    """1-based column index to its spreadsheet letter — the base-26,
    no-zero scheme every spreadsheet uses. `xlsx.py` gets this from
    `openpyxl`, which is that renderer's own dependency already; this module
    has no reason to add it just to spell a cosmetic cell reference (see
    `_chart_xml`'s docstring for why the reference is cosmetic here), so it
    is spelled out directly instead.
    """
    letters = ""
    while index:
        index, remainder = divmod(index - 1, 26)
        letters = chr(ord("A") + remainder) + letters
    return letters


def _axis_title_xml(text: str) -> str:
    """A `c:title` element carrying plain text — used for both a chart's
    axis titles. Word ignores an axis with no `c:title` child entirely
    (rather than showing a blank one), which is why this returns "" for an
    unset axis rather than an empty title element.
    """
    if not text:
        return ""
    from xml.sax.saxutils import escape

    return (
        "<c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>"
        + escape(text)
        + "</a:t></a:r></a:p></c:rich></c:tx><c:overlay val=\"0\"/></c:title>"
    )


def _series_xml(index: int, label: str, values: list[float | None], number_format: str,
                 *, marker: bool, categories: list[str]) -> str:
    """One `c:ser` element: its own name, the shared category list, and its
    values — each as a cache (`c:strCache`/`c:numCache`), the values Word
    actually draws with no workbook to resolve. See `_chart_xml`'s docstring
    for why there is no workbook behind the `c:f` cell references below; they
    are spelled anyway, in the same `Sheet1!$B$2:$B$5` shape a real embedded
    workbook would use, so nothing here looks unlike what `pptx.py`'s charts
    (which do have a backing workbook) produce.
    """
    from xml.sax.saxutils import escape

    def strcache(items: list[str]) -> str:
        points = "".join(f'<c:pt idx="{i}"><c:v>{escape(str(v))}</c:v></c:pt>' for i, v in enumerate(items))
        return f'<c:ptCount val="{len(items)}"/>{points}'

    def numcache(items: list[float | None]) -> str:
        points = "".join(
            f'<c:pt idx="{i}"><c:v>{v!r}</c:v></c:pt>' for i, v in enumerate(items) if v is not None
        )
        return (
            f'<c:formatCode>{escape(number_format or "General")}</c:formatCode>'
            f'<c:ptCount val="{len(items)}"/>{points}'
        )

    col = _column_letter(index + 2)  # column A holds the categories
    cat_col = _column_letter(1)
    return (
        f'<c:ser><c:idx val="{index}"/><c:order val="{index}"/>'
        f'<c:tx><c:strRef><c:f>Sheet1!${col}$1</c:f>'
        f'<c:strCache>{strcache([label])}</c:strCache></c:strRef></c:tx>'
        + ('<c:marker><c:symbol val="none"/></c:marker>' if marker else "")
        + f'<c:cat><c:strRef><c:f>Sheet1!${cat_col}$2:${cat_col}${len(categories) + 1}</c:f>'
        f'<c:strCache>{strcache(categories)}</c:strCache></c:strRef></c:cat>'
        f'<c:val><c:numRef><c:f>Sheet1!${col}$2:${col}${len(values) + 1}</c:f>'
        f'<c:numCache>{numcache(values)}</c:numCache></c:numRef></c:val>'
        "</c:ser>"
    )


def _chart_xml(
    chart: Chart, categories: list[str], series: list[tuple[str, list[float | None], str | None]],
) -> bytes:
    """The DrawingML chart part XML for one declared chart — cached values
    only, no linked workbook.

    `python-docx` has no chart API at all (unlike `python-pptx`, whose
    `shapes.add_chart` this project's `pptx.py` uses directly), so this
    builds the `c:chartSpace` part by hand — the same DrawingML chart schema
    every OOXML host (Word, PowerPoint, Excel) shares, which is what makes a
    hand-built one exactly as valid as a library-built one.

    A real embedded workbook — what `pptx.py`'s charts carry, because
    `python-pptx`'s API always creates one — is deliberately not built here.
    `CT_ChartSpace`'s `c:externalData` is optional (ECMA-376 §21.2.2.101,
    ``minOccurs="0"``): a chart is *displayed* from its own `c:numCache`/
    `c:strCache`, and the external workbook exists only so a reader can
    choose "Edit Data in Excel" on it. Building one would mean a second OOXML
    package nested inside this one — `python-pptx` reaches for `xlsxwriter`
    to do it, which is exactly the nested-clock defect `ooxml.normalise`'s
    own docstring describes fixing for `pptx.py`. Skipping it is not a
    shortcut taken to avoid that fix: it removes an entire dependency and an
    entire determinism surface, and a reader can still see and check every
    plotted value against the table beside it either way.
    """
    is_pie = chart.kind is ChartKind.PIE
    plotted = series[:1] if is_pie else series
    is_line = chart.kind is ChartKind.LINE

    ser_xml = "".join(
        _series_xml(index, label, values, number_format or "General", marker=is_line, categories=categories)
        for index, (label, values, number_format) in enumerate(plotted)
    )

    if is_pie:
        plot = f'<c:pieChart><c:varyColors val="1"/>{ser_xml}</c:pieChart>'
        axes = ""
    else:
        tag, direction = {
            ChartKind.COLUMN: ("barChart", "col"),
            ChartKind.BAR: ("barChart", "bar"),
            ChartKind.LINE: ("lineChart", None),
        }[chart.kind]
        grouping = '<c:grouping val="clustered"/>' if tag == "barChart" else '<c:grouping val="standard"/>'
        direction_el = f'<c:barDir val="{direction}"/>' if direction else ""
        marker_el = '<c:marker val="1"/>' if is_line else ""
        plot = (
            f"<c:{tag}>{direction_el}{grouping}{marker_el}{ser_xml}"
            f'<c:axId val="{_CAT_AXIS_ID}"/><c:axId val="{_VAL_AXIS_ID}"/></c:{tag}>'
        )
        # A horizontal bar chart's category axis runs up the left edge, not
        # along the bottom — swapped here rather than left at the vertical
        # chart's positions, which would put category labels on the value
        # axis and vice versa.
        cat_pos, val_pos = ("l", "b") if direction == "bar" else ("b", "l")
        axes = (
            f'<c:catAx><c:axId val="{_CAT_AXIS_ID}"/><c:scaling><c:orientation val="minMax"/></c:scaling>'
            f'<c:delete val="0"/><c:axPos val="{cat_pos}"/>{_axis_title_xml(chart.category_axis)}'
            '<c:majorTickMark val="out"/><c:minorTickMark val="none"/><c:tickLblPos val="nextTo"/>'
            f'<c:crossAx val="{_VAL_AXIS_ID}"/><c:crosses val="autoZero"/><c:auto val="1"/>'
            '<c:lblAlgn val="ctr"/><c:lblOffset val="100"/><c:noMultiLvlLbl val="0"/></c:catAx>'
            f'<c:valAx><c:axId val="{_VAL_AXIS_ID}"/><c:scaling><c:orientation val="minMax"/></c:scaling>'
            f'<c:delete val="0"/><c:axPos val="{val_pos}"/>{_axis_title_xml(chart.value_axis)}'
            '<c:majorGridlines/><c:numFmt formatCode="General" sourceLinked="0"/>'
            '<c:majorTickMark val="out"/><c:minorTickMark val="none"/><c:tickLblPos val="nextTo"/>'
            f'<c:crossAx val="{_CAT_AXIS_ID}"/><c:crosses val="autoZero"/></c:valAx>'
        )

    # A single plotted series needs no legend to say what it is; a pie
    # always does, because its wedges have no axis to be labelled by.
    legend = '<c:legend><c:legendPos val="b"/><c:overlay val="0"/></c:legend>' if len(plotted) > 1 or is_pie else ""

    xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        f'<c:chartSpace xmlns:c="{_CHART_NS}" '
        'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        "<c:chart><c:autoTitleDeleted val=\"1\"/>"  # the caption paragraph beside it already carries the title
        f"<c:plotArea><c:layout/>{plot}{axes}</c:plotArea>"
        f"{legend}<c:plotVisOnly val=\"1\"/><c:dispBlanksAs val=\"gap\"/></c:chart>"
        "</c:chartSpace>"
    )
    return xml.encode("utf-8")


def _add_chart_part(document, xml_bytes: bytes) -> str:  # type: ignore[no-untyped-def]
    """Add one chart XML blob as a package part related to the main document
    part, and return the relationship id `document.xml` uses to reach it.

    `docx.opc.part.Part`/`OpcPackage` are the same OPC machinery
    `python-pptx` builds its own chart parts on top of (both packages
    descend from the same original library) — this is that machinery used
    directly, one layer below where `python-docx`'s own API stops. Content
    types are derived automatically from every part reachable from the
    package's relationship graph at save time (`docx.opc.pkgwriter`), so
    adding this relationship is the only bookkeeping this function needs to
    do; there is no `[Content_Types].xml` entry to maintain by hand.
    """
    from docx.opc.constants import CONTENT_TYPE as CT
    from docx.opc.constants import RELATIONSHIP_TYPE as RT
    from docx.opc.part import Part

    part = document.part
    partname = part.package.next_partname("/word/charts/chart%d.xml")
    chart_part = Part(partname, CT.DML_CHART, xml_bytes, part.package)
    return part.relate_to(chart_part, RT.CHART)


def _chart_drawing_xml(rid: str, drawing_id: int) -> str:
    """A `<w:r><w:drawing>...` run embedding the chart part *rid* points to,
    sized to `_CHART_WIDTH_EMU`/`_CHART_HEIGHT_EMU`.

    Appended to a paragraph's own element (`paragraph._p.append(...)`) rather
    than assembled as a whole `<w:p>` and appended to `document.element.body`
    — `w:body`'s last child must be its `w:sectPr` (section properties), and
    `document.add_paragraph()` already knows how to insert *before* it;
    appending straight to `body` would put the drawing after it instead,
    which is exactly the "needs repair" defect a first attempt at this
    produced and a round-trip open through `python-docx` alone did not catch
    (nothing here reads `body`'s child order back).
    """
    from docx.oxml.ns import nsdecls

    return (
        f'<w:r {nsdecls("w")}><w:drawing>'
        f'<wp:inline {nsdecls("wp")} distT="0" distB="0" distL="0" distR="0">'
        f'<wp:extent cx="{_CHART_WIDTH_EMU}" cy="{_CHART_HEIGHT_EMU}"/>'
        '<wp:effectExtent l="0" t="0" r="0" b="0"/>'
        f'<wp:docPr id="{drawing_id}" name="Chart {drawing_id}"/>'
        f'<a:graphic {nsdecls("a")}>'
        f'<a:graphicData uri="{_CHART_NS}">'
        f'<c:chart {nsdecls("c", "r")} r:id="{rid}"/>'
        "</a:graphicData></a:graphic></wp:inline></w:drawing></w:r>"
    )


def _figure(document, chart: Chart, table: Table, g: StyleGenome, chart_index) -> None:  # type: ignore[no-untyped-def]
    """A declared chart, drawn as a native OOXML chart part — see
    `_chart_xml`'s own docstring for why it carries no linked workbook.

    *chart_index* is an `itertools.count()` shared across the whole document
    (threaded down from `render`) — `wp:docPr`'s `id` has to be unique across
    every drawing the finished document contains, and nothing else here is
    tracking how many precede this one.
    """
    from docx.oxml.parser import parse_xml
    from docx.shared import Pt

    categories, series = _chart_series(chart, table)
    if not categories or not series:
        return

    caption = document.add_paragraph()
    label = caption.add_run(f"Figure — {chart.title}")
    label.bold = True
    label.font.size = Pt(_heading_pt(g, _TS_BODY))

    xml_bytes = _chart_xml(chart, categories, series)
    rid = _add_chart_part(document, xml_bytes)
    drawing = document.add_paragraph()
    drawing._p.append(parse_xml(_chart_drawing_xml(rid, next(chart_index))))

    if chart.note:
        note = document.add_paragraph(chart.note)
        note.runs[0].italic = True
        note.runs[0].font.size = Pt(_heading_pt(g, _TS_CAPTION))


def _section(document, section: ArtifactSection, facts, g: StyleGenome,
             locale: Locale = DEFAULT_LOCALE,
             presentation: Presentation = DEFAULT_PRESENTATION,
             chart_index=None) -> None:  # type: ignore[no-untyped-def]
    heading = document.add_heading(section.heading, level=1)
    _style_heading(
        heading, size_pt=_heading_pt(g, _TS_HEADING), colour_hex=g.colour_roles["body_text"],
        alignment=g.title_alignment, space_before_pt=_space_pt(g, _SP_HEADING),
    )
    if section.hidden:
        marker = document.add_paragraph(_HIDDEN_NOTE)
        marker.runs[0].italic = True

    if section.body:
        text = (references.substitute(section.body, facts, locale=locale,
                                      presentation=presentation)
                if facts else section.body)
        # Blank lines are paragraph breaks. Word has no other way to say it, and a
        # single run containing newlines renders as one unbroken block.
        from docx.shared import Pt

        for block in (part.strip() for part in text.split("\n\n")):
            if block:
                paragraph = document.add_paragraph(block)
                paragraph.paragraph_format.space_after = Pt(_space_pt(g, _SP_PARAGRAPH))
                for run in paragraph.runs:
                    run.font.size = Pt(_heading_pt(g, _TS_BODY))
                    run.font.color.rgb = _rgb(g.colour_roles["body_text"])
    elif section.quote is not None:
        # The same blockquote semantics as `markdown._quote`: a pulled-out
        # line, visibly not narrated in place. Word has no blockquote style
        # guaranteed present, so indent + italic carries the distinction.
        text = (references.substitute(section.quote.text, facts, locale=locale,
                                      presentation=presentation)
                if facts else section.quote.text)
        from docx.shared import Pt as _Pt

        quoted = document.add_paragraph(text)
        quoted.paragraph_format.left_indent = _Pt(24)
        for run in quoted.runs:
            run.italic = True
        if section.quote.attribution:
            by = document.add_paragraph(f"— {section.quote.attribution}")
            by.paragraph_format.left_indent = _Pt(24)
    elif section.table is not None:
        _table(document, section.table, g, locale)
    elif section.flow is None or not (section.flow.nodes or section.flow.edges):
        awaiting = document.add_paragraph(_AWAITING)
        awaiting.runs[0].italic = True

    # The flow is additive, exactly as in `render.markdown`: a causal chain is
    # a diagram of the argument the prose just made, so it follows the
    # paragraph instead of replacing it. This branch did not exist for a long
    # time while `compiler/components.py` declared `ops.causal_chain` and
    # `ops.process_flow` supported in "markdown docx pptx pdf" — measured on a
    # three-period incident build, DOCX printed the awaiting notice under
    # *Root cause* where markdown and PDF printed 21 nodes and 18 edges.
    if section.flow is not None and (section.flow.nodes or section.flow.edges):
        label_by_key = {node.key: node.label for node in section.flow.nodes}

        def _resolved(text: str) -> str:
            return (references.substitute(text, facts, locale=locale,
                                          presentation=presentation)
                    if facts else text)

        steps = (
            [
                f"{_resolved(label_by_key.get(edge.source, edge.source))} → "
                f"{_resolved(label_by_key.get(edge.target, edge.target))}"
                + (f" ({_resolved(edge.label)})" if edge.label else "")
                for edge in section.flow.edges
            ]
            if section.flow.edges
            else [_resolved(node.label) for node in section.flow.nodes]
        )
        from docx.shared import Pt as _Pt

        for step in steps:
            bullet = document.add_paragraph(step, style="List Bullet")
            for run in bullet.runs:
                run.font.size = _Pt(_heading_pt(g, _TS_BODY))

    # After the chain, never inside it — a `for` between the `elif` and the
    # `else` binds the `else` to the loop, and Python runs a loop-else whenever
    # the loop did not break. That mistake put an "awaiting narrative" notice
    # under finished prose in the Markdown renderer.
    if section.charts and chart_index is None:
        # A direct call with no counter supplied (as several tests make) —
        # unique only within this one section's own figures, which is still
        # correct: nothing before this call has drawn a chart into `document`.
        from itertools import count as _count

        chart_index = _count(1)
    for chart in section.charts:
        # `chart.table` names the table this chart reads — see `Chart`'s own
        # docstring, "every value it plots is a cell already in the table
        # beside it". Skipped rather than guessed at when it names some
        # other table: drawing from `section.table` anyway would be this
        # renderer inventing which table the chart meant.
        if section.table is not None and chart.table == section.table.key:
            _figure(document, chart, section.table, g, chart_index)


def render(
    ir: ArtifactIR,
    facts: dict[str, CanonicalFact] | None = None,
    *,
    locale: Locale = DEFAULT_LOCALE,
    presentation: Presentation = DEFAULT_PRESENTATION,
) -> bytes:
    """Render one IR to DOCX bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render
    time. Without it the references stay visible, which is the right failure — a
    document that quietly drops a figure reads as complete and is not.

    *locale* is the corpus's, resolved once by ``render_all`` and threaded down
    rather than looked up per table — see ``values.corpus_locale``. It defaults
    to the engine's so that rendering a single IR without a world (the idiom
    every determinism test in ``tests/test_docx.py`` uses) still works.

    *presentation* rides beside it and decides who the document is for —
    see ``presentation.py``. It defaults to ``AUDIT`` for the same reason,
    and because ``AUDIT`` is what this function did before profiles existed.
    """
    from itertools import count

    docx = _require_docx()
    document = docx.Document()
    g = _genome_for(ir)
    _apply_typeface(document, g)

    _page_setup(document)
    _running_heads(document, ir, g)
    _cover(document, ir, g)
    _genre_front_matter(document, ir, g)
    _contents(document, ir, g)

    # One counter for the whole document, not one per section — `wp:docPr`'s
    # `id` has to be unique across every chart the finished document
    # contains, and a fresh `count(1)` per section would hand out "1" again
    # the moment a second section drew a chart.
    chart_index = count(1)
    for section in ir.sections:
        if section.hidden and presentation.appendix != "append":
            continue
        _section(document, section, facts, g, locale, presentation, chart_index)

    if ir.metadata.get("voice") and presentation.provenance == "footer":
        closing = document.add_paragraph(
            f"Author voice: {ir.metadata['voice']}. Persona: {ir.metadata.get('persona', '')}."
        )
        closing.runs[0].italic = True
        from docx.shared import Pt

        closing.runs[0].font.size = Pt(_heading_pt(g, _TS_CAPTION))
        closing.runs[0].font.color.rgb = _rgb(_MUTED)

    properties = document.core_properties
    properties.title = ir.title
    properties.subject = ir.subtitle or ""
    properties.author = ir.metadata.get("author") or "Worldloom"
    properties.comments = ir.metadata.get(
        "note", "Synthetic corpus generated by Worldloom."
    )
    properties.keywords = "synthetic,worldloom,seed=" + ir.metadata.get("worldloom_seed", "")
    categories: list[str] = []
    if ir.metadata.get("voice") and presentation.provenance == "properties":
        # Word's own "category" field, which no reader of the document sees
        # and every corpus tool can read. The brief is worth keeping — it is
        # how a later reader knows why a memo sounds the way it does — and
        # the only thing wrong with it was being the last paragraph.
        categories.append(
            f"voice: {ir.metadata['voice']}; persona: {ir.metadata.get('persona', '')}"
        )
    if ir.metadata.get("realism_profile") == "ecology/v1":
        categories.extend((
            "worldloom-realism=ecology/v1",
            f"lifecycle={ir.metadata.get('lifecycle', 'draft')}",
            f"revision={ir.metadata.get('revision', '1')}",
            f"family={ir.metadata.get('artifact_family', 'document')}",
        ))
    if categories:
        properties.category = "; ".join(categories)

    from io import BytesIO

    buffer = BytesIO()
    document.save(buffer)
    # Dates come from the world, never the clock. python-docx would otherwise
    # ship its template's own 2013 timestamps, which is a smaller lie than
    # `now()` and still a wrong one.
    return ooxml.normalise(buffer.getvalue(), created=ir.metadata.get("worldloom_created"))


def render_all(world: World) -> list[Rendered]:
    """Render every document-shaped artifact in *world*."""
    facts = {fact.id: fact for fact in world.facts}
    locale = corpus_locale(world)
    profile = presentation_of(world)
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type not in HANDLES:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.docx",
                media_type=MEDIA_TYPE,
                payload=render(ir, facts, locale=locale,
                               presentation=profile.for_doctype(intent.artifact_type)),
            )
        )
    return out
