"""The DOCX renderer.

Word is where enterprise narrative actually lives. A retrieval corpus made of
Markdown is a corpus of a shape no enterprise has — the memo a controller writes
is a ``.docx`` with a byline, headings, and a table pasted out of the workbook,
and a system that has only ever been tested on Markdown has not been tested on
the thing it will meet.

Same rule as every other format: this reads the IR and nothing else. The prose it
writes is the prose the narrative compiler already produced and the harness
already validated; the figures it writes come from the same resolved cells the
workbook computes. Nothing here can introduce a number, because nothing here is
given the chance to compute one.

Hidden sections are rendered, marked. Markdown includes them and so must this —
a "supporting facts" appendix present in one format and absent in the other would
be two documents of one artifact disagreeing about what the artifact contains,
which is the failure this project exists to prevent. Hidden means *not part of
the readable surface*, not *not written down*.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..models import ArtifactIR, ArtifactSection, CanonicalFact, Table
from ..narrative import references
from . import Rendered, RenderError, ooxml, slug_for
from .values import format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World

MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

#: Artifact types that are documents. A Jira bundle and a workbook are not, and a
#: Confluence page belongs to Confluence — rendering it as Word would assert a
#: filing that does not exist.
HANDLES = frozenset(
    {
        "cfo_variance_memo",
        "executive_summary",
        "incident_rca",
        "working_note",
        "knowledge_article",
        "close_calendar",
    }
)

_AWAITING = (
    "Awaiting narrative. Structure and supporting facts are resolved; "
    "prose is generated by the constrained compiler."
)

_HIDDEN_NOTE = "Not part of the readable surface."


def _require_docx():  # type: ignore[no-untyped-def]
    try:
        import docx
    except ImportError as exc:  # pragma: no cover - depends on install extras
        raise RenderError(
            "the docx format needs python-docx. Install it with: pip install 'worldloom[docx]'"
        ) from exc
    return docx


# ---------------------------------------------------------------------------
# Document furniture
# ---------------------------------------------------------------------------

#: A sober palette. Two greys and one accent — a generated document that reaches
#: for colour is the first thing that reads as generated.
_HEADER_FILL = "2F4858"
_SUBTOTAL_FILL = "EDF2F4"

#: A4, because the worlds this renders are not American. Margins are the ones a
#: corporate template actually uses rather than Word's defaults.
_PAGE = {"width_mm": 210, "height_mm": 297, "margin_mm": 22}

#: Below this many visible sections a contents page is furniture for its own sake.
_TOC_THRESHOLD = 4


def _shade(cell, colour: str) -> None:  # type: ignore[no-untyped-def]
    """Fill one table cell. There is no python-docx API for this; it is w:shd."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    element = OxmlElement("w:shd")
    element.set(qn("w:fill"), colour)
    cell._element.get_or_add_tcPr().append(element)


def _field(paragraph, instruction: str) -> None:  # type: ignore[no-untyped-def]
    """Append a Word field code — the begin / instrText / end triple.

    Fields are how Word expresses anything it computes when the document opens:
    a page number, a contents list. python-docx has no API for them, so the XML
    goes in directly. This is the same principle the workbook follows — a page
    number that was *written* is a number that goes stale the moment a section is
    added, and a contents list of literal text is a lie waiting to happen.
    """
    from docx.oxml import parse_xml
    from docx.oxml.ns import nsdecls

    element = paragraph._element
    for fragment in (
        f'<w:r {nsdecls("w")}><w:fldChar w:fldCharType="begin"/></w:r>',
        f'<w:r {nsdecls("w")}><w:instrText xml:space="preserve">{instruction}</w:instrText></w:r>',
        f'<w:r {nsdecls("w")}><w:fldChar w:fldCharType="end"/></w:r>',
    ):
        element.append(parse_xml(fragment))


def _page_setup(document) -> None:  # type: ignore[no-untyped-def]
    from docx.shared import Mm

    for section in document.sections:
        section.page_width = Mm(_PAGE["width_mm"])
        section.page_height = Mm(_PAGE["height_mm"])
        for edge in ("top_margin", "bottom_margin", "left_margin", "right_margin"):
            setattr(section, edge, Mm(_PAGE["margin_mm"]))


def _running_heads(document, ir: ArtifactIR) -> None:  # type: ignore[no-untyped-def]
    """A header naming the document and a footer that counts its own pages.

    Both are fields rather than text where Word will compute them. A page count
    written as a literal is wrong the moment a section is added, and this corpus
    is regenerated constantly.

    The header names the company as well as the document because a reader holding
    one printed page of a synthetic corpus should be able to tell which world it
    came from without finding the cover.
    """
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt, RGBColor

    section = document.sections[0]

    head = section.header.paragraphs[0]
    head.text = " · ".join(
        part for part in (ir.metadata.get("company"), ir.title) if part
    )
    head.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    for run in head.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x6B, 0x74, 0x7B)

    foot = section.footer.paragraphs[0]
    foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
    foot.text = ""
    label = foot.add_run(
        ir.metadata.get("note", "Synthetic corpus generated by Worldloom.") + "    Page "
    )
    label.font.size = Pt(8)
    label.font.color.rgb = RGBColor(0x6B, 0x74, 0x7B)
    _field(foot, " PAGE ")
    tail = foot.add_run(" of ")
    tail.font.size = Pt(8)
    tail.font.color.rgb = RGBColor(0x6B, 0x74, 0x7B)
    _field(foot, " NUMPAGES ")
    for run in foot.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x6B, 0x74, 0x7B)


def _cover(document, ir: ArtifactIR) -> None:  # type: ignore[no-untyped-def]
    from docx.shared import Pt, RGBColor

    document.add_heading(ir.title, level=0)
    if ir.subtitle:
        subtitle = document.add_paragraph(ir.subtitle)
        subtitle.runs[0].italic = True
        subtitle.runs[0].font.size = Pt(11)
        subtitle.runs[0].font.color.rgb = RGBColor(0x4A, 0x55, 0x5C)

    author = ir.metadata.get("author")
    if author:
        byline = author
        if ir.metadata.get("author_title"):
            byline += f", {ir.metadata['author_title']}"
        document.add_paragraph(byline).runs[0].bold = True

    notice = document.add_paragraph(
        ir.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")
    )
    notice.runs[0].italic = True
    notice.runs[0].font.size = Pt(8)
    notice.runs[0].font.color.rgb = RGBColor(0x6B, 0x74, 0x7B)


def _contents(document, ir: ArtifactIR) -> None:  # type: ignore[no-untyped-def]
    """A contents field, on documents long enough to need one.

    A field rather than a written list: Word builds it from the headings actually
    present when the document opens, so it cannot drift from the document the way
    a typed list would.
    """
    visible = [s for s in ir.sections if not s.hidden]
    if len(visible) < _TOC_THRESHOLD:
        return

    document.add_heading("Contents", level=1)
    _field(document.add_paragraph(), r' TOC \o "1-2" \h \z \u ')
    document.add_page_break()

def _table(document, table: Table) -> None:  # type: ignore[no-untyped-def]
    """One IR table as a Word table.

    A label column then one column per measure, matching the Markdown rendering
    cell for cell — the values come from ``format_value``, which both formats
    share so neither can round differently from the other.

    Numbers are right-aligned and subtotal rows shaded, because a financial table
    that is not aligned on the decimal is one a finance reader cannot scan, and
    scanning is the only thing they will do with it.
    """
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt, RGBColor

    grid = document.add_table(rows=1, cols=len(table.columns) + 1)
    grid.style = "Table Grid"

    header = grid.rows[0].cells
    header[0].text = table.title
    for index, column in enumerate(table.columns, start=1):
        header[index].text = column.label
    for cell in header:
        _shade(cell, _HEADER_FILL)
        for paragraph in cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            for run in paragraph.runs:
                run.bold = True
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
    header[0].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.LEFT

    for row in table.rows:
        cells = grid.add_row().cells
        cells[0].text = row.label
        for index, column in enumerate(table.columns, start=1):
            cell = row.cells.get(column.key)
            value = cell.value if cell else None
            cells[index].text = format_value(value, column.number_format) if cell else ""
            paragraph = cells[index].paragraphs[0]
            if isinstance(value, (int, float)):
                paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
                # A negative in an accounting format is already parenthesised by
                # `format_value`; the colour is the second signal, not the first,
                # so the table survives being printed in black and white.
                if value < 0:
                    for run in paragraph.runs:
                        run.font.color.rgb = RGBColor(0x9B, 0x22, 0x26)
        for cell in cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(9)
                    run.bold = bool(row.emphasis)
            if row.emphasis:
                _shade(cell, _SUBTOTAL_FILL)

    if table.note:
        note = document.add_paragraph(table.note)
        note.runs[0].italic = True
        note.runs[0].font.size = Pt(8)
        note.runs[0].font.color.rgb = RGBColor(0x6B, 0x74, 0x7B)


#: How wide the widest bar in a figure is drawn, in block characters.
_BAR_WIDTH = 28


def _figure(document, chart, table: Table) -> None:  # type: ignore[no-untyped-def]
    """A declared chart, drawn with the means Word gives us for free.

    Not a native chart: python-docx has no API for DrawingML charts, and the two
    alternatives both cost more than they return. A plotted image needs matplotlib
    — thirty megabytes of dependency and a new determinism surface, for a picture
    of numbers that are already in the table above. Hand-writing the chart part
    means composing an embedded workbook inside the document package.

    So the figure is drawn as proportional bars from the same cells the table
    shows. It is deterministic, it needs nothing installed, it prints, and a
    reader can check every bar against the row beside it. Native charts live in
    the formats whose libraries actually support them.
    """
    from docx.shared import Pt, RGBColor

    if not chart.series:
        return
    measure = chart.series[0]
    column = table.column(measure)
    rows = [row for row in table.rows if row.key in set(chart.rows)] or list(table.rows)

    values: list[tuple[str, float]] = []
    for row in rows:
        cell = row.cells.get(measure)
        if cell is not None and isinstance(cell.value, (int, float)):
            values.append((row.label, float(cell.value)))
    if not values:
        return

    caption = document.add_paragraph()
    label = caption.add_run(f"Figure — {chart.title}")
    label.bold = True
    label.font.size = Pt(9)

    widest = max(abs(value) for _, value in values) or 1.0
    grid = document.add_table(rows=0, cols=3)
    for name, value in values:
        cells = grid.add_row().cells
        cells[0].text = name
        cells[1].text = format_value(value, column.number_format if column else None)
        cells[2].text = "█" * max(1, round(abs(value) / widest * _BAR_WIDTH))
        for index, cell in enumerate(cells):
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(8)
                    if index == 2:
                        run.font.color.rgb = (
                            RGBColor(0x9B, 0x22, 0x26) if value < 0
                            else RGBColor(0x2F, 0x48, 0x58)
                        )

    if chart.note:
        note = document.add_paragraph(chart.note)
        note.runs[0].italic = True
        note.runs[0].font.size = Pt(8)


def _section(document, section: ArtifactSection, facts) -> None:  # type: ignore[no-untyped-def]
    document.add_heading(section.heading, level=1)
    if section.hidden:
        marker = document.add_paragraph(_HIDDEN_NOTE)
        marker.runs[0].italic = True

    if section.body:
        text = references.substitute(section.body, facts) if facts else section.body
        # Blank lines are paragraph breaks. Word has no other way to say it, and a
        # single run containing newlines renders as one unbroken block.
        for block in (part.strip() for part in text.split("\n\n")):
            if block:
                document.add_paragraph(block)
    elif section.table is not None:
        _table(document, section.table)
    else:
        awaiting = document.add_paragraph(_AWAITING)
        awaiting.runs[0].italic = True

    # After the chain, never inside it — a `for` between the `elif` and the
    # `else` binds the `else` to the loop, and Python runs a loop-else whenever
    # the loop did not break. That mistake put an "awaiting narrative" notice
    # under finished prose in the Markdown renderer.
    for chart in section.charts:
        if section.table is not None:
            _figure(document, chart, section.table)


def render(ir: ArtifactIR, facts: dict[str, CanonicalFact] | None = None) -> bytes:
    """Render one IR to DOCX bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render
    time. Without it the references stay visible, which is the right failure — a
    document that quietly drops a figure reads as complete and is not.
    """
    docx = _require_docx()
    document = docx.Document()

    _page_setup(document)
    _running_heads(document, ir)
    _cover(document, ir)
    _contents(document, ir)

    for section in ir.sections:
        _section(document, section, facts)

    if ir.metadata.get("voice"):
        closing = document.add_paragraph(
            f"Author voice: {ir.metadata['voice']}. Persona: {ir.metadata.get('persona', '')}."
        )
        closing.runs[0].italic = True

    properties = document.core_properties
    properties.title = ir.title
    properties.subject = ir.subtitle or ""
    properties.author = ir.metadata.get("author") or "Worldloom"
    properties.comments = ir.metadata.get(
        "note", "Synthetic corpus generated by Worldloom."
    )
    properties.keywords = "synthetic,worldloom,seed=" + ir.metadata.get("worldloom_seed", "")

    from io import BytesIO

    buffer = BytesIO()
    document.save(buffer)
    # Dates come from the world, never the clock. python-docx would otherwise
    # ship its template's own 2013 timestamps, which is a smaller lie than
    # `now()` and still a wrong one.
    return ooxml.normalise(buffer.getvalue(), created=ir.metadata.get("worldloom_created"))


def render_all(world: World) -> list[Rendered]:
    """Render every document-shaped artifact in *world*."""
    facts = {fact.id: fact for fact in world.facts}
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type not in HANDLES:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.docx",
                media_type=MEDIA_TYPE,
                payload=render(ir, facts),
            )
        )
    return out
