"""The DOCX renderer.

Word is where enterprise narrative actually lives. A retrieval corpus made of
Markdown is a corpus of a shape no enterprise has — the memo a controller writes
is a ``.docx`` with a byline, headings, and a table pasted out of the workbook,
and a system that has only ever been tested on Markdown has not been tested on
the thing it will meet.

Same rule as every other format: this reads the IR and nothing else. The prose it
writes is the prose the narrative compiler already produced and the harness
already validated; the figures it writes come from the same resolved cells the
workbook computes. Nothing here can introduce a number, because nothing here is
given the chance to compute one.

Hidden sections are rendered, marked. Markdown includes them and so must this —
a "supporting facts" appendix present in one format and absent in the other would
be two documents of one artifact disagreeing about what the artifact contains,
which is the failure this project exists to prevent. Hidden means *not part of
the readable surface*, not *not written down*.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..models import ArtifactIR, ArtifactSection, CanonicalFact, Table
from ..narrative import references
from . import Rendered, RenderError, ooxml, slug_for
from .values import format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World

MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

#: Artifact types that are documents. A Jira bundle and a workbook are not, and a
#: Confluence page belongs to Confluence — rendering it as Word would assert a
#: filing that does not exist.
HANDLES = frozenset(
    {
        "cfo_variance_memo",
        "executive_summary",
        "incident_rca",
        "working_note",
        "knowledge_article",
        "close_calendar",
    }
)

_AWAITING = (
    "Awaiting narrative. Structure and supporting facts are resolved; "
    "prose is generated by the constrained compiler."
)

_HIDDEN_NOTE = "Not part of the readable surface."


def _require_docx():  # type: ignore[no-untyped-def]
    try:
        import docx
    except ImportError as exc:  # pragma: no cover - depends on install extras
        raise RenderError(
            "the docx format needs python-docx. Install it with: pip install 'worldloom[docx]'"
        ) from exc
    return docx


def _table(document, table: Table) -> None:  # type: ignore[no-untyped-def]
    """One IR table as a Word table.

    A label column then one column per measure, matching the Markdown rendering
    cell for cell — the values come from ``format_value``, which both formats
    share so neither can round differently from the other.
    """
    grid = document.add_table(rows=1, cols=len(table.columns) + 1)
    grid.style = "Table Grid"

    header = grid.rows[0].cells
    header[0].text = table.title
    for index, column in enumerate(table.columns, start=1):
        header[index].text = column.label
    for cell in header:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True

    for row in table.rows:
        cells = grid.add_row().cells
        cells[0].text = row.label
        for index, column in enumerate(table.columns, start=1):
            cell = row.cells.get(column.key)
            cells[index].text = format_value(cell.value, column.number_format) if cell else ""
        if row.emphasis:
            for cell in cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.bold = True

    if table.note:
        note = document.add_paragraph(table.note)
        note.runs[0].italic = True


def _section(document, section: ArtifactSection, facts) -> None:  # type: ignore[no-untyped-def]
    document.add_heading(section.heading, level=1)
    if section.hidden:
        marker = document.add_paragraph(_HIDDEN_NOTE)
        marker.runs[0].italic = True

    if section.body:
        text = references.substitute(section.body, facts) if facts else section.body
        # Blank lines are paragraph breaks. Word has no other way to say it, and a
        # single run containing newlines renders as one unbroken block.
        for block in (part.strip() for part in text.split("\n\n")):
            if block:
                document.add_paragraph(block)
    elif section.table is not None:
        _table(document, section.table)
    else:
        awaiting = document.add_paragraph(_AWAITING)
        awaiting.runs[0].italic = True


def render(ir: ArtifactIR, facts: dict[str, CanonicalFact] | None = None) -> bytes:
    """Render one IR to DOCX bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render
    time. Without it the references stay visible, which is the right failure — a
    document that quietly drops a figure reads as complete and is not.
    """
    docx = _require_docx()
    document = docx.Document()

    document.add_heading(ir.title, level=0)
    if ir.subtitle:
        subtitle = document.add_paragraph(ir.subtitle)
        subtitle.runs[0].italic = True

    author = ir.metadata.get("author")
    if author:
        byline = author
        if ir.metadata.get("author_title"):
            byline += f", {ir.metadata['author_title']}"
        document.add_paragraph(byline).runs[0].bold = True

    notice = document.add_paragraph(
        ir.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")
    )
    notice.runs[0].italic = True

    for section in ir.sections:
        _section(document, section, facts)

    if ir.metadata.get("voice"):
        closing = document.add_paragraph(
            f"Author voice: {ir.metadata['voice']}. Persona: {ir.metadata.get('persona', '')}."
        )
        closing.runs[0].italic = True

    properties = document.core_properties
    properties.title = ir.title
    properties.subject = ir.subtitle or ""
    properties.author = author or "Worldloom"
    properties.comments = ir.metadata.get(
        "note", "Synthetic corpus generated by Worldloom."
    )
    properties.keywords = "synthetic,worldloom,seed=" + ir.metadata.get("worldloom_seed", "")

    from io import BytesIO

    buffer = BytesIO()
    document.save(buffer)
    # Dates come from the world, never the clock. python-docx would otherwise
    # ship its template's own 2013 timestamps, which is a smaller lie than
    # `now()` and still a wrong one.
    return ooxml.normalise(buffer.getvalue(), created=ir.metadata.get("worldloom_created"))


def render_all(world: World) -> list[Rendered]:
    """Render every document-shaped artifact in *world*."""
    facts = {fact.id: fact for fact in world.facts}
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type not in HANDLES:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.docx",
                media_type=MEDIA_TYPE,
                payload=render(ir, facts),
            )
        )
    return out
