"""The Markdown renderer.

Renders any IR, which makes it the fallback that keeps every artifact readable
even before its native format exists. Cheap, diffable, and reviewable in a pull
request — which matters more than it sounds for a corpus whose whole claim is
that its documents agree with each other.

Where XLSX emits a formula, Markdown emits the literal value from the same cell.
Both are correct and both agree, because both read one resolved IR.

A section awaiting prose says so, rather than being filled with something
plausible. An empty heading is honest; invented narrative is not.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..locales import DEFAULT as DEFAULT_LOCALE, Locale
from ..models import ArtifactIR, CanonicalFact, Chart, Table
from ..narrative import references
from . import Rendered, slug_for
from .values import corpus_locale, format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World


def _table(table: Table, locale: Locale = DEFAULT_LOCALE) -> str:
    """One table as GitHub-flavoured Markdown."""
    header = ["", *[column.label for column in table.columns]]
    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join("---" for _ in header) + " |",
    ]
    for row in table.rows:
        cells = [f"**{row.label}**" if row.emphasis else row.label]
        for column in table.columns:
            cell = row.cells.get(column.key)
            text = format_value(cell.value, column.number_format, locale=locale) if cell else ""
            cells.append(f"**{text}**" if row.emphasis and text else text)
        lines.append("| " + " | ".join(cells) + " |")

    if table.note:
        lines += ["", f"*{table.note}*"]
    return "\n".join(lines)


def _caption(chart: Chart, table: Table | None) -> str:
    """A chart named rather than drawn.

    Markdown cannot draw one, and inventing an ASCII approximation would be a
    second rendering of the data that could disagree with the table above it. So
    the chart is announced and its data left where it already is — the reader sees
    the same numbers the workbook plots, one screen up.
    """
    labels = [
        (table.column(key).label if table and table.column(key) else key)
        for key in chart.series
    ]
    lines = [f"**Figure — {chart.title}** *({chart.kind.value} chart of {', '.join(labels)})*"]
    if chart.note:
        lines.append(f"*{chart.note}*")
    return "\n\n".join(lines)


def render(
    ir: ArtifactIR,
    facts: dict[str, CanonicalFact] | None = None,
    *,
    locale: Locale = DEFAULT_LOCALE,
) -> bytes:
    """Render one IR to Markdown bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render time.
    Without it the references stay visible, which is the right failure — a document
    that quietly drops a figure reads as complete and is not.

    *locale* spells every figure, in the table and in the prose alike. Defaulted
    rather than required because a determinism check that renders one IR in
    isolation has no world to ask; ``render_all`` always passes the corpus's.
    """
    parts: list[str] = [f"# {ir.title}"]
    if ir.subtitle:
        parts.append(f"**{ir.subtitle}**")

    author = ir.metadata.get("author")
    if author:
        byline = author
        if ir.metadata.get("author_title"):
            byline += f", {ir.metadata['author_title']}"
        parts.append(byline)

    parts.append(
        "> "
        + ir.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")
    )

    for section in ir.sections:
        heading = f"## {section.heading}"
        if section.hidden:
            heading += " *(not part of the readable surface)*"
        parts.append(heading)

        if section.body:
            parts.append(
                references.substitute(section.body, facts, locale=locale)
                if facts else section.body
            )
        elif section.table is not None:
            parts.append(_table(section.table, locale))

        else:
            parts.append(
                "*Awaiting narrative. Structure and supporting facts are resolved; "
                "prose is generated by the constrained compiler.*"
            )

        # After the chain, never inside it. A `for` placed between the `elif` and
        # the `else` above binds the `else` to the loop rather than to the
        # conditional, and Python runs a loop-else whenever the loop did not
        # break — so every chartless section quietly grew an "awaiting narrative"
        # notice under finished prose.
        for chart in section.charts:
            parts.append(_caption(chart, section.table))

    if ir.metadata.get("voice"):
        parts.append(
            f"---\n\n*Author voice: {ir.metadata['voice']}. "
            f"Persona: {ir.metadata.get('persona', '')}.*"
        )

    return ("\n\n".join(parts).rstrip() + "\n").encode("utf-8")


#: Types with a native format of their own. Markdown still renders them on
#: request, but ``render_all`` leaves them to the format that owns them.
#: Types markdown must not render because a dedicated format owns them — a
#: workbook belongs to its sheet, a ticket to its bundle. Domain modules add
#: their own source artifacts via `own_elsewhere` when they register a
#: dedicated renderer for them.
_OWNED_ELSEWHERE = {"finance_workbook", "jira_issues", "servicenow_incident"}


def own_elsewhere(*artifact_types: str) -> None:
    """Exclude *artifact_types* from the markdown fallback."""
    _OWNED_ELSEWHERE.update(artifact_types)

def render_all(world: World) -> list[Rendered]:
    """Render every artifact that has no more specific format."""
    locale = corpus_locale(world)
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type in _OWNED_ELSEWHERE:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.md",
                media_type="text/markdown",
                payload=render(ir, {fact.id: fact for fact in world.facts}, locale=locale),
            )
        )
    return out
