"""The Markdown renderer.

Renders any IR, which makes it the fallback that keeps every artifact readable
even before its native format exists. Cheap, diffable, and reviewable in a pull
request — which matters more than it sounds for a corpus whose whole claim is
that its documents agree with each other.

Where XLSX emits a formula, Markdown emits the literal value from the same cell.
Both are correct and both agree, because both read one resolved IR.

A section awaiting prose says so, rather than being filled with something
plausible. An empty heading is honest; invented narrative is not.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..models import ArtifactIR, CanonicalFact, Table
from ..narrative import references
from . import Rendered, slug_for
from .values import format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World


def _table(table: Table) -> str:
    """One table as GitHub-flavoured Markdown."""
    header = ["", *[column.label for column in table.columns]]
    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join("---" for _ in header) + " |",
    ]
    for row in table.rows:
        cells = [f"**{row.label}**" if row.emphasis else row.label]
        for column in table.columns:
            cell = row.cells.get(column.key)
            text = format_value(cell.value, column.number_format) if cell else ""
            cells.append(f"**{text}**" if row.emphasis and text else text)
        lines.append("| " + " | ".join(cells) + " |")

    if table.note:
        lines += ["", f"*{table.note}*"]
    return "\n".join(lines)


def render(ir: ArtifactIR, facts: dict[str, CanonicalFact] | None = None) -> bytes:
    """Render one IR to Markdown bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render time.
    Without it the references stay visible, which is the right failure — a document
    that quietly drops a figure reads as complete and is not.
    """
    parts: list[str] = [f"# {ir.title}"]
    if ir.subtitle:
        parts.append(f"**{ir.subtitle}**")

    author = ir.metadata.get("author")
    if author:
        byline = author
        if ir.metadata.get("author_title"):
            byline += f", {ir.metadata['author_title']}"
        parts.append(byline)

    parts.append(
        "> "
        + ir.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")
    )

    for section in ir.sections:
        heading = f"## {section.heading}"
        if section.hidden:
            heading += " *(not part of the readable surface)*"
        parts.append(heading)

        if section.body:
            parts.append(references.substitute(section.body, facts) if facts else section.body)
        elif section.table is not None:
            parts.append(_table(section.table))
        else:
            parts.append(
                "*Awaiting narrative. Structure and supporting facts are resolved; "
                "prose is generated by the constrained compiler.*"
            )

    if ir.metadata.get("voice"):
        parts.append(
            f"---\n\n*Author voice: {ir.metadata['voice']}. "
            f"Persona: {ir.metadata.get('persona', '')}.*"
        )

    return ("\n\n".join(parts).rstrip() + "\n").encode("utf-8")


#: Types with a native format of their own. Markdown still renders them on
#: request, but ``render_all`` leaves them to the format that owns them.
_OWNED_ELSEWHERE = frozenset(
    {"finance_workbook", "jira_issues", "servicenow_incident"}
)

def render_all(world: World) -> list[Rendered]:
    """Render every artifact that has no more specific format."""
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type in _OWNED_ELSEWHERE:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.md",
                media_type="text/markdown",
                payload=render(ir, {fact.id: fact for fact in world.facts}),
            )
        )
    return out
