"""The native PDF renderer.

``docs/artifact-compiler.md`` §9.4 treats PDF as "derived by default" — DOCX and
PPTX converted through LibreOffice — and reserves a native renderer for an
artifact whose *canonical* form is PDF. This module exists anyway, because the
derived path cannot satisfy the property every other format in this package is
held to: CI regenerates a corpus from its ledger and diffs it byte-for-byte, and
a LibreOffice conversion is not byte-reproducible across machines or LibreOffice
versions — it is an external, version-dependent binary, not a projection of the
IR. A derived PDF can be a *preview* for the visual harness (§11.D scopes it
exactly that way, "behind capability detection"); it can never be a ``-f pdf``
corpus artifact. So ``-f pdf`` is a second, deterministic, pure-Python projection
of the same ``ArtifactIR`` the DOCX renderer reads — built with ``reportlab``,
which never shells out — rather than a conversion of the DOCX renderer's own
output.

Same rule as every other renderer: this reads the IR and nothing else. Every
figure it draws is a cell ``format_value`` already agreed on with Markdown and
DOCX; nothing here computes one. See ``tests/test_pdf.py`` for the proof that
two renders of the same IR, even in separate processes, are byte-identical —
the property a derived PDF could never offer.

Hidden sections are rendered, marked, exactly as DOCX and Markdown do — an
appendix present in one format and silently absent from another is two
documents of one artifact disagreeing about what the artifact contains.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from io import BytesIO
from typing import TYPE_CHECKING
from xml.sax.saxutils import escape as _escape

from ..compiler.compose import compose, plan_from_ir
from ..compiler.grammar import GrammarViolation
from ..compiler.plan import SizeClass
from ..models import ArtifactIR, ArtifactSection, CanonicalFact, Table
from ..narrative import references
from . import Rendered, RenderError, ooxml, slug_for
from .docx import HANDLES
from .values import format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World

MEDIA_TYPE = "application/pdf"

_AWAITING = (
    "Awaiting narrative. Structure and supporting facts are resolved; "
    "prose is generated by the constrained compiler."
)

_HIDDEN_NOTE = "Not part of the readable surface."

#: A sober palette, matching DOCX exactly — one artifact rendered in two formats
#: that disagreed about colour would read as two artifacts.
_HEADER_FILL = "2F4858"
_SUBTOTAL_FILL = "EDF2F4"
_NEGATIVE = "9B2226"
_MUTED = "6B747B"
_INK = "1A1A1A"

#: A4 with the same corporate margins as `render/docx.py`. Kept in points rather
#: than reaching for `reportlab.lib.units.mm` at module scope, so this geometry —
#: and the ``DocumentPlan`` built from it — exists and is inspectable even before
#: `_require_reportlab` has proven the library is installed.
_MM_TO_PT = 72.0 / 25.4
_PAGE_MM = {"width": 210, "height": 297, "margin": 22}
_PAGE_WIDTH_PT = _PAGE_MM["width"] * _MM_TO_PT
_PAGE_HEIGHT_PT = _PAGE_MM["height"] * _MM_TO_PT
_MARGIN_PT = _PAGE_MM["margin"] * _MM_TO_PT
_FRAME_WIDTH_PT = _PAGE_WIDTH_PT - 2 * _MARGIN_PT
_FRAME_HEIGHT_PT = _PAGE_HEIGHT_PT - 2 * _MARGIN_PT


def _require_reportlab():  # type: ignore[no-untyped-def]
    try:
        import reportlab
    except ImportError as exc:  # pragma: no cover - depends on install extras
        raise RenderError(
            "the pdf format needs reportlab. Install it with: pip install 'worldloom[pdf]'"
        ) from exc
    return reportlab


# ---------------------------------------------------------------------------
# The document plan
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DocumentPlan:
    """Renderer-local: fixed page geometry, plus the section order and any drops
    the artifact compiler decided.

    Per ``docs/artifact-compiler.md`` §2, a plan may decide which page a section
    lands on and whether detail moves to an appendix; it may not decide which
    facts are true or which rows belong in a table — those are already fixed by
    the time an ``ArtifactIR`` exists. Never persisted: rebuilt from the IR on
    every render, so it cannot drift from the artifact it describes.
    """

    page_width_pt: float
    page_height_pt: float
    margin_pt: float
    sections: tuple[ArtifactSection, ...]
    """``ir.sections``, reordered exactly as the compiler's composition ordered
    the beats built from them — identity order today, since nothing in the
    shipped vocabulary requires a repair (`compose._repair_order`), but this is
    what makes a future reorder or drop take effect here without a second
    decision being made in this module."""
    dropped: tuple[str, ...]
    """Section headings the compiler dropped as over-budget optional material.
    Always empty against the artifacts this repository ships — see the report
    for why — but respected rather than assumed away."""
    violations: tuple[GrammarViolation, ...]
    """Grammar violations in the composed sequence, carried through rather than
    silenced. Empty for every shipped artifact type; a non-empty tuple here is
    a defect upstream of this renderer, not something this module can repair,
    so it does not raise — the caller (a future validator) can inspect it."""


def _plan(ir: ArtifactIR, artifact_type: str, size_class: SizeClass) -> DocumentPlan:
    """Derive a page plan from *ir* via the artifact compiler.

    Composed against ``pdf`` in its own right. This originally borrowed
    ``docx``, because no component declared ``pdf`` at all — a reasonable
    stopgap that was also a quiet lie: it would have kept working, and kept
    reporting success, long after the two formats diverged. Every component
    spellable in Word is spellable in a fixed-page projection of the same IR,
    so the registry now says so, and this asks for what it actually renders.
    """
    plan = plan_from_ir(ir, artifact_type=artifact_type, size_class=size_class)
    try:
        composition = compose(plan, fmt="pdf")
    except ValueError as exc:
        raise RenderError(f"{ir.id}: cannot compose a page plan: {exc}") from exc

    # `plan.beats` is built one beat per `ir.section`, in that same order (see
    # `plan_from_ir`), so this zip is a true parallel pairing rather than a
    # guess — the only thing `composition.beats` can have done to that order is
    # drop entries or move one earlier via `_repair_order`.
    section_by_beat = dict(zip((beat.key for beat in plan.beats), ir.sections))
    ordered = tuple(section_by_beat[key] for key in composition.beats)

    return DocumentPlan(
        page_width_pt=_PAGE_WIDTH_PT,
        page_height_pt=_PAGE_HEIGHT_PT,
        margin_pt=_MARGIN_PT,
        sections=ordered,
        dropped=composition.dropped,
        violations=composition.violations,
    )


# ---------------------------------------------------------------------------
# Determinism: the PDF-specific clock and identity hazards
# ---------------------------------------------------------------------------

_CREATION_DATE = re.compile(rb"(/CreationDate\s*\()[^)]*(\))")
_MOD_DATE = re.compile(rb"(/ModDate\s*\()[^)]*(\))")


def _pdf_date(instant: tuple[int, int, int, int, int, int]) -> str:
    """*instant* as a PDF date string, ``D:YYYYMMDDHHmmSS+00'00'``."""
    year, month, day, hour, minute, second = instant
    return f"D:{year:04d}{month:02d}{day:02d}{hour:02d}{minute:02d}{second:02d}+00'00'"


def _normalise(payload: bytes) -> bytes:
    """Rewrite ``/CreationDate`` and ``/ModDate`` to the epoch every Office
    package in this repository already uses.

    reportlab's own ``invariant=True`` (passed when the document is built)
    already does most of the work: it swaps ``time.time()`` for a fixed instant
    project-wide, which is what keeps `/ID` — a hash of document content salted
    with that instant — a function of content alone rather than of content and
    wall-clock time. But the instant reportlab substitutes is *its* choice
    (2000-01-01), not this project's. `render/ooxml.py` fixes the equivalent
    hazard in DOCX and XLSX to ``EPOCH = (1980, 1, 1, 0, 0, 0)``; this rewrites
    the same two Info-dictionary fields to that instant so a PDF and a DOCX of
    the same corpus agree about when the corpus was made, rather than each
    being internally constant but disagreeing with the other.

    A narrow byte substitution, like `ooxml.normalise` — the value is a literal
    PDF string with no nested parentheses, so this does not need a PDF parser.
    """
    stamp = _pdf_date(ooxml.EPOCH).encode()
    payload = _CREATION_DATE.sub(rb"\g<1>" + stamp + rb"\g<2>", payload, count=1)
    payload = _MOD_DATE.sub(rb"\g<1>" + stamp + rb"\g<2>", payload, count=1)
    return payload


# ---------------------------------------------------------------------------
# Paragraph styles
# ---------------------------------------------------------------------------


def _styles() -> dict:  # type: ignore[no-untyped-def]
    """Every named style this renderer draws with, built once per render call.

    Deferred behind `_require_reportlab` rather than built at import time —
    same reason every other reportlab name in this module is imported inside a
    function: an optional dependency for one format must not break import of
    the package as a whole (see `render/__init__.py`).
    """
    from reportlab.lib.colors import HexColor
    from reportlab.lib.enums import TA_LEFT, TA_RIGHT
    from reportlab.lib.styles import ParagraphStyle

    muted = HexColor(f"#{_MUTED}")
    negative = HexColor(f"#{_NEGATIVE}")
    accent = HexColor(f"#{_HEADER_FILL}")
    ink = HexColor(f"#{_INK}")
    white = HexColor("#FFFFFF")

    def cell(name: str, *, bold: bool = False, right: bool = False, colour=ink):  # type: ignore[no-untyped-def]
        return ParagraphStyle(
            name,
            fontName="Helvetica-Bold" if bold else "Helvetica",
            fontSize=9,
            leading=11,
            alignment=TA_RIGHT if right else TA_LEFT,
            textColor=colour,
        )

    return {
        "title": ParagraphStyle(
            "wl-title", fontName="Helvetica-Bold", fontSize=22, leading=26,
            spaceAfter=6, textColor=ink,
        ),
        "subtitle": ParagraphStyle(
            "wl-subtitle", fontName="Helvetica-Oblique", fontSize=11, leading=14,
            spaceAfter=4, textColor=HexColor("#4A555C"),
        ),
        "byline": ParagraphStyle(
            "wl-byline", fontName="Helvetica-Bold", fontSize=10, leading=13,
            spaceAfter=10, textColor=ink,
        ),
        "notice": ParagraphStyle(
            "wl-notice", fontName="Helvetica-Oblique", fontSize=8, leading=10,
            spaceAfter=16, textColor=muted,
        ),
        "heading": ParagraphStyle(
            "wl-heading", fontName="Helvetica-Bold", fontSize=13, leading=16,
            spaceBefore=14, spaceAfter=6, textColor=accent,
        ),
        "purpose": ParagraphStyle(
            "wl-purpose", fontName="Helvetica-Oblique", fontSize=9, leading=12,
            spaceAfter=6, textColor=muted,
        ),
        "body": ParagraphStyle(
            "wl-body", fontName="Helvetica", fontSize=10, leading=14,
            spaceAfter=8, textColor=ink,
        ),
        "awaiting": ParagraphStyle(
            "wl-awaiting", fontName="Helvetica-Oblique", fontSize=9.5, leading=13,
            spaceAfter=8, textColor=muted,
        ),
        "hidden": ParagraphStyle(
            "wl-hidden", fontName="Helvetica-Oblique", fontSize=9, leading=12,
            spaceAfter=6, textColor=muted,
        ),
        "note": ParagraphStyle(
            "wl-note", fontName="Helvetica-Oblique", fontSize=8, leading=11,
            spaceAfter=10, textColor=muted,
        ),
        "figure_title": ParagraphStyle(
            "wl-figure-title", fontName="Helvetica-Bold", fontSize=9, leading=11,
            spaceAfter=4, textColor=ink,
        ),
        "figure_note": ParagraphStyle(
            "wl-figure-note", fontName="Helvetica-Oblique", fontSize=8, leading=10,
            spaceBefore=4, textColor=muted,
        ),
        "cell": cell("wl-cell"),
        "cell_bold": cell("wl-cell-bold", bold=True),
        "cell_header": cell("wl-cell-header", bold=True, colour=white),
        "cell_right": cell("wl-cell-right", right=True),
        "cell_right_bold": cell("wl-cell-right-bold", bold=True, right=True),
        "cell_right_header": cell("wl-cell-right-header", bold=True, right=True, colour=white),
        "cell_right_negative": cell("wl-cell-right-negative", right=True, colour=negative),
        "cell_right_negative_bold": cell(
            "wl-cell-right-negative-bold", bold=True, right=True, colour=negative
        ),
    }


# ---------------------------------------------------------------------------
# Tables and figures
# ---------------------------------------------------------------------------


def _table_flowable(table: Table, frame_width: float, styles: dict):  # type: ignore[no-untyped-def]
    """One IR table as a paginating platypus table.

    ``repeatRows=1`` is what gives this renderer real pagination for free: when
    platypus splits a table across a page boundary it repeats row 0 — our
    header — on the continuation, which is the "header repeated" half of the
    task's pagination rule stated as a table property rather than code this
    module has to write. The other half — a single row too tall for an empty
    page — is not a per-table decision; see `render` for how that is handled
    when it happens.

    Numbers are right-aligned and subtotal rows shaded, matching
    `render/docx.py::_table` cell for cell, because both read the same
    `format_value` and a reader should not be able to tell which renderer
    produced a given figure.
    """
    from reportlab.lib import colors
    from reportlab.platypus import Paragraph
    from reportlab.platypus import Table as PlatypusTable
    from reportlab.platypus import TableStyle

    label_width = frame_width * 0.34
    per_column = (frame_width - label_width) / max(1, len(table.columns))
    col_widths = [label_width] + [per_column] * len(table.columns)

    header_row = [Paragraph(_escape(table.title), styles["cell_header"])]
    header_row += [Paragraph(_escape(column.label), styles["cell_right_header"]) for column in table.columns]
    data = [header_row]

    commands = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(f"#{_HEADER_FILL}")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#C7CDD1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]

    for row_index, row in enumerate(table.rows, start=1):
        cells = [Paragraph(_escape(row.label), styles["cell_bold" if row.emphasis else "cell"])]
        for column in table.columns:
            cell = row.cells.get(column.key)
            value = cell.value if cell else None
            text = format_value(value, column.number_format) if cell else ""
            negative = isinstance(value, (int, float)) and value < 0
            # A negative is already parenthesised by `format_value`; colour is
            # the second signal, never the only one, so the table survives
            # being printed in black and white — same rule `docx._table` uses.
            key = (
                "cell_right_negative_bold" if negative and row.emphasis
                else "cell_right_negative" if negative
                else "cell_right_bold" if row.emphasis
                else "cell_right"
            )
            cells.append(Paragraph(_escape(text), styles[key]))
        data.append(cells)
        if row.emphasis:
            commands.append(("BACKGROUND", (0, row_index), (-1, row_index), colors.HexColor(f"#{_SUBTOTAL_FILL}")))

    grid = PlatypusTable(data, colWidths=col_widths, repeatRows=1)
    grid.setStyle(TableStyle(commands))
    return grid


def _figure_flowables(chart, table: Table, frame_width: float, styles: dict) -> list:  # type: ignore[no-untyped-def]
    """A declared chart, drawn as proportional bars from the same cells the
    table above shows — never a second computation of the data.

    `render/docx.py::_figure` draws its bars from block glyphs (``█``) because
    python-docx has no drawing API to reach for. reportlab's canvas does, and a
    block glyph turned out to be the wrong choice to port: it sits outside the
    WinAnsi encoding the base-14 fonts use, so Helvetica silently substitutes an
    unrelated character for it — confirmed while building this renderer by
    inspecting the emitted content stream. A rectangle scaled by simple
    arithmetic (see `_Bar` below) is exactly as deterministic as a glyph count
    and does not depend on what a font happens to map a codepoint to.
    """
    from reportlab.lib import colors
    from reportlab.platypus import Flowable, Paragraph
    from reportlab.platypus import Table as PlatypusTable
    from reportlab.platypus import TableStyle

    class _Bar(Flowable):
        """A single proportional bar, vector-drawn to a fixed height."""

        def __init__(self, fraction: float, width: float, height: float, colour) -> None:  # type: ignore[no-untyped-def]
            super().__init__()
            self.fraction = fraction
            self.width = width
            self.height = height
            self.colour = colour

        def wrap(self, avail_width: float, avail_height: float) -> tuple[float, float]:
            return self.width, self.height

        def draw(self) -> None:
            self.canv.setFillColor(self.colour)
            self.canv.rect(0, 0, self.width * self.fraction, self.height, stroke=0, fill=1)

    if not chart.series:
        return []
    measure = chart.series[0]
    column = table.column(measure)
    rows = [row for row in table.rows if row.key in set(chart.rows)] or list(table.rows)

    values: list[tuple[str, float]] = []
    for row in rows:
        cell = row.cells.get(measure)
        if cell is not None and isinstance(cell.value, (int, float)):
            values.append((row.label, float(cell.value)))
    if not values:
        return []

    widest = max(abs(value) for _, value in values) or 1.0
    label_width = frame_width * 0.30
    value_width = frame_width * 0.20
    bar_width = frame_width - label_width - value_width

    data = []
    commands = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]
    for name, value in values:
        colour = colors.HexColor(f"#{_NEGATIVE if value < 0 else _HEADER_FILL}")
        fraction = min(1.0, abs(value) / widest)
        formatted = format_value(value, column.number_format if column else None)
        data.append([
            Paragraph(_escape(name), styles["cell"]),
            Paragraph(_escape(formatted), styles["cell_right"]),
            _Bar(fraction, bar_width, 8, colour),
        ])

    grid = PlatypusTable(data, colWidths=[label_width, value_width, bar_width])
    grid.setStyle(TableStyle(commands))

    flow = [Paragraph(f"Figure — {_escape(chart.title)}", styles["figure_title"]), grid]
    if chart.note:
        flow.append(Paragraph(_escape(chart.note), styles["figure_note"]))
    return flow


def _section_flowables(
    section: ArtifactSection, facts: dict[str, CanonicalFact] | None, styles: dict, frame_width: float
) -> list:
    """One IR section as a run of flowables: heading, then body or table."""
    from reportlab.platypus import Paragraph, Spacer

    flow: list = [Paragraph(_escape(section.heading), styles["heading"])]
    if section.hidden:
        flow.append(Paragraph(_escape(_HIDDEN_NOTE), styles["hidden"]))

    # `purpose` is shown only when there is no prose to carry it — a finished
    # paragraph already says what the section is for; a table or an
    # awaiting-narrative placeholder does not, and that is where a reader
    # benefits from the one-line brief the outline wrote for the narrator.
    if section.purpose and section.body is None:
        flow.append(Paragraph(_escape(section.purpose), styles["purpose"]))

    if section.body:
        text = references.substitute(section.body, facts) if facts else section.body
        for block in (part.strip() for part in text.split("\n\n")):
            if block:
                flow.append(Paragraph(_escape(block), styles["body"]))
    elif section.table is not None:
        flow.append(_table_flowable(section.table, frame_width, styles))
        if section.table.note:
            flow.append(Paragraph(_escape(section.table.note), styles["note"]))
    else:
        flow.append(Paragraph(_escape(_AWAITING), styles["awaiting"]))

    # After the chain, never inside it. `render/docx.py` and `render/markdown.py`
    # both carry the same note: a `for` placed between the `elif` and the `else`
    # above binds the `else` to the loop rather than to the conditional, and
    # Python runs a loop-else whenever the loop did not break — which is how
    # that defect first shipped, in the Markdown renderer.
    for chart in section.charts:
        if section.table is not None:
            flow.extend(_figure_flowables(chart, section.table, frame_width, styles))

    flow.append(Spacer(1, 4))
    return flow


# ---------------------------------------------------------------------------
# Running heads and page numbering
# ---------------------------------------------------------------------------


def _header_drawer(text: str):  # type: ignore[no-untyped-def]
    """An ``onPage`` callback that writes the running header — the company and
    the document title, right-aligned in the top margin, same content as
    `render/docx.py::_running_heads`. Needs no total page count, unlike the
    footer, so it draws directly rather than through the buffering trick below.
    """

    def draw(canvas, doc) -> None:  # type: ignore[no-untyped-def]
        from reportlab.lib.colors import HexColor

        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(HexColor(f"#{_MUTED}"))
        canvas.drawRightString(_PAGE_WIDTH_PT - _MARGIN_PT, _PAGE_HEIGHT_PT - _MARGIN_PT + 8, text)
        canvas.restoreState()

    return draw


def _numbered_canvas_class(footer_note: str):  # type: ignore[no-untyped-def]
    """Build a `Canvas` subclass that captions every page ``Page X of Y``.

    The footer needs the total page count, and `Canvas.save()` writes pages as
    they are produced — the total is not known until the whole story has been
    laid out. This is the standard reportlab technique for that: buffer each
    page's finished drawing state instead of emitting it immediately, and once
    `save()` is called (so the total is known) replay every buffered page,
    drawing the footer on each before it is actually written. Nothing here
    reads the clock or a random source — it replays state this render already
    computed, plus one integer — so it is exactly as deterministic as every
    other page in the document.

    A class factory rather than a module-level class: the class subclasses
    `reportlab.pdfgen.canvas.Canvas`, and every reportlab name in this module is
    imported inside a function so an optional dependency for one format cannot
    break import of the package as a whole.
    """
    from reportlab.lib import colors
    from reportlab.pdfgen import canvas as canvas_module

    class _NumberedCanvas(canvas_module.Canvas):
        def __init__(self, *args, **kwargs) -> None:  # type: ignore[no-untyped-def]
            super().__init__(*args, **kwargs)
            self._worldloom_pages: list[dict] = []

        def showPage(self) -> None:
            self._worldloom_pages.append(dict(self.__dict__))
            self._startPage()

        def save(self) -> None:
            total = len(self._worldloom_pages)
            for state in self._worldloom_pages:
                self.__dict__.update(state)
                self._draw_footer(total)
                canvas_module.Canvas.showPage(self)
            canvas_module.Canvas.save(self)

        def _draw_footer(self, total: int) -> None:
            self.saveState()
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor(f"#{_MUTED}"))
            self.drawCentredString(
                _PAGE_WIDTH_PT / 2,
                _MARGIN_PT - 10,
                f"{footer_note}    Page {self._pageNumber} of {total}",
            )
            self.restoreState()

    return _NumberedCanvas


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------


def render(
    ir: ArtifactIR,
    facts: dict[str, CanonicalFact] | None = None,
    *,
    artifact_type: str = "",
    size_class: SizeClass = "medium",
) -> bytes:
    """Render one IR to PDF bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render
    time. Without it the references stay visible, which is the right failure —
    a document that quietly drops a figure reads as complete and is not.

    *artifact_type* and *size_class* feed the artifact compiler's page plan
    (see ``_plan``); both default to values that compose against every
    artifact type this renderer ships against, so a bare ``render(ir, facts)``
    — the shape `tests/test_docx.py`'s idiom uses — still works for a
    determinism check that does not care about composition.
    """
    _require_reportlab()
    from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph
    from reportlab.platypus.doctemplate import LayoutError

    plan = _plan(ir, artifact_type, size_class)
    styles = _styles()
    frame_width = plan.page_width_pt - 2 * plan.margin_pt

    story: list = [Paragraph(_escape(ir.title), styles["title"])]
    if ir.subtitle:
        story.append(Paragraph(_escape(ir.subtitle), styles["subtitle"]))

    author = ir.metadata.get("author")
    if author:
        byline = author
        if ir.metadata.get("author_title"):
            byline += f", {ir.metadata['author_title']}"
        story.append(Paragraph(_escape(byline), styles["byline"]))

    story.append(Paragraph(
        _escape(ir.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")),
        styles["notice"],
    ))

    for section in plan.sections:
        story.extend(_section_flowables(section, facts, styles, frame_width))

    if ir.metadata.get("voice"):
        story.append(Paragraph(
            _escape(f"Author voice: {ir.metadata['voice']}. Persona: {ir.metadata.get('persona', '')}."),
            styles["note"],
        ))

    buffer = BytesIO()
    doc = BaseDocTemplate(
        buffer,
        pagesize=(plan.page_width_pt, plan.page_height_pt),
        leftMargin=plan.margin_pt,
        rightMargin=plan.margin_pt,
        topMargin=plan.margin_pt,
        bottomMargin=plan.margin_pt,
        title=ir.title,
        author=ir.metadata.get("author") or "Worldloom",
        subject=ir.subtitle or "",
        creator="Worldloom",
        keywords=["synthetic", "worldloom", f"seed={ir.metadata.get('worldloom_seed', '')}"],
        # `invariant` is reportlab's own documented determinism switch — it
        # substitutes a fixed instant for `time.time()` everywhere the library
        # would otherwise reach for the clock, including the digest that seeds
        # `/ID`. `pageCompression=0` keeps every content stream as literal
        # bytes rather than deflated ones, which is what lets a figure be
        # verified by searching the file the same way a fact is checked
        # against the Markdown twin (see `tests/test_pdf.py`) — a diffable
        # native artifact, the same virtue `render/markdown.py` was written
        # for, at the cost of a larger file than a shipped PDF viewer would
        # produce.
        invariant=True,
        pageCompression=0,
    )
    frame = Frame(plan.margin_pt, plan.margin_pt, frame_width, plan.page_height_pt - 2 * plan.margin_pt, id="body")
    header_text = " · ".join(part for part in (ir.metadata.get("company"), ir.title) if part)
    footer_note = ir.metadata.get("note", "Synthetic corpus generated by Worldloom.")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_header_drawer(header_text))])

    try:
        doc.build(story, canvasmaker=_numbered_canvas_class(footer_note))
    except LayoutError as exc:
        # A single row taller than an empty page cannot be split further —
        # `Table.split()` has nothing left to try, and platypus raises rather
        # than silently clipping content. Turned into a `RenderError` naming
        # the artifact rather than left as reportlab's own exception, so a
        # caller sees which document failed and why instead of a bare layout
        # message with no artifact id in it.
        raise RenderError(
            f"{ir.id}: a table row does not fit on a single page even alone — "
            f"shorten its content or widen the page margins ({exc})"
        ) from exc

    return _normalise(buffer.getvalue())


def render_all(world: World) -> list[Rendered]:
    """Render every document-shaped artifact in *world* — the same set
    `render/docx.py` handles, since a native-PDF artifact and a Word artifact
    are the same document-shaped content, just spelled in two fixed-page
    formats. Reused from there rather than duplicated, so the two lists cannot
    quietly drift apart.
    """
    facts = {fact.id: fact for fact in world.facts}
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type not in HANDLES:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.pdf",
                media_type=MEDIA_TYPE,
                payload=render(
                    ir, facts, artifact_type=intent.artifact_type, size_class=intent.size_profile
                ),
            )
        )
    return out
