"""The PPTX renderer.

A board deck is where the executive summary this project already emits
actually gets consumed — nobody hands a CFO a Markdown file. Per
``docs/artifact-compiler.md`` sections 9.1 and 14.A, this is the vertical
slice: one artifact type, the pipeline that document describes end to end, and
nothing wider.

::

    ArtifactIR -> PresentationPlan -> slide components -> geometry solve
    -> python-pptx -> OOXML normalisation -> structural validation

Same rule as every other renderer in this package: this reads the IR and
nothing else. The compiler (``worldloom.compiler``) turns the IR into a
validated sequence of component ids — the same deterministic, grammar-checked
composition any format in this repo could reach for — and this module's only
job is to spell that sequence as shapes. Nothing here computes a number,
resolves a fact, or decides which rows belong in a table; every value that
lands on a slide is either prose the narrative compiler already validated
(with ``{{fact:ID}}`` substituted the same way ``docx`` and ``markdown`` do)
or a cell that was already sitting in a resolved ``Table``.

``PresentationPlan``, ``SlidePlan`` and ``Box`` are renderer-local. Per
``docs/artifact-compiler.md`` section 2, a format plan is a rendering concern
— it is rebuilt from the IR every time a deck is wanted and is never
persisted, so it cannot drift from the artifact it describes the way a second
hand-kept structure could. None of the three belongs in ``models.py``.

Geometry is explicit ``Box(x, y, cx, cy)`` arithmetic against a handful of
module constants, not a constraint solver. Per section 14.E, CP-SAT and a
Cassowary solver are justified only once greedy layout fails a recorded
fixture — this renderer has one artifact type and at most a handful of shapes
per slide, and reaching for a solver here would be solving a problem that
does not exist yet.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from ..compiler.compose import compose, plan_from_ir
from ..compiler.style import StyleGenome, genome
from ..locales import DEFAULT as DEFAULT_LOCALE
from ..locales import Locale
from ..models import ArtifactIR, CanonicalFact, Chart, ChartKind, Row, Table
from ..narrative import references
from ..presentation import DEFAULT as DEFAULT_PRESENTATION
from ..presentation import Presentation as PresentationProfile
from ..presentation import of as presentation_of
from ..rng import Rng
from . import Rendered, RenderError, fonts, ooxml, slug_for
from .values import corpus_locale, format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World

MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.presentationml.presentation"

#: Artifact types this renderer spells. Per 14.A the vertical slice targets one
#: artifact — the executive summary the retail-close episode already emits —
#: rather than the wider ``HANDLES`` set `docx.py` covers. Widening this is
#: 14.B work (component registry extraction, more layout families), not this
#: slice's job.
HANDLES = frozenset({"executive_summary"})

#: Same wording DOCX and Markdown use for a section still awaiting prose. One
#: string, so a reader comparing all three formats of an unfinished corpus sees
#: one message rather than three renderers each describing the gap differently.
_AWAITING = (
    "Awaiting narrative. Structure and supporting facts are resolved; "
    "prose is generated by the constrained compiler."
)

_HIDDEN_NOTE = "Not part of the readable surface."


def _require_pptx():  # type: ignore[no-untyped-def]
    try:
        import pptx
    except ImportError as exc:  # pragma: no cover - depends on install extras
        raise RenderError(
            "the pptx format needs python-pptx. Install it with: pip install 'worldloom[pptx]'"
        ) from exc
    return pptx


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------

_EMU_PER_INCH = 914_400


def _in(inches: float) -> int:
    """Inches to EMU, the unit every OOXML coordinate is stored in.

    A plain function rather than reaching for ``pptx.util.Inches`` — the
    geometry constants below are computed at import time, before
    ``_require_pptx`` has run, so they cannot depend on the optional package.
    ``Emu``/``Inches`` are themselves just ``int`` subclasses; python-pptx
    accepts a bare EMU int anywhere it accepts a ``Length``.
    """
    return round(inches * _EMU_PER_INCH)


#: Widescreen, because every deck this renders is a 2020s corporate one, not a
#: 2003-era projector. 13.333 x 7.5in is PowerPoint's own 16:9 default size.
SLIDE_W = _in(13.333)
SLIDE_H = _in(7.5)

#: Outer margin and the gap between stacked regions. Not copied from `docx.py`
#: verbatim — its 22mm page margin (~0.87in) is tuned for an A4 page held
#: close; a slide is wider and shorter, and the same margin there would eat a
#: third of the usable width. Tighter, so the two formats read as
#: proportionate rather than as one renderer ignoring the other's convention.
_MARGIN = _in(0.55)
_GUTTER = _in(0.25)

#: The coloured band carrying a slide's heading, and the footer strip below the
#: body. Both span the full slide width (no side margin) — a full-bleed band
#: is what makes a slide read as "a deck" rather than "a page with a border".
_HEADER_H = _in(0.85)
_FOOTER_H = _in(0.35)

_CONTENT_X = _MARGIN
_CONTENT_W = SLIDE_W - 2 * _MARGIN

_BODY_Y = _HEADER_H + _GUTTER
_FOOTER_Y = SLIDE_H - _FOOTER_H
_BODY_H = _FOOTER_Y - _GUTTER - _BODY_Y


@dataclass(frozen=True)
class Box:
    """One rectangle in EMU. The only geometry primitive this renderer has.

    Nothing below ever searches for a box — every ``Box`` is either a module
    constant or arithmetic over one (see ``_stack`` and ``_columns``), which is
    what "deterministic greedy layout" concretely means here: the same IR
    produces the same boxes because there is no search, only addition.
    """

    x: int
    y: int
    cx: int
    cy: int

    @property
    def right(self) -> int:
        return self.x + self.cx

    @property
    def bottom(self) -> int:
        return self.y + self.cy


#: The three horizontal bands every slide is built from, fixed for the whole
#: deck. A slide-specific layout only ever subdivides ``BODY``; ``HEADER`` and
#: ``FOOTER`` are the same rectangle on every slide, which is what stops a
#: one-off slide from silently drifting the deck's furniture out from under
#: the rest.
HEADER = Box(0, 0, SLIDE_W, _HEADER_H)
BODY = Box(_CONTENT_X, _BODY_Y, _CONTENT_W, _BODY_H)
FOOTER = Box(0, _FOOTER_Y, SLIDE_W, _FOOTER_H)


def _assert_in_bounds(box: Box) -> None:
    """A shape that starts life out of bounds is a bug in this renderer's own
    arithmetic, not something the structural validator downstream should have
    to be the first to catch."""
    assert box.x >= 0 and box.y >= 0, box
    assert box.right <= SLIDE_W and box.bottom <= SLIDE_H, box


def _stack(x: int, top: int, width: int, heights: list[int], gap: int = _GUTTER) -> list[Box]:
    """*heights* laid out downward from *top*, each separated by *gap*.

    The one layout combinator this renderer needs: every multi-element slide
    (the cover, a prose slide with an accent bar) is boxes stacked or set side
    by side, never positioned by hand — which is what makes non-overlap a
    property of the arithmetic rather than something checked after the fact,
    box by box.
    """
    boxes = []
    y = top
    for h in heights:
        boxes.append(Box(x, y, width, h))
        y += h + gap
    return boxes


def _columns(box: Box, count: int, gap: int = _GUTTER) -> list[Box]:
    """*box* split into *count* equal-width columns side by side."""
    width = (box.cx - gap * (count - 1)) // count
    return [Box(box.x + i * (width + gap), box.y, width, box.cy) for i in range(count)]


# ---------------------------------------------------------------------------
# The plan
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SlidePlan:
    """One slide's resolved content, already assigned a component family.

    Renderer-local and rebuilt on every render — see the module docstring.
    ``kind`` picks the slide's furniture (a cover has no header band, a
    divider has no footer table); ``component_id`` is the compiler's choice of
    family for content slides, and it only ever selects a *visual treatment*.
    What actually appears is always ``body`` or ``table`` off the IR section
    this plan came from — never something the component id invents.
    """

    kind: str  # "cover" | "divider" | "content" | "closing"
    component_id: str
    heading: str
    body: str | None = None
    table: Table | None = None
    hidden: bool = False
    charts: tuple[Chart, ...] = ()
    """Charts declared over `table` — a view of it, never a source of data of
    its own (see `Chart`'s own docstring). Drawn onto their own slide(s) after
    whatever `table`/`body` produces, by `_draw_content`."""


@dataclass(frozen=True)
class PresentationPlan:
    """The whole deck, before a single shape exists."""

    title: str
    subtitle: str | None
    metadata: dict[str, str]
    slides: tuple[SlidePlan, ...]


#: The size class and density profile handed to the compiler. Not read off the
#: originating ``ArtifactIntent`` — ``render(ir, facts)`` carries the same
#: signature as every other format here and the IR itself does not carry a
#: size class, so threading the intent through would widen this module's
#: surface for a value that is already implied: every ``executive_summary`` in
#: `generators/planning.py` is planned as ``"small"``, because it is an
#: executive committee's one-pager, not a workbook. If a future
#: ``executive_summary`` ever grows past the four beats that implies,
#: ``compose`` raises rather than silently overflowing a slide — see `_plan`.
_SIZE_CLASS = "small"
_DENSITY_PROFILE = "balanced"


def _plan(ir: ArtifactIR,
          profile: PresentationProfile = DEFAULT_PRESENTATION) -> PresentationPlan:
    """``ArtifactIR`` -> ``PresentationPlan``, by way of the compiler.

    ``compose`` decides which component family presents each section and
    checks the resulting sequence reads as a document a company would issue
    (``docs/artifact-compiler.md`` section 4). This function's only job is to
    turn that validated sequence into slides, adding the structural slides —
    cover, appendix divider, closing — that the compiler has no opinion about
    because they carry no beat of the argument.
    """
    plan = plan_from_ir(
        ir,
        artifact_type="executive_summary",
        size_class=_SIZE_CLASS,
        density_profile=_DENSITY_PROFILE,
    )
    composition = compose(plan, fmt="pptx")
    if not composition.ok:
        raise RenderError(
            f"{ir.id}: component sequence is not a grammatical executive_summary: "
            + "; ".join(str(v) for v in composition.violations)
        )

    # `plan.beats` and `ir.sections` are built 1:1, in order, by `plan_from_ir`
    # — one beat per section, nothing filtered before `compose` runs — so
    # zipping them is the correct way back to the section a beat came from,
    # without re-deriving the beat-key slug `compose` computes internally.
    section_by_beat = {beat.key: section for beat, section in zip(plan.beats, ir.sections)}

    slides: list[SlidePlan] = [SlidePlan(kind="cover", component_id="cover", heading=ir.title)]
    appendix_opened = False
    for component_id, beat_key in zip(composition.components, composition.beats):
        section = section_by_beat[beat_key]
        if section.hidden and profile.appendix != "append":
            # Dropped before the divider is considered, so a deck whose only
            # hidden sections are omitted does not open an appendix and then
            # put nothing in it — three slides of the shipped executive
            # summary were the divider, the fact tables and the persona.
            continue
        if section.hidden and not appendix_opened:
            # One divider, however many hidden sections fall inside the
            # appendix — not one per section, which would read as the deck
            # repeatedly announcing the same change of subject.
            slides.append(
                SlidePlan(kind="divider", component_id="core.section_divider", heading="Appendix")
            )
            appendix_opened = True
        slides.append(
            SlidePlan(
                kind="content",
                component_id=component_id,
                heading=section.heading,
                body=section.body,
                table=section.table,
                hidden=section.hidden,
                charts=tuple(section.charts),
            )
        )
    if profile.provenance == "footer":
        # The closing slide carries nothing but the author voice, so under
        # any other provenance it is a blank slide with a heading. Dropped
        # rather than emptied: a deck ending on an empty 'Closing' is worse
        # than one that simply ends.
        slides.append(SlidePlan(kind="closing", component_id="closing", heading="Closing"))

    return PresentationPlan(title=ir.title, subtitle=ir.subtitle, metadata=ir.metadata, slides=tuple(slides))


# ---------------------------------------------------------------------------
# Style
# ---------------------------------------------------------------------------

#: The palette `genome(rng, archetype="house")` reproduces exactly — the pptx
#: analogue of `docx.py`'s own `_HEADER_FILL`/`_SUBTOTAL_FILL` pair. Kept as
#: the fixed reference point the sampling space is built around and as the
#: source of `_HOUSE_GENOME` below; the renderer itself now reads every
#: colour off that document's own world-seeded genome instead.
_HEADER_FILL = "2F4858"
_ACCENT_FILL = "EDF2F4"
_NEGATIVE = "9B2226"
_INK = "1B1F22"
_MUTED = "6B747B"
_SUBTITLE_INK = "4A555C"
_WHITE = "FFFFFF"

#: No text on any slide goes below this. PowerPoint's own accessibility
#: checker starts flagging body copy under 18pt for a *projected* deck, but
#: nothing this renderer produces is meant to be read from the back of a room
#: — it is read on a screen, the same way the DOCX and Markdown twins of the
#: same artifact are. 12pt is the floor below which even screen reading starts
#: to strain, and it is deliberately not lower than the smallest text DOCX
#: itself ever uses (`docx.py`'s footnote and table text sit at 8-9pt, but
#: that is on an A4 page held close, which a slide viewed at arm's length is
#: not).
MIN_FONT_PT = 12


def _rgb(hexcode: str):  # type: ignore[no-untyped-def]
    from pptx.dml.color import RGBColor

    return RGBColor.from_string(hexcode)


def _pt(size: int):  # type: ignore[no-untyped-def]
    from pptx.util import Pt

    assert size >= MIN_FONT_PT, f"{size}pt would sit below the {MIN_FONT_PT}pt floor — see MIN_FONT_PT"
    return Pt(size)


# ---------------------------------------------------------------------------
# The style genome
# ---------------------------------------------------------------------------

#: `type_scale` band indices — see `compiler/style.py::_TYPE_BANDS`. Named so
#: call sites read `_clamped_pt(g.type_scale[_TS_HEADING])` rather than an
#: unlabelled tuple index — the same convention `docx.py` uses for the same
#: five bands.
_TS_TITLE, _TS_HEADING, _TS_SUBHEADING, _TS_BODY, _TS_CAPTION = range(5)

#: `spacing_scale` band indices — see `compiler/style.py::_SPACING_BANDS`.
_SP_HEADING, _SP_SUBHEADING, _SP_PARAGRAPH, _SP_CELL = range(4)

#: See `docx.py`'s identical constant: `table_density` scales the tightest
#: spacing band a second time, since density and the sampled scale are
#: independent knobs in `style.py`.
_DENSITY_FACTOR: dict[str, float] = {"airy": 1.4, "normal": 1.0, "tight": 0.65}

#: Fallback genome for the handful of draw functions this module exposes
#: without a leading underscore or that `tests/test_pptx.py` reaches directly,
#: rather than through `render()` — `draw_metric_cards`, `_draw_prose_content`,
#: `_draw_table_content`, `_draw_divider`, `_draw_cover` are all exercised
#: that way, on shapes built with no `ArtifactIR` (and so no world seed) in
#: hand at all. `archetype="house"` pins the colour and structural fields
#: regardless of which seed derives it (see `style.genome`'s own docstring —
#: only `type_scale`/`spacing_scale`/`rule_weight`/`whitespace_bias` vary by
#: seed under `"house"`), so a caller that supplies no genome of its own gets
#: exactly the look this renderer has always had, not an arbitrary sampled
#: one; seed 0 is as good as any seed for a fallback that isn't tied to a
#: real world.
_HOUSE_GENOME = genome(Rng(0).derive("style"), archetype="house")


def _genome_for(ir: ArtifactIR) -> StyleGenome:
    """This artifact's world-derived style genome — see `docx.py::_genome_for`
    for the full reasoning; both renderers derive it identically so the deck
    and the memo for one world always agree on how it looks.

        from ..compiler.style import genome
        from ..rng import Rng
        g = genome(Rng(world.seed).derive("style"))
    """
    raw = ir.metadata.get("style_seed") or ir.metadata.get("worldloom_seed")
    seed = int(raw) if raw and raw != "None" else 0
    return genome(Rng(seed).derive("style"))


def _clamped_pt(value: float) -> int:
    """A genome's `type_scale` can legitimately sample below `MIN_FONT_PT` —
    its body band is 10-11pt, comfortably readable on the A4 page `docx.py`
    prints, but this renderer's floor exists for a different reason (a slide
    read at arm's length, not held close — see `MIN_FONT_PT`'s own
    docstring). The floor is the invariant a rendered deck must never
    violate, so it wins over the sampled value here rather than the other way
    around: a genome that asked for 10pt body copy gets 12pt on a slide,
    every time, and every genome-derived size in this module is required to
    pass through here before it reaches `_pt`/`_write`/`_style_cell`.
    """
    return max(MIN_FONT_PT, round(value))


def _space_pt(g: StyleGenome, band: int) -> float:
    """One `spacing_scale` band in points, anchored to this genome's own body
    type size — see `docx.py::_space_pt`, the same reasoning applies here."""
    return g.spacing_scale[band] * g.type_scale[_TS_BODY]


def _cell_padding_pt(g: StyleGenome) -> float:
    """Table cell padding: the tightest spacing band, scaled again by
    `table_density` — see `docx.py::_cell_padding_pt`."""
    return _space_pt(g, _SP_CELL) * _DENSITY_FACTOR[g.table_density]


def _negative_text(value: float, text: str, convention: str) -> str:
    """Return *text* unchanged. The genome's `number_negatives` is deliberately
    not applied here.

    It was, briefly, and `tests/test_docx.py` caught it: a table rendered
    `-10,200` in Word while the same table rendered `(10,200)` in Markdown, and
    `render/values.py` exists precisely so that cannot happen — "one function,
    so there is one answer". A per-renderer override of how a number is spelled
    reintroduces the divergence that module was written to eliminate, and it
    does so invisibly, because each format is internally consistent.

    Varying the convention is still legitimate diversity; it just has to be a
    corpus-wide decision applied in one place. That place now exists and it is
    not here: `locales.Locale.negative` is decided once for the corpus, recorded
    on the recipe, resolved once per render pass by `values.corpus_locale`, and
    spelled by `format_value` — so a locale whose negatives are signed prints
    `-1.234` in Word *and* in Markdown *and* in the BM25 index, which is the
    property this function refuses to break. A genome that varied the convention
    per document would still be a second answer to a question the corpus has
    already answered, so `number_negatives` stays unapplied.

    Kept as a function rather than deleted at the call sites so the reason
    survives next to the temptation.
    """
    del convention
    return text
def _textbox(slide, box: Box, *, fill: str | None = None):  # type: ignore[no-untyped-def]
    """A text box at *box*, transparent unless *fill* is given.

    Every text-bearing shape in this module goes through here, which is what
    keeps word-wrap, margins, and the no-autofit choice below uniform instead
    of each ``_draw_*`` function reimplementing them slightly differently.
    """
    from pptx.enum.text import MSO_AUTO_SIZE

    _assert_in_bounds(box)
    shape = slide.shapes.add_textbox(box.x, box.y, box.cx, box.cy)
    frame = shape.text_frame
    frame.word_wrap = True
    # Not the default. `SHAPE_TO_FIT_TEXT` is a hint for the *next* editor to
    # resize the shape around its text — left on, a box we sized deliberately
    # could grow past the bounds this module computed the moment someone
    # opens and re-saves the deck. This renderer owns the geometry; nothing
    # downstream should get to override it.
    frame.auto_size = MSO_AUTO_SIZE.NONE
    frame.margin_left = frame.margin_right = _in(0.12)
    frame.margin_top = frame.margin_bottom = _in(0.06)
    if fill is not None:
        shape.fill.solid()
        shape.fill.fore_color.rgb = _rgb(fill)
        shape.line.fill.background()
    else:
        shape.fill.background()
        shape.line.fill.background()
    return shape


def _write(
    frame,  # type: ignore[no-untyped-def]
    paragraphs: list[str],
    *,
    size: float,
    colour: str,
    bold: bool = False,
    italic: bool = False,
    align=None,  # type: ignore[no-untyped-def]
    space_after_pt: float | None = None,
    face: str | None = None,
) -> None:
    """Fill a text frame with one paragraph per string, uniformly styled.

    Every run gets an explicit size and colour rather than inheriting the
    theme default — inheritance is exactly what would let a run slip under
    ``MIN_FONT_PT`` unnoticed, since nothing would ever assign it a size to
    check.

    *space_after_pt* — a genome's `spacing_scale` reaching this module — only
    ever changes room *between* paragraphs inside one already-fixed textbox;
    it cannot move a shape's own box (`_assert_in_bounds`'s rectangle is set
    before any text goes in), so it is free to vary by genome without risking
    this renderer's non-overlap guarantee the way changing `_GUTTER` or
    `_MARGIN` themselves would.
    """
    from pptx.util import Pt

    first = True
    for text in paragraphs:
        if not text:
            continue
        paragraph = frame.paragraphs[0] if first else frame.add_paragraph()
        first = False
        paragraph.text = text
        if align is not None:
            paragraph.alignment = align
        if space_after_pt is not None:
            paragraph.space_after = Pt(space_after_pt)
        run = paragraph.runs[0]
        run.font.size = _pt(size)
        run.font.bold = bold
        run.font.italic = italic
        run.font.color.rgb = _rgb(colour)
        # The genome's typeface, resolved by the caller to this run's role
        # (display for titles and bands, body for everything else). `None` —
        # the house family in the theme-bearing formats — sets no name, which
        # is the theme default a house deck always had.
        if face:
            run.font.name = face


def _new_slide(prs, heading: str, *, footer_text: str, g: StyleGenome = _HOUSE_GENOME):  # type: ignore[no-untyped-def]
    """A blank slide with the two bands every content slide shares."""
    from pptx.enum.text import MSO_ANCHOR, PP_ALIGN

    slide = prs.slides.add_slide(prs.slide_layouts[6])  # "Blank" — see module docstring

    header = _textbox(slide, HEADER, fill=g.colour_roles["header_fill"])
    header.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    heading_align = PP_ALIGN.LEFT if g.title_alignment == "left" else PP_ALIGN.CENTER
    _write(
        header.text_frame, [heading], size=_clamped_pt(g.type_scale[_TS_HEADING]),
        colour=g.colour_roles["header_text"], bold=True, align=heading_align,
        face=fonts.named(g.typeface).display,
    )

    footer = _textbox(slide, FOOTER)
    footer.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    _write(footer.text_frame, [footer_text], size=MIN_FONT_PT, colour=_MUTED, italic=True, align=PP_ALIGN.CENTER)

    return slide


# ---------------------------------------------------------------------------
# Slide components
# ---------------------------------------------------------------------------


def _draw_cover(prs, plan: PresentationPlan, g: StyleGenome = _HOUSE_GENOME) -> None:  # type: ignore[no-untyped-def]
    """The title slide. Structural, like `docx.py`'s ``_cover`` — not a
    compiler component, because it carries no beat of the argument."""
    from pptx.enum.text import PP_ALIGN

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    title_box, subtitle_box, byline_box = _stack(
        _CONTENT_X, _in(2.4), _CONTENT_W, [_in(1.1), _in(0.6), _in(0.5)]
    )

    title = _textbox(slide, title_box)
    _write(
        title.text_frame, [plan.title], size=_clamped_pt(g.type_scale[_TS_TITLE]),
        colour=g.colour_roles["body_text"], bold=True, align=PP_ALIGN.CENTER,
        face=fonts.named(g.typeface).display,
    )

    if plan.subtitle:
        subtitle = _textbox(slide, subtitle_box)
        _write(
            subtitle.text_frame, [plan.subtitle], size=_clamped_pt(g.type_scale[_TS_SUBHEADING]),
            colour=_SUBTITLE_INK, italic=True, align=PP_ALIGN.CENTER,
        )

    author = plan.metadata.get("author")
    if author:
        author_title = plan.metadata.get("author_title")
        byline_text = f"{author}, {author_title}" if author_title else author
        byline = _textbox(slide, byline_box)
        _write(
            byline.text_frame, [byline_text], size=_clamped_pt(g.type_scale[_TS_BODY]),
            colour=g.colour_roles["body_text"], bold=True, align=PP_ALIGN.CENTER,
        )

    company = plan.metadata.get("company", "")
    note = plan.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")
    note_box = Box(_CONTENT_X, SLIDE_H - _MARGIN - _in(0.4), _CONTENT_W, _in(0.4))
    note_shape = _textbox(slide, note_box)
    _write(
        note_shape.text_frame,
        [f"{company} · {note}" if company else note],
        size=MIN_FONT_PT, colour=_MUTED, italic=True, align=PP_ALIGN.CENTER,
    )


def _draw_divider(prs, heading: str, g: StyleGenome = _HOUSE_GENOME) -> None:  # type: ignore[no-untyped-def]
    """A section-divider slide — ``core.section_divider``.

    Used once, ahead of the appendix, to mark the change of subject the same
    way `docx.py` marks a hidden section: present, but flagged as not part of
    the readable surface.
    """
    from pptx.enum.text import MSO_ANCHOR, PP_ALIGN

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    band_box = Box(0, _in(2.6), SLIDE_W, _in(1.3))
    band = _textbox(slide, band_box, fill=g.colour_roles["header_fill"])
    band.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    _write(
        band.text_frame, [heading], size=_clamped_pt(g.type_scale[_TS_TITLE]),
        colour=g.colour_roles["header_text"], bold=True, align=PP_ALIGN.CENTER,
        face=fonts.named(g.typeface).display,
    )

    note_box = Box(_CONTENT_X, band_box.bottom + _GUTTER, _CONTENT_W, _in(0.5))
    note = _textbox(slide, note_box)
    _write(
        note.text_frame, [_HIDDEN_NOTE], size=_clamped_pt(g.type_scale[_TS_SUBHEADING]),
        colour=_MUTED, italic=True, align=PP_ALIGN.CENTER,
    )


def _draw_closing(prs, plan: PresentationPlan, g: StyleGenome = _HOUSE_GENOME) -> None:  # type: ignore[no-untyped-def]
    """The closing slide. Carries the same author-voice line `docx.py`'s
    closing paragraph does, off the same metadata — not a new statement."""
    footer_text = f"{plan.metadata.get('company', '')} · {plan.title}"
    slide = _new_slide(prs, "Closing", footer_text=footer_text, g=g)
    voice = plan.metadata.get("voice", "")
    persona = plan.metadata.get("persona", "")
    body = _textbox(slide, BODY)
    _write(
        body.text_frame, [f"Author voice: {voice}. Persona: {persona}."],
        size=_clamped_pt(g.type_scale[_TS_BODY]), colour=_MUTED, italic=True,
    )


#: Per-component visual treatment for a prose slide, keyed by `type_scale`
#: band rather than a literal pt size — see `_TS_HEADING` etc. ``accent``
#: draws a narrow coloured bar down the left of the body box — a cheap,
#: cheap-to-verify way to give ``core.schedule`` and ``mgmt.decision_panel``
#: a distinct silhouette from a plain narrative slide without inventing
#: content neither carries.
_PROSE_STYLE: dict[str, dict] = {
    "core.position": {"band": _TS_HEADING, "bold": True},
    "core.executive_summary": {"band": _TS_SUBHEADING},
    "core.schedule": {"band": _TS_SUBHEADING, "accent": True},
    "mgmt.decision_panel": {"band": _TS_SUBHEADING, "accent": True},
}
_DEFAULT_PROSE_STYLE = {"band": _TS_BODY}


def _draw_prose_content(prs, slide_plan, facts, footer_text: str,
                        g: StyleGenome = _HOUSE_GENOME,
                        locale: Locale = DEFAULT_LOCALE,
                        profile: PresentationProfile = DEFAULT_PRESENTATION) -> None:  # type: ignore[no-untyped-def]
    """A section whose content is prose — ``core.position``, ``core.narrative``
    and the rest of the text-shaped components in the registry."""
    slide = _new_slide(prs, slide_plan.heading, footer_text=footer_text, g=g)
    resolved = (references.substitute(slide_plan.body, facts, locale=locale,
                                     presentation=profile)
                if facts else slide_plan.body)
    # Blank lines are paragraph breaks — the same convention `docx.py` follows
    # for the identical reason: a single run holding newlines renders as one
    # unbroken block, not separate paragraphs.
    paragraphs = [block.strip() for block in resolved.split("\n\n") if block.strip()]

    style = _PROSE_STYLE.get(slide_plan.component_id, _DEFAULT_PROSE_STYLE)
    box = BODY
    if style.get("accent"):
        bar_w = _in(0.08)
        _textbox(slide, Box(BODY.x, BODY.y, bar_w, BODY.cy), fill=g.colour_roles["accent"])
        box = Box(BODY.x + bar_w + _GUTTER, BODY.y, BODY.cx - bar_w - _GUTTER, BODY.cy)

    text = _textbox(slide, box)
    _write(
        text.text_frame, paragraphs, size=_clamped_pt(g.type_scale[style["band"]]),
        colour=g.colour_roles["body_text"], bold=style.get("bold", False),
        space_after_pt=_space_pt(g, _SP_PARAGRAPH),
        face=fonts.named(g.typeface).body,
    )


#: Row budget per table slide. Not derived from `ComponentSpec.max_rows` —
#: those bands constrain which *component* the compiler assigns a beat, not
#: how many rows fit one physical slide of this renderer's own geometry, and
#: the two questions have different answers (`finance.variance_table` has no
#: declared cap at all, because a workbook table has no fixed canvas — a slide
#: always does). ``BODY`` is 5.8in tall; a header row plus 6 data rows leaves
#: ~0.83in per row, comfortably above one wrapped line at the 12pt floor even
#: for the longest cell text this renderer has seen (~50 characters).
_MAX_TABLE_ROWS_PER_SLIDE = 6


def _column_widths(table: Table, total: int, locale: Locale = DEFAULT_LOCALE) -> list[int]:
    """Column widths proportional to their content, not divided evenly.

    A table whose "statement" column carries a sentence and whose "authority"
    column carries one word looks unreadable split into equal fifths. Each
    column is weighted by the longest text it actually holds (header label
    included) — a property of the resolved data, not a guess about it, and the
    same ``format_value`` every other renderer uses, so the measured width
    agrees with what actually gets drawn into the cell.

    Rounds every column but the last, then gives the last the exact remainder
    — the sum has to equal *total* precisely, or the table's own shape would
    drift out of the bounds this renderer computed for it.
    """
    label_width = max((len(row.label) for row in table.rows), default=6)
    weights = [max(label_width, 6)]
    for column in table.columns:
        longest = len(column.label)
        for row in table.rows:
            cell = row.cells.get(column.key)
            if cell is not None:
                longest = max(longest, len(format_value(cell.value, column.number_format, locale=locale)))
        weights.append(max(longest, 6))

    share = sum(weights)
    widths = [round(total * weight / share) for weight in weights[:-1]]
    widths.append(total - sum(widths))
    return widths


def _apply_cell_borders(cell, policy: str, weight_pt: float) -> None:  # type: ignore[no-untyped-def]
    """Draw one table cell's own edges per the genome's `gridline_policy` —
    the pptx analogue of `docx.py::_apply_table_borders`, done per cell
    because python-pptx's own table-cell schema has no table-wide equivalent
    of Word's ``tblBorders`` (`CT_TableCellProperties` models fill and
    margins but no ``lnL``/``lnR``/``lnT``/``lnB``), so the border elements
    are built directly.

    Must run before `cell.fill.solid()` (only ever called from `_style_cell`,
    which does exactly that) — DrawingML's own schema requires the four
    ``ln*`` border elements to precede the fill choice group in document
    order, and python-pptx has no insertion helper for a pair of elements it
    never modeled.
    """
    from lxml import etree
    from pptx.oxml.ns import qn

    edges = {"all": ("lnL", "lnR", "lnT", "lnB"), "horizontal": ("lnT", "lnB"), "none": ()}[policy]
    # EMU, not eighths of a point (DrawingML's own line-width unit) — floored
    # at a quarter point for the same reason `docx.py`'s own `sz` is: the
    # lightest sampled `rule_weight` (0.25) should still draw a visible
    # hairline rather than rounding away to nothing.
    width = max(3175, round(weight_pt * 12700))
    tc_pr = cell._tc.get_or_add_tcPr()
    for tag in ("lnL", "lnR", "lnT", "lnB"):
        element = etree.SubElement(tc_pr, qn(f"a:{tag}"))
        element.set("w", str(width))
        element.set("cap", "flat")
        if tag in edges:
            fill = etree.SubElement(element, qn("a:solidFill"))
            colour = etree.SubElement(fill, qn("a:srgbClr"))
            colour.set("val", "808080")
        else:
            etree.SubElement(element, qn("a:noFill"))


def _apply_table_density(table, pad_pt: float) -> None:  # type: ignore[no-untyped-def]
    """Table-wide cell padding — `table_density`'s render-time effect,
    mirroring `docx.py::_apply_cell_padding`. Left/right stay python-pptx's
    own default; only the vertical axis a genome's "airy" vs "tight" table
    actually changes moves."""
    from pptx.util import Pt

    pad = Pt(pad_pt)
    for cell in table.iter_cells():
        cell.margin_top = pad
        cell.margin_bottom = pad


def _style_cell(
    cell, *, size: int, colour: str, bold: bool = False, fill: str | None = None, align=None,  # type: ignore[no-untyped-def]
    borders: tuple[str, float] | None = None,
) -> None:
    if borders is not None:
        _apply_cell_borders(cell, *borders)
    if fill is not None:
        cell.fill.solid()
        cell.fill.fore_color.rgb = _rgb(fill)
    frame = cell.text_frame
    frame.word_wrap = True
    for paragraph in frame.paragraphs:
        if align is not None:
            paragraph.alignment = align
        for run in paragraph.runs:
            run.font.size = _pt(size)
            run.font.bold = bold
            run.font.color.rgb = _rgb(colour)


def _draw_table(slide, table: Table, rows: list[Row], *, note: str | None, g: StyleGenome = _HOUSE_GENOME, locale: Locale = DEFAULT_LOCALE) -> None:  # type: ignore[no-untyped-def]
    """One table, or one page of a paginated one, as a native PPTX table.

    Mirrors `docx.py`'s ``_table``: a label column then one column per
    measure, right-aligned numbers, subtotal rows shaded, negatives marked
    twice over (parenthesised or minus-signed by `number_negatives` and
    coloured) so the sign survives a black-and-white printout of a slide as
    readily as a page.
    """
    from pptx.enum.text import PP_ALIGN

    box = BODY
    note_box = None
    if note:
        note_h = _in(0.45)
        box = Box(BODY.x, BODY.y, BODY.cx, BODY.cy - note_h - _GUTTER)
        note_box = Box(BODY.x, box.bottom + _GUTTER, BODY.cx, note_h)
    _assert_in_bounds(box)

    graphic = slide.shapes.add_table(len(rows) + 1, len(table.columns) + 1, box.x, box.y, box.cx, box.cy)
    grid = graphic.table
    for column, width in zip(grid.columns, _column_widths(table, box.cx, locale)):
        column.width = width
    _apply_table_density(grid, _cell_padding_pt(g))
    borders = (g.gridline_policy, g.rule_weight)

    body_size = _clamped_pt(g.type_scale[_TS_BODY])
    header_size = _clamped_pt(g.type_scale[_TS_SUBHEADING])

    header_cells = grid.rows[0].cells
    header_cells[0].text = table.title
    for index, column in enumerate(table.columns, start=1):
        header_cells[index].text = column.label
    for index, cell in enumerate(header_cells):
        _style_cell(
            cell, size=header_size, colour=g.colour_roles["header_text"], bold=True,
            fill=g.colour_roles["header_fill"], align=PP_ALIGN.LEFT if index == 0 else PP_ALIGN.RIGHT,
            borders=borders,
        )

    for row_index, row in enumerate(rows, start=1):
        cells = grid.rows[row_index].cells
        cells[0].text = row.label
        # A subtotal row's own text colour always wins over the
        # negative-figure colour — see `docx.py::_table`'s identical
        # reasoning: `subtotal_text` is the only colour `style.py` ever
        # proves legible against `subtotal_fill`.
        row_colour = g.colour_roles["subtotal_text"] if row.emphasis else g.colour_roles["body_text"]
        _style_cell(cells[0], size=body_size, colour=row_colour, bold=row.emphasis, borders=borders)
        for column_index, column in enumerate(table.columns, start=1):
            cell = row.cells.get(column.key)
            value = cell.value if cell else None
            negative = isinstance(value, (int, float)) and value < 0
            text = format_value(value, column.number_format, locale=locale) if cell else ""
            if negative:
                text = _negative_text(value, text, g.number_negatives)
            cells[column_index].text = text
            cell_colour = g.colour_roles["negative_text"] if negative and not row.emphasis else row_colour
            _style_cell(
                cells[column_index], size=body_size, colour=cell_colour, bold=row.emphasis,
                align=PP_ALIGN.RIGHT, borders=borders,
            )
        if row.emphasis:
            for cell in cells:
                cell.fill.solid()
                cell.fill.fore_color.rgb = _rgb(g.colour_roles["subtotal_fill"])

    if note_box is not None:
        note_shape = _textbox(slide, note_box)
        _write(note_shape.text_frame, [note], size=MIN_FONT_PT, colour=_MUTED, italic=True)


def draw_metric_cards(slide, table: Table, g: StyleGenome = _HOUSE_GENOME, locale: Locale = DEFAULT_LOCALE) -> None:  # type: ignore[no-untyped-def]
    """A small table as a strip of KPI cards — ``finance.metric_strip`` — one
    box per row, each showing the row's first measure large and its label
    beneath.

    Public (no leading underscore) because nothing in this renderer's own
    pipeline currently reaches this shape from `executive_summary` — the
    compiler selects `finance.metric_strip` only when a beat's *evidence
    count* falls in its 3-6 row band, and that beat-level count is not the
    same thing as a table's actual row count (see `_draw_table_content`'s own
    note on this). It stays a first-class, directly callable component rather
    than dead code behind a heuristic, so a future artifact whose beats really
    do carry three to six metrics can reach it, and so it can be exercised on
    its own in tests today.
    """
    from pptx.enum.text import PP_ALIGN

    value_size = _clamped_pt(g.type_scale[_TS_TITLE])
    label_size = _clamped_pt(g.type_scale[_TS_SUBHEADING])

    measure = table.columns[0] if table.columns else None
    for box, row in zip(_columns(BODY, len(table.rows)), table.rows):
        # `subtotal_fill`/`subtotal_text`, not `accent` — a card is a light
        # tinted tile (the pptx analogue of `docx.py`'s shaded subtotal row),
        # not the dark header band `accent` reuses; `subtotal_text` is the
        # one colour `style.py` proves legible against `subtotal_fill`.
        card = _textbox(slide, box, fill=g.colour_roles["subtotal_fill"])
        cell = row.cells.get(measure.key) if measure else None
        value = cell.value if cell else None
        value_text = format_value(value, measure.number_format, locale=locale) if cell else ""
        if isinstance(value, (int, float)) and value < 0:
            value_text = _negative_text(value, value_text, g.number_negatives)
        frame = card.text_frame
        first = True
        for index, line in enumerate(text for text in (value_text, row.label) if text):
            paragraph = frame.paragraphs[0] if first else frame.add_paragraph()
            first = False
            paragraph.text = line
            paragraph.alignment = PP_ALIGN.CENTER
            run = paragraph.runs[0]
            # `subtotal_text` throughout, sign or no sign — see
            # `docx.py::_table`'s identical rule: `subtotal_text` is the
            # only colour `style.py` proves legible against `subtotal_fill`,
            # so a card's negative figure marks itself by the
            # parenthesised/minus convention, never by a second, unverified
            # colour painted over this fill.
            run.font.bold = index == 0
            run.font.size = _pt(value_size if index == 0 else label_size)
            run.font.color.rgb = _rgb(g.colour_roles["subtotal_text"])


# ---------------------------------------------------------------------------
# Charts
# ---------------------------------------------------------------------------


def _chart_rows(chart: Chart, table: Table) -> list[str]:
    """Row keys this chart plots, in the order they should appear.

    `Chart.rows`'s own docstring draws the line: explicit rows keep the
    author's order (a chart that puts the worst division first is a
    decision, not noise), and empty means every row that is not a subtotal —
    a chart that included the subtotals would double every bar. There the
    table's own row order is the only order there is, since there is no
    author-declared one to fall back on.
    """
    if chart.rows:
        return list(chart.rows)
    return [row.key for row in table.rows if not row.emphasis]


def _chart_series(
    chart: Chart, table: Table,
) -> tuple[list[str], list[tuple[str, list[float | None], str | None]]]:
    """Resolve a declared chart into categories and ``(label, values,
    number_format)`` series, reading nothing but cells already in *table* —
    see `Chart`'s own docstring: "a chart never introduces a number."

    `by_row` decides which axis of the table becomes which axis of the
    chart — see `Chart.by_row`'s own docstring for why getting this backwards
    renders without complaint. Reads the two fields exactly as
    `xlsx.py::_chart_block` does, so the workbook's chart and this one can
    never disagree about which cells they plot.
    """
    row_keys = _chart_rows(chart, table)
    rows_by_key = {row.key: row for row in table.rows}

    def row_label(key: str) -> str:
        row = rows_by_key.get(key)
        return row.label if row else key

    def column_label(key: str) -> str:
        column = table.column(key)
        return column.label if column else key

    def value(row_key: str, column_key: str) -> float | None:
        row = rows_by_key.get(row_key)
        cell = row.cells.get(column_key) if row else None
        if cell is None or not isinstance(cell.value, (int, float)):
            return None
        raw = float(cell.value)
        column = table.column(column_key)
        # A percentage fact is stored as 24.94; Excel's own percent format
        # multiplies by 100 to display it, so a chart axis using that format
        # needs the same 24.94 -> 0.2494 conversion `xlsx.py::render` applies
        # to cells — see that function's own comment for why the format
        # string is what decides, not the column's name.
        if column and column.number_format and column.number_format.endswith("%"):
            return raw / 100
        return raw

    if chart.by_row:
        first_format = table.column(chart.series[0]).number_format if chart.series else None
        categories = [column_label(key) for key in chart.series]
        series = [
            (row_label(row_key), [value(row_key, col_key) for col_key in chart.series], first_format)
            for row_key in row_keys
        ]
    else:
        categories = [row_label(key) for key in row_keys]
        series = [
            (column_label(col_key),
             [value(row_key, col_key) for row_key in row_keys],
             table.column(col_key).number_format if table.column(col_key) else None)
            for col_key in chart.series
        ]
    return categories, series


#: `ChartKind` -> `XL_CHART_TYPE`. A module-level name rather than a literal
#: dict built inside `_draw_chart` every call — built lazily all the same,
#: since `XL_CHART_TYPE` lives in the optional `pptx` package `_draw_chart`
#: is the only caller of.
def _chart_type(kind: ChartKind):  # type: ignore[no-untyped-def]
    from pptx.enum.chart import XL_CHART_TYPE

    return {
        ChartKind.COLUMN: XL_CHART_TYPE.COLUMN_CLUSTERED,
        ChartKind.BAR: XL_CHART_TYPE.BAR_CLUSTERED,
        ChartKind.LINE: XL_CHART_TYPE.LINE,
        ChartKind.PIE: XL_CHART_TYPE.PIE,
    }[kind]


def _draw_chart(prs, chart: Chart, table: Table, footer_text: str,
                 g: StyleGenome = _HOUSE_GENOME) -> None:  # type: ignore[no-untyped-def]
    """One declared chart, as a native OOXML chart — a real ``c:chartSpace``
    graphic frame, not a picture of one or a table dressed up as bars.

    ``shapes.add_chart`` embeds a small workbook of the plotted values
    alongside the chart XML (`python-pptx`'s own chart API always creates
    one — see `ooxml.normalise`'s docstring for the nested-clock defect that
    turned out to cause). Every value in it is read by `_chart_series`
    straight off *table*, never computed here, which is what lets a reader
    check the chart against the same table the slide (or an earlier one, if
    the table itself paginated) already showed.
    """
    from pptx.chart.data import CategoryChartData
    from pptx.enum.chart import XL_LEGEND_POSITION

    categories, series = _chart_series(chart, table)
    if not categories or not series:
        return

    # A pie plots one total's composition — `ChartKind.PIE`'s own docstring —
    # so a second series would silently double the wedges. Plotting only the
    # first is the same defensive read `docx.py::_figure` already gives a
    # chart whose declaration does not match its own kind.
    plotted = series[:1] if chart.kind is ChartKind.PIE else series

    slide = _new_slide(prs, chart.title, footer_text=footer_text, g=g)

    box = BODY
    note_box = None
    if chart.note:
        note_h = _in(0.4)
        box = Box(BODY.x, BODY.y, BODY.cx, BODY.cy - note_h - _GUTTER)
        note_box = Box(BODY.x, box.bottom + _GUTTER, BODY.cx, note_h)
    _assert_in_bounds(box)

    data = CategoryChartData()
    data.categories = categories
    for label, values, number_format in plotted:
        # A blank cell plots as zero rather than vanishing — `add_series` has
        # no notion of a missing point, and dropping one would silently
        # reindex every point after it against the wrong category.
        data.add_series(label, tuple(v if v is not None else 0.0 for v in values),
                         number_format=number_format or "General")

    graphic_frame = slide.shapes.add_chart(
        _chart_type(chart.kind), box.x, box.y, box.cx, box.cy, data
    )
    native = graphic_frame.chart
    native.has_title = False  # the slide heading above already carries it

    # A single-series bar or line needs no legend to say what it is; a pie
    # always does, because its wedges have no axis to be labelled by.
    native.has_legend = len(plotted) > 1 or chart.kind is ChartKind.PIE
    if native.has_legend:
        native.legend.position = XL_LEGEND_POSITION.BOTTOM
        native.legend.include_in_layout = False
        native.legend.font.size = _pt(MIN_FONT_PT)
        native.legend.font.color.rgb = _rgb(g.colour_roles["body_text"])

    if chart.kind is not ChartKind.PIE:
        for axis, title in (
            (native.category_axis, chart.category_axis),
            (native.value_axis, chart.value_axis),
        ):
            axis.tick_labels.font.size = _pt(MIN_FONT_PT)
            axis.tick_labels.font.color.rgb = _rgb(g.colour_roles["body_text"])
            if title:
                axis.has_title = True
                axis.axis_title.text_frame.text = title
                run = axis.axis_title.text_frame.paragraphs[0].runs[0]
                run.font.size = _pt(MIN_FONT_PT)
                run.font.color.rgb = _rgb(g.colour_roles["body_text"])

    if note_box is not None:
        note_shape = _textbox(slide, note_box)
        _write(note_shape.text_frame, [chart.note], size=MIN_FONT_PT, colour=_MUTED, italic=True)


def _draw_table_content(prs, slide_plan, footer_text: str, g: StyleGenome = _HOUSE_GENOME, locale: Locale = DEFAULT_LOCALE) -> None:  # type: ignore[no-untyped-def]
    table = slide_plan.table
    assert table is not None

    # `finance.metric_strip` is a *hint*, not a guarantee, that this table is
    # metric-strip shaped — see `draw_metric_cards`'s docstring. Checked
    # against the table's own row and column counts before trusting it, so a
    # table the compiler tagged that way for beat-level reasons but that is
    # actually wide or long still gets the table it can honestly hold.
    if slide_plan.component_id == "finance.metric_strip" and 1 <= len(table.rows) <= 6 and len(table.columns) <= 3:
        slide = _new_slide(prs, slide_plan.heading, footer_text=footer_text, g=g)
        draw_metric_cards(slide, table, g, locale)
        return

    chunks = [
        table.rows[i : i + _MAX_TABLE_ROWS_PER_SLIDE]
        for i in range(0, len(table.rows), _MAX_TABLE_ROWS_PER_SLIDE)
    ] or [[]]
    for index, rows in enumerate(chunks):
        # No digit in the continuation heading — a bare "(2)" would be a
        # figure this renderer typed rather than one the IR gave it, and the
        # bare-number rule in `AGENTS.md` does not stop applying just because
        # the number in question is furniture rather than a fact.
        heading = slide_plan.heading if index == 0 else f"{slide_plan.heading} (continued)"
        slide = _new_slide(prs, heading, footer_text=footer_text, g=g)
        # The note belongs to the table, not to any one page of it — shown
        # once, on the first slide, rather than repeated on every
        # continuation where it would read as new information each time.
        _draw_table(slide, table, rows, note=table.note if index == 0 else None, g=g, locale=locale)


def _draw_content(  # type: ignore[no-untyped-def]
    prs, plan: PresentationPlan, slide_plan, facts: dict[str, CanonicalFact],
    g: StyleGenome = _HOUSE_GENOME, locale: Locale = DEFAULT_LOCALE,
    profile: PresentationProfile = DEFAULT_PRESENTATION,
) -> None:
    """Dispatch one resolved section to a table or prose slide.

    Dispatch is on the section's own shape — whether it carries a ``table`` or
    a ``body`` — not on ``component_id`` alone. The compiler's component
    choice already had to agree with the section's shape to be selected in the
    first place (`ComponentSpec.fits` checks density and row bounds before a
    component can be picked at all), so this is not a second, competing
    opinion — it is reading the same fact the compiler already established,
    the only way this renderer is allowed to read it: off the IR.
    """
    footer_text = f"{plan.metadata.get('company', '')} · {plan.title}"
    if slide_plan.table is not None:
        _draw_table_content(prs, slide_plan, footer_text, g, locale)
    elif slide_plan.body:
        _draw_prose_content(prs, slide_plan, facts, footer_text, g, locale, profile)
    else:
        slide = _new_slide(prs, slide_plan.heading, footer_text=footer_text, g=g)
        body = _textbox(slide, BODY)
        _write(body.text_frame, [_AWAITING], size=_clamped_pt(g.type_scale[_TS_BODY]), colour=_MUTED, italic=True)

    # One extra slide per declared chart, after whatever the table (however
    # many slides it paginated into) or prose above produced — see
    # `SlidePlan.charts`'s own docstring. Guarded on the table actually being
    # *this* chart's table, not merely present: `Chart`'s own docstring says
    # every value it plots is a cell "already in the table beside it", and a
    # mismatched `chart.table` would be this renderer inventing which table
    # that was rather than reading it off the IR.
    if slide_plan.table is not None:
        for chart in slide_plan.charts:
            if chart.table == slide_plan.table.key:
                _draw_chart(prs, chart, slide_plan.table, footer_text, g)


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------


def render(
    ir: ArtifactIR,
    facts: dict[str, CanonicalFact] | None = None,
    *,
    locale: Locale = DEFAULT_LOCALE,
    profile: PresentationProfile = DEFAULT_PRESENTATION,
) -> bytes:
    """Render one IR to PPTX bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render
    time. Without it the references stay visible, which is the right failure —
    a deck that quietly drops a figure reads as finished and is not.

    *locale* reaches the column widths as well as the cells, which is why
    `_column_widths` takes one: it measures a column by the longest text it
    actually holds, and `1.234,50 EUR` is not the same number of characters as
    `1,234.50` in every jurisdiction. A width measured in one grammar and drawn
    in another is a table that overflows its box for no visible reason.
    """
    pptx_pkg = _require_pptx()
    plan = _plan(ir, profile)
    g = _genome_for(ir)

    presentation = pptx_pkg.Presentation()
    presentation.slide_width = SLIDE_W
    presentation.slide_height = SLIDE_H

    for slide_plan in plan.slides:
        if slide_plan.kind == "cover":
            _draw_cover(presentation, plan, g)
        elif slide_plan.kind == "divider":
            _draw_divider(presentation, slide_plan.heading, g)
        elif slide_plan.kind == "closing":
            _draw_closing(presentation, plan, g)
        else:
            _draw_content(presentation, plan, slide_plan, facts, g, locale, profile)

    properties = presentation.core_properties
    properties.title = ir.title
    properties.subject = ir.subtitle or ""
    properties.author = ir.metadata.get("author") or "Worldloom"
    properties.comments = ir.metadata.get("note", "Synthetic corpus generated by Worldloom.")
    properties.keywords = "synthetic,worldloom,seed=" + ir.metadata.get("worldloom_seed", "")
    if ir.metadata.get("voice") and profile.provenance == "properties":
        # PowerPoint's category field, for `docx.render`'s reason: the brief
        # is worth keeping and belongs off the slides.
        properties.category = (
            f"voice: {ir.metadata['voice']}; persona: {ir.metadata.get('persona', '')}"
        )

    from io import BytesIO

    buffer = BytesIO()
    presentation.save(buffer)
    # Dates come from the world, never the clock — see `ooxml.normalise`. Both
    # python-pptx's per-entry zip timestamps and its template's own static
    # `docProps/core.xml` dates are wall-clock or template artefacts, exactly
    # the defect `ooxml.py` exists to correct for DOCX and XLSX alike.
    return ooxml.normalise(buffer.getvalue(), created=ir.metadata.get("worldloom_created"))


def render_all(world: World) -> list[Rendered]:
    """Render every executive-summary-shaped artifact in *world*."""
    facts = {fact.id: fact for fact in world.facts}
    locale = corpus_locale(world)
    profile = presentation_of(world)
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type not in HANDLES:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.pptx",
                media_type=MEDIA_TYPE,
                payload=render(ir, facts, locale=locale,
                               profile=profile.for_doctype(intent.artifact_type)),
            )
        )
    return out
