"""The PPTX renderer.

A board deck is where the executive summary this project already emits
actually gets consumed — nobody hands a CFO a Markdown file. Per
``docs/artifact-compiler.md`` sections 9.1 and 14.A, this is the vertical
slice: one artifact type, the pipeline that document describes end to end, and
nothing wider.

::

    ArtifactIR -> PresentationPlan -> slide components -> geometry solve
    -> python-pptx -> OOXML normalisation -> structural validation

Same rule as every other renderer in this package: this reads the IR and
nothing else. The compiler (``worldloom.compiler``) turns the IR into a
validated sequence of component ids — the same deterministic, grammar-checked
composition any format in this repo could reach for — and this module's only
job is to spell that sequence as shapes. Nothing here computes a number,
resolves a fact, or decides which rows belong in a table; every value that
lands on a slide is either prose the narrative compiler already validated
(with ``{{fact:ID}}`` substituted the same way ``docx`` and ``markdown`` do)
or a cell that was already sitting in a resolved ``Table``.

``PresentationPlan``, ``SlidePlan`` and ``Box`` are renderer-local. Per
``docs/artifact-compiler.md`` section 2, a format plan is a rendering concern
— it is rebuilt from the IR every time a deck is wanted and is never
persisted, so it cannot drift from the artifact it describes the way a second
hand-kept structure could. None of the three belongs in ``models.py``.

Geometry is explicit ``Box(x, y, cx, cy)`` arithmetic against a handful of
module constants, not a constraint solver. Per section 14.E, CP-SAT and a
Cassowary solver are justified only once greedy layout fails a recorded
fixture — this renderer has one artifact type and at most a handful of shapes
per slide, and reaching for a solver here would be solving a problem that
does not exist yet.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from ..compiler.compose import compose, plan_from_ir
from ..models import ArtifactIR, CanonicalFact, Row, Table
from ..narrative import references
from . import Rendered, RenderError, ooxml, slug_for
from .values import format_value

if TYPE_CHECKING:  # pragma: no cover
    from ..world import World

MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.presentationml.presentation"

#: Artifact types this renderer spells. Per 14.A the vertical slice targets one
#: artifact — the executive summary the retail-close episode already emits —
#: rather than the wider ``HANDLES`` set `docx.py` covers. Widening this is
#: 14.B work (component registry extraction, more layout families), not this
#: slice's job.
HANDLES = frozenset({"executive_summary"})

#: Same wording DOCX and Markdown use for a section still awaiting prose. One
#: string, so a reader comparing all three formats of an unfinished corpus sees
#: one message rather than three renderers each describing the gap differently.
_AWAITING = (
    "Awaiting narrative. Structure and supporting facts are resolved; "
    "prose is generated by the constrained compiler."
)

_HIDDEN_NOTE = "Not part of the readable surface."


def _require_pptx():  # type: ignore[no-untyped-def]
    try:
        import pptx
    except ImportError as exc:  # pragma: no cover - depends on install extras
        raise RenderError(
            "the pptx format needs python-pptx. Install it with: pip install 'worldloom[pptx]'"
        ) from exc
    return pptx


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------

_EMU_PER_INCH = 914_400


def _in(inches: float) -> int:
    """Inches to EMU, the unit every OOXML coordinate is stored in.

    A plain function rather than reaching for ``pptx.util.Inches`` — the
    geometry constants below are computed at import time, before
    ``_require_pptx`` has run, so they cannot depend on the optional package.
    ``Emu``/``Inches`` are themselves just ``int`` subclasses; python-pptx
    accepts a bare EMU int anywhere it accepts a ``Length``.
    """
    return round(inches * _EMU_PER_INCH)


#: Widescreen, because every deck this renders is a 2020s corporate one, not a
#: 2003-era projector. 13.333 x 7.5in is PowerPoint's own 16:9 default size.
SLIDE_W = _in(13.333)
SLIDE_H = _in(7.5)

#: Outer margin and the gap between stacked regions. Not copied from `docx.py`
#: verbatim — its 22mm page margin (~0.87in) is tuned for an A4 page held
#: close; a slide is wider and shorter, and the same margin there would eat a
#: third of the usable width. Tighter, so the two formats read as
#: proportionate rather than as one renderer ignoring the other's convention.
_MARGIN = _in(0.55)
_GUTTER = _in(0.25)

#: The coloured band carrying a slide's heading, and the footer strip below the
#: body. Both span the full slide width (no side margin) — a full-bleed band
#: is what makes a slide read as "a deck" rather than "a page with a border".
_HEADER_H = _in(0.85)
_FOOTER_H = _in(0.35)

_CONTENT_X = _MARGIN
_CONTENT_W = SLIDE_W - 2 * _MARGIN

_BODY_Y = _HEADER_H + _GUTTER
_FOOTER_Y = SLIDE_H - _FOOTER_H
_BODY_H = _FOOTER_Y - _GUTTER - _BODY_Y


@dataclass(frozen=True)
class Box:
    """One rectangle in EMU. The only geometry primitive this renderer has.

    Nothing below ever searches for a box — every ``Box`` is either a module
    constant or arithmetic over one (see ``_stack`` and ``_columns``), which is
    what "deterministic greedy layout" concretely means here: the same IR
    produces the same boxes because there is no search, only addition.
    """

    x: int
    y: int
    cx: int
    cy: int

    @property
    def right(self) -> int:
        return self.x + self.cx

    @property
    def bottom(self) -> int:
        return self.y + self.cy


#: The three horizontal bands every slide is built from, fixed for the whole
#: deck. A slide-specific layout only ever subdivides ``BODY``; ``HEADER`` and
#: ``FOOTER`` are the same rectangle on every slide, which is what stops a
#: one-off slide from silently drifting the deck's furniture out from under
#: the rest.
HEADER = Box(0, 0, SLIDE_W, _HEADER_H)
BODY = Box(_CONTENT_X, _BODY_Y, _CONTENT_W, _BODY_H)
FOOTER = Box(0, _FOOTER_Y, SLIDE_W, _FOOTER_H)


def _assert_in_bounds(box: Box) -> None:
    """A shape that starts life out of bounds is a bug in this renderer's own
    arithmetic, not something the structural validator downstream should have
    to be the first to catch."""
    assert box.x >= 0 and box.y >= 0, box
    assert box.right <= SLIDE_W and box.bottom <= SLIDE_H, box


def _stack(x: int, top: int, width: int, heights: list[int], gap: int = _GUTTER) -> list[Box]:
    """*heights* laid out downward from *top*, each separated by *gap*.

    The one layout combinator this renderer needs: every multi-element slide
    (the cover, a prose slide with an accent bar) is boxes stacked or set side
    by side, never positioned by hand — which is what makes non-overlap a
    property of the arithmetic rather than something checked after the fact,
    box by box.
    """
    boxes = []
    y = top
    for h in heights:
        boxes.append(Box(x, y, width, h))
        y += h + gap
    return boxes


def _columns(box: Box, count: int, gap: int = _GUTTER) -> list[Box]:
    """*box* split into *count* equal-width columns side by side."""
    width = (box.cx - gap * (count - 1)) // count
    return [Box(box.x + i * (width + gap), box.y, width, box.cy) for i in range(count)]


# ---------------------------------------------------------------------------
# The plan
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SlidePlan:
    """One slide's resolved content, already assigned a component family.

    Renderer-local and rebuilt on every render — see the module docstring.
    ``kind`` picks the slide's furniture (a cover has no header band, a
    divider has no footer table); ``component_id`` is the compiler's choice of
    family for content slides, and it only ever selects a *visual treatment*.
    What actually appears is always ``body`` or ``table`` off the IR section
    this plan came from — never something the component id invents.
    """

    kind: str  # "cover" | "divider" | "content" | "closing"
    component_id: str
    heading: str
    body: str | None = None
    table: Table | None = None
    hidden: bool = False


@dataclass(frozen=True)
class PresentationPlan:
    """The whole deck, before a single shape exists."""

    title: str
    subtitle: str | None
    metadata: dict[str, str]
    slides: tuple[SlidePlan, ...]


#: The size class and density profile handed to the compiler. Not read off the
#: originating ``ArtifactIntent`` — ``render(ir, facts)`` carries the same
#: signature as every other format here and the IR itself does not carry a
#: size class, so threading the intent through would widen this module's
#: surface for a value that is already implied: every ``executive_summary`` in
#: `generators/planning.py` is planned as ``"small"``, because it is an
#: executive committee's one-pager, not a workbook. If a future
#: ``executive_summary`` ever grows past the four beats that implies,
#: ``compose`` raises rather than silently overflowing a slide — see `_plan`.
_SIZE_CLASS = "small"
_DENSITY_PROFILE = "balanced"


def _plan(ir: ArtifactIR) -> PresentationPlan:
    """``ArtifactIR`` -> ``PresentationPlan``, by way of the compiler.

    ``compose`` decides which component family presents each section and
    checks the resulting sequence reads as a document a company would issue
    (``docs/artifact-compiler.md`` section 4). This function's only job is to
    turn that validated sequence into slides, adding the structural slides —
    cover, appendix divider, closing — that the compiler has no opinion about
    because they carry no beat of the argument.
    """
    plan = plan_from_ir(
        ir,
        artifact_type="executive_summary",
        size_class=_SIZE_CLASS,
        density_profile=_DENSITY_PROFILE,
    )
    composition = compose(plan, fmt="pptx")
    if not composition.ok:
        raise RenderError(
            f"{ir.id}: component sequence is not a grammatical executive_summary: "
            + "; ".join(str(v) for v in composition.violations)
        )

    # `plan.beats` and `ir.sections` are built 1:1, in order, by `plan_from_ir`
    # — one beat per section, nothing filtered before `compose` runs — so
    # zipping them is the correct way back to the section a beat came from,
    # without re-deriving the beat-key slug `compose` computes internally.
    section_by_beat = {beat.key: section for beat, section in zip(plan.beats, ir.sections)}

    slides: list[SlidePlan] = [SlidePlan(kind="cover", component_id="cover", heading=ir.title)]
    appendix_opened = False
    for component_id, beat_key in zip(composition.components, composition.beats):
        section = section_by_beat[beat_key]
        if section.hidden and not appendix_opened:
            # One divider, however many hidden sections fall inside the
            # appendix — not one per section, which would read as the deck
            # repeatedly announcing the same change of subject.
            slides.append(
                SlidePlan(kind="divider", component_id="core.section_divider", heading="Appendix")
            )
            appendix_opened = True
        slides.append(
            SlidePlan(
                kind="content",
                component_id=component_id,
                heading=section.heading,
                body=section.body,
                table=section.table,
                hidden=section.hidden,
            )
        )
    slides.append(SlidePlan(kind="closing", component_id="closing", heading="Closing"))

    return PresentationPlan(title=ir.title, subtitle=ir.subtitle, metadata=ir.metadata, slides=tuple(slides))


# ---------------------------------------------------------------------------
# Style
# ---------------------------------------------------------------------------

#: The same palette `docx.py` uses (its ``_HEADER_FILL`` and negative red),
#: reused rather than re-derived — a reader who has seen the memo should
#: recognise the deck as the same company's document, not a different colour
#: scheme wearing the same title.
_HEADER_FILL = "2F4858"
_ACCENT_FILL = "EDF2F4"
_NEGATIVE = "9B2226"
_INK = "1B1F22"
_MUTED = "6B747B"
_SUBTITLE_INK = "4A555C"
_WHITE = "FFFFFF"

#: No text on any slide goes below this. PowerPoint's own accessibility
#: checker starts flagging body copy under 18pt for a *projected* deck, but
#: nothing this renderer produces is meant to be read from the back of a room
#: — it is read on a screen, the same way the DOCX and Markdown twins of the
#: same artifact are. 12pt is the floor below which even screen reading starts
#: to strain, and it is deliberately not lower than the smallest text DOCX
#: itself ever uses (`docx.py`'s footnote and table text sit at 8-9pt, but
#: that is on an A4 page held close, which a slide viewed at arm's length is
#: not).
MIN_FONT_PT = 12


def _rgb(hexcode: str):  # type: ignore[no-untyped-def]
    from pptx.dml.color import RGBColor

    return RGBColor.from_string(hexcode)


def _pt(size: int):  # type: ignore[no-untyped-def]
    from pptx.util import Pt

    assert size >= MIN_FONT_PT, f"{size}pt would sit below the {MIN_FONT_PT}pt floor — see MIN_FONT_PT"
    return Pt(size)


def _textbox(slide, box: Box, *, fill: str | None = None):  # type: ignore[no-untyped-def]
    """A text box at *box*, transparent unless *fill* is given.

    Every text-bearing shape in this module goes through here, which is what
    keeps word-wrap, margins, and the no-autofit choice below uniform instead
    of each ``_draw_*`` function reimplementing them slightly differently.
    """
    from pptx.enum.text import MSO_AUTO_SIZE

    _assert_in_bounds(box)
    shape = slide.shapes.add_textbox(box.x, box.y, box.cx, box.cy)
    frame = shape.text_frame
    frame.word_wrap = True
    # Not the default. `SHAPE_TO_FIT_TEXT` is a hint for the *next* editor to
    # resize the shape around its text — left on, a box we sized deliberately
    # could grow past the bounds this module computed the moment someone
    # opens and re-saves the deck. This renderer owns the geometry; nothing
    # downstream should get to override it.
    frame.auto_size = MSO_AUTO_SIZE.NONE
    frame.margin_left = frame.margin_right = _in(0.12)
    frame.margin_top = frame.margin_bottom = _in(0.06)
    if fill is not None:
        shape.fill.solid()
        shape.fill.fore_color.rgb = _rgb(fill)
        shape.line.fill.background()
    else:
        shape.fill.background()
        shape.line.fill.background()
    return shape


def _write(
    frame,  # type: ignore[no-untyped-def]
    paragraphs: list[str],
    *,
    size: int,
    colour: str,
    bold: bool = False,
    italic: bool = False,
    align=None,  # type: ignore[no-untyped-def]
) -> None:
    """Fill a text frame with one paragraph per string, uniformly styled.

    Every run gets an explicit size and colour rather than inheriting the
    theme default — inheritance is exactly what would let a run slip under
    ``MIN_FONT_PT`` unnoticed, since nothing would ever assign it a size to
    check.
    """
    first = True
    for text in paragraphs:
        if not text:
            continue
        paragraph = frame.paragraphs[0] if first else frame.add_paragraph()
        first = False
        paragraph.text = text
        if align is not None:
            paragraph.alignment = align
        run = paragraph.runs[0]
        run.font.size = _pt(size)
        run.font.bold = bold
        run.font.italic = italic
        run.font.color.rgb = _rgb(colour)


def _new_slide(prs, heading: str, *, footer_text: str):  # type: ignore[no-untyped-def]
    """A blank slide with the two bands every content slide shares."""
    from pptx.enum.text import MSO_ANCHOR, PP_ALIGN

    slide = prs.slides.add_slide(prs.slide_layouts[6])  # "Blank" — see module docstring

    header = _textbox(slide, HEADER, fill=_HEADER_FILL)
    header.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    _write(header.text_frame, [heading], size=24, colour=_WHITE, bold=True)

    footer = _textbox(slide, FOOTER)
    footer.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    _write(footer.text_frame, [footer_text], size=MIN_FONT_PT, colour=_MUTED, italic=True, align=PP_ALIGN.CENTER)

    return slide


# ---------------------------------------------------------------------------
# Slide components
# ---------------------------------------------------------------------------


def _draw_cover(prs, plan: PresentationPlan) -> None:  # type: ignore[no-untyped-def]
    """The title slide. Structural, like `docx.py`'s ``_cover`` — not a
    compiler component, because it carries no beat of the argument."""
    from pptx.enum.text import PP_ALIGN

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    title_box, subtitle_box, byline_box = _stack(
        _CONTENT_X, _in(2.4), _CONTENT_W, [_in(1.1), _in(0.6), _in(0.5)]
    )

    title = _textbox(slide, title_box)
    _write(title.text_frame, [plan.title], size=40, colour=_INK, bold=True, align=PP_ALIGN.CENTER)

    if plan.subtitle:
        subtitle = _textbox(slide, subtitle_box)
        _write(
            subtitle.text_frame, [plan.subtitle], size=18, colour=_SUBTITLE_INK,
            italic=True, align=PP_ALIGN.CENTER,
        )

    author = plan.metadata.get("author")
    if author:
        author_title = plan.metadata.get("author_title")
        byline_text = f"{author}, {author_title}" if author_title else author
        byline = _textbox(slide, byline_box)
        _write(byline.text_frame, [byline_text], size=16, colour=_INK, bold=True, align=PP_ALIGN.CENTER)

    company = plan.metadata.get("company", "")
    note = plan.metadata.get("note", "Synthetic corpus generated by Worldloom. Not a real company.")
    note_box = Box(_CONTENT_X, SLIDE_H - _MARGIN - _in(0.4), _CONTENT_W, _in(0.4))
    note_shape = _textbox(slide, note_box)
    _write(
        note_shape.text_frame,
        [f"{company} · {note}" if company else note],
        size=MIN_FONT_PT, colour=_MUTED, italic=True, align=PP_ALIGN.CENTER,
    )


def _draw_divider(prs, heading: str) -> None:  # type: ignore[no-untyped-def]
    """A section-divider slide — ``core.section_divider``.

    Used once, ahead of the appendix, to mark the change of subject the same
    way `docx.py` marks a hidden section: present, but flagged as not part of
    the readable surface.
    """
    from pptx.enum.text import MSO_ANCHOR, PP_ALIGN

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    band_box = Box(0, _in(2.6), SLIDE_W, _in(1.3))
    band = _textbox(slide, band_box, fill=_HEADER_FILL)
    band.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    _write(band.text_frame, [heading], size=32, colour=_WHITE, bold=True, align=PP_ALIGN.CENTER)

    note_box = Box(_CONTENT_X, band_box.bottom + _GUTTER, _CONTENT_W, _in(0.5))
    note = _textbox(slide, note_box)
    _write(note.text_frame, [_HIDDEN_NOTE], size=14, colour=_MUTED, italic=True, align=PP_ALIGN.CENTER)


def _draw_closing(prs, plan: PresentationPlan) -> None:  # type: ignore[no-untyped-def]
    """The closing slide. Carries the same author-voice line `docx.py`'s
    closing paragraph does, off the same metadata — not a new statement."""
    footer_text = f"{plan.metadata.get('company', '')} · {plan.title}"
    slide = _new_slide(prs, "Closing", footer_text=footer_text)
    voice = plan.metadata.get("voice", "")
    persona = plan.metadata.get("persona", "")
    body = _textbox(slide, BODY)
    _write(body.text_frame, [f"Author voice: {voice}. Persona: {persona}."], size=16, colour=_MUTED, italic=True)


#: Per-component visual treatment for a prose slide. ``accent`` draws a narrow
#: coloured bar down the left of the body box — a cheap, cheap-to-verify way
#: to give ``core.schedule`` and ``mgmt.decision_panel`` a distinct silhouette
#: from a plain narrative slide without inventing content neither carries.
_PROSE_STYLE: dict[str, dict] = {
    "core.position": {"size": 22, "bold": True},
    "core.executive_summary": {"size": 20},
    "core.schedule": {"size": 18, "accent": True},
    "mgmt.decision_panel": {"size": 18, "accent": True},
}
_DEFAULT_PROSE_STYLE = {"size": 18}


def _draw_prose_content(prs, slide_plan, facts, footer_text: str) -> None:  # type: ignore[no-untyped-def]
    """A section whose content is prose — ``core.position``, ``core.narrative``
    and the rest of the text-shaped components in the registry."""
    slide = _new_slide(prs, slide_plan.heading, footer_text=footer_text)
    resolved = references.substitute(slide_plan.body, facts) if facts else slide_plan.body
    # Blank lines are paragraph breaks — the same convention `docx.py` follows
    # for the identical reason: a single run holding newlines renders as one
    # unbroken block, not separate paragraphs.
    paragraphs = [block.strip() for block in resolved.split("\n\n") if block.strip()]

    style = _PROSE_STYLE.get(slide_plan.component_id, _DEFAULT_PROSE_STYLE)
    box = BODY
    if style.get("accent"):
        bar_w = _in(0.08)
        _textbox(slide, Box(BODY.x, BODY.y, bar_w, BODY.cy), fill=_HEADER_FILL)
        box = Box(BODY.x + bar_w + _GUTTER, BODY.y, BODY.cx - bar_w - _GUTTER, BODY.cy)

    text = _textbox(slide, box)
    _write(text.text_frame, paragraphs, size=style["size"], colour=_INK, bold=style.get("bold", False))


#: Row budget per table slide. Not derived from `ComponentSpec.max_rows` —
#: those bands constrain which *component* the compiler assigns a beat, not
#: how many rows fit one physical slide of this renderer's own geometry, and
#: the two questions have different answers (`finance.variance_table` has no
#: declared cap at all, because a workbook table has no fixed canvas — a slide
#: always does). ``BODY`` is 5.8in tall; a header row plus 6 data rows leaves
#: ~0.83in per row, comfortably above one wrapped line at the 12pt floor even
#: for the longest cell text this renderer has seen (~50 characters).
_MAX_TABLE_ROWS_PER_SLIDE = 6


def _column_widths(table: Table, total: int) -> list[int]:
    """Column widths proportional to their content, not divided evenly.

    A table whose "statement" column carries a sentence and whose "authority"
    column carries one word looks unreadable split into equal fifths. Each
    column is weighted by the longest text it actually holds (header label
    included) — a property of the resolved data, not a guess about it, and the
    same ``format_value`` every other renderer uses, so the measured width
    agrees with what actually gets drawn into the cell.

    Rounds every column but the last, then gives the last the exact remainder
    — the sum has to equal *total* precisely, or the table's own shape would
    drift out of the bounds this renderer computed for it.
    """
    label_width = max((len(row.label) for row in table.rows), default=6)
    weights = [max(label_width, 6)]
    for column in table.columns:
        longest = len(column.label)
        for row in table.rows:
            cell = row.cells.get(column.key)
            if cell is not None:
                longest = max(longest, len(format_value(cell.value, column.number_format)))
        weights.append(max(longest, 6))

    share = sum(weights)
    widths = [round(total * weight / share) for weight in weights[:-1]]
    widths.append(total - sum(widths))
    return widths


def _style_cell(cell, *, size: int, colour: str, bold: bool = False, fill: str | None = None, align=None) -> None:  # type: ignore[no-untyped-def]
    if fill is not None:
        cell.fill.solid()
        cell.fill.fore_color.rgb = _rgb(fill)
    frame = cell.text_frame
    frame.word_wrap = True
    for paragraph in frame.paragraphs:
        if align is not None:
            paragraph.alignment = align
        for run in paragraph.runs:
            run.font.size = _pt(size)
            run.font.bold = bold
            run.font.color.rgb = _rgb(colour)


def _draw_table(slide, table: Table, rows: list[Row], *, note: str | None) -> None:  # type: ignore[no-untyped-def]
    """One table, or one page of a paginated one, as a native PPTX table.

    Mirrors `docx.py`'s ``_table``: a label column then one column per
    measure, right-aligned numbers, subtotal rows shaded, negatives marked
    twice over (parenthesised by ``format_value`` and coloured) so the sign
    survives a black-and-white printout of a slide as readily as a page.
    """
    from pptx.enum.text import PP_ALIGN

    box = BODY
    note_box = None
    if note:
        note_h = _in(0.45)
        box = Box(BODY.x, BODY.y, BODY.cx, BODY.cy - note_h - _GUTTER)
        note_box = Box(BODY.x, box.bottom + _GUTTER, BODY.cx, note_h)
    _assert_in_bounds(box)

    graphic = slide.shapes.add_table(len(rows) + 1, len(table.columns) + 1, box.x, box.y, box.cx, box.cy)
    grid = graphic.table
    for column, width in zip(grid.columns, _column_widths(table, box.cx)):
        column.width = width

    header_cells = grid.rows[0].cells
    header_cells[0].text = table.title
    for index, column in enumerate(table.columns, start=1):
        header_cells[index].text = column.label
    for index, cell in enumerate(header_cells):
        _style_cell(
            cell, size=13, colour=_WHITE, bold=True, fill=_HEADER_FILL,
            align=PP_ALIGN.LEFT if index == 0 else PP_ALIGN.RIGHT,
        )

    for row_index, row in enumerate(rows, start=1):
        cells = grid.rows[row_index].cells
        cells[0].text = row.label
        _style_cell(cells[0], size=MIN_FONT_PT, colour=_INK, bold=row.emphasis)
        for column_index, column in enumerate(table.columns, start=1):
            cell = row.cells.get(column.key)
            value = cell.value if cell else None
            cells[column_index].text = format_value(value, column.number_format) if cell else ""
            negative = isinstance(value, (int, float)) and value < 0
            _style_cell(
                cells[column_index], size=MIN_FONT_PT, colour=_NEGATIVE if negative else _INK,
                bold=row.emphasis, align=PP_ALIGN.RIGHT,
            )
        if row.emphasis:
            for cell in cells:
                cell.fill.solid()
                cell.fill.fore_color.rgb = _rgb(_ACCENT_FILL)

    if note_box is not None:
        note_shape = _textbox(slide, note_box)
        _write(note_shape.text_frame, [note], size=MIN_FONT_PT, colour=_MUTED, italic=True)


def draw_metric_cards(slide, table: Table) -> None:  # type: ignore[no-untyped-def]
    """A small table as a strip of KPI cards — ``finance.metric_strip`` — one
    box per row, each showing the row's first measure large and its label
    beneath.

    Public (no leading underscore) because nothing in this renderer's own
    pipeline currently reaches this shape from `executive_summary` — the
    compiler selects `finance.metric_strip` only when a beat's *evidence
    count* falls in its 3-6 row band, and that beat-level count is not the
    same thing as a table's actual row count (see `_draw_table_content`'s own
    note on this). It stays a first-class, directly callable component rather
    than dead code behind a heuristic, so a future artifact whose beats really
    do carry three to six metrics can reach it, and so it can be exercised on
    its own in tests today.
    """
    from pptx.enum.text import PP_ALIGN

    measure = table.columns[0] if table.columns else None
    for box, row in zip(_columns(BODY, len(table.rows)), table.rows):
        card = _textbox(slide, box, fill=_ACCENT_FILL)
        cell = row.cells.get(measure.key) if measure else None
        value_text = format_value(cell.value, measure.number_format) if cell else ""
        frame = card.text_frame
        first = True
        for index, line in enumerate(text for text in (value_text, row.label) if text):
            paragraph = frame.paragraphs[0] if first else frame.add_paragraph()
            first = False
            paragraph.text = line
            paragraph.alignment = PP_ALIGN.CENTER
            run = paragraph.runs[0]
            run.font.size = _pt(24 if index == 0 else 13)
            run.font.bold = index == 0
            run.font.color.rgb = _rgb(_HEADER_FILL if index == 0 else _MUTED)


def _draw_table_content(prs, slide_plan, footer_text: str) -> None:  # type: ignore[no-untyped-def]
    table = slide_plan.table
    assert table is not None

    # `finance.metric_strip` is a *hint*, not a guarantee, that this table is
    # metric-strip shaped — see `draw_metric_cards`'s docstring. Checked
    # against the table's own row and column counts before trusting it, so a
    # table the compiler tagged that way for beat-level reasons but that is
    # actually wide or long still gets the table it can honestly hold.
    if slide_plan.component_id == "finance.metric_strip" and 1 <= len(table.rows) <= 6 and len(table.columns) <= 3:
        slide = _new_slide(prs, slide_plan.heading, footer_text=footer_text)
        draw_metric_cards(slide, table)
        return

    chunks = [
        table.rows[i : i + _MAX_TABLE_ROWS_PER_SLIDE]
        for i in range(0, len(table.rows), _MAX_TABLE_ROWS_PER_SLIDE)
    ] or [[]]
    for index, rows in enumerate(chunks):
        # No digit in the continuation heading — a bare "(2)" would be a
        # figure this renderer typed rather than one the IR gave it, and the
        # bare-number rule in `AGENTS.md` does not stop applying just because
        # the number in question is furniture rather than a fact.
        heading = slide_plan.heading if index == 0 else f"{slide_plan.heading} (continued)"
        slide = _new_slide(prs, heading, footer_text=footer_text)
        # The note belongs to the table, not to any one page of it — shown
        # once, on the first slide, rather than repeated on every
        # continuation where it would read as new information each time.
        _draw_table(slide, table, rows, note=table.note if index == 0 else None)


def _draw_content(prs, plan: PresentationPlan, slide_plan, facts: dict[str, CanonicalFact]) -> None:  # type: ignore[no-untyped-def]
    """Dispatch one resolved section to a table or prose slide.

    Dispatch is on the section's own shape — whether it carries a ``table`` or
    a ``body`` — not on ``component_id`` alone. The compiler's component
    choice already had to agree with the section's shape to be selected in the
    first place (`ComponentSpec.fits` checks density and row bounds before a
    component can be picked at all), so this is not a second, competing
    opinion — it is reading the same fact the compiler already established,
    the only way this renderer is allowed to read it: off the IR.
    """
    footer_text = f"{plan.metadata.get('company', '')} · {plan.title}"
    if slide_plan.table is not None:
        _draw_table_content(prs, slide_plan, footer_text)
    elif slide_plan.body:
        _draw_prose_content(prs, slide_plan, facts, footer_text)
    else:
        slide = _new_slide(prs, slide_plan.heading, footer_text=footer_text)
        body = _textbox(slide, BODY)
        _write(body.text_frame, [_AWAITING], size=16, colour=_MUTED, italic=True)


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------


def render(ir: ArtifactIR, facts: dict[str, CanonicalFact] | None = None) -> bytes:
    """Render one IR to PPTX bytes.

    Prose carries ``{{fact:ID}}`` references; *facts* resolves them at render
    time. Without it the references stay visible, which is the right failure —
    a deck that quietly drops a figure reads as finished and is not.
    """
    pptx_pkg = _require_pptx()
    plan = _plan(ir)

    presentation = pptx_pkg.Presentation()
    presentation.slide_width = SLIDE_W
    presentation.slide_height = SLIDE_H

    for slide_plan in plan.slides:
        if slide_plan.kind == "cover":
            _draw_cover(presentation, plan)
        elif slide_plan.kind == "divider":
            _draw_divider(presentation, slide_plan.heading)
        elif slide_plan.kind == "closing":
            _draw_closing(presentation, plan)
        else:
            _draw_content(presentation, plan, slide_plan, facts)

    properties = presentation.core_properties
    properties.title = ir.title
    properties.subject = ir.subtitle or ""
    properties.author = ir.metadata.get("author") or "Worldloom"
    properties.comments = ir.metadata.get("note", "Synthetic corpus generated by Worldloom.")
    properties.keywords = "synthetic,worldloom,seed=" + ir.metadata.get("worldloom_seed", "")

    from io import BytesIO

    buffer = BytesIO()
    presentation.save(buffer)
    # Dates come from the world, never the clock — see `ooxml.normalise`. Both
    # python-pptx's per-entry zip timestamps and its template's own static
    # `docProps/core.xml` dates are wall-clock or template artefacts, exactly
    # the defect `ooxml.py` exists to correct for DOCX and XLSX alike.
    return ooxml.normalise(buffer.getvalue(), created=ir.metadata.get("worldloom_created"))


def render_all(world: World) -> list[Rendered]:
    """Render every executive-summary-shaped artifact in *world*."""
    facts = {fact.id: fact for fact in world.facts}
    out: list[Rendered] = []
    for ir in world.artifact_irs:
        intent = world.artifact_intents.by_id(ir.intent_id)
        if intent.artifact_type not in HANDLES:
            continue
        out.append(
            Rendered(
                artifact_id=ir.id,
                path=f"artifacts/{ir.id.lower()}-{slug_for(intent.artifact_type)}.pptx",
                media_type=MEDIA_TYPE,
                payload=render(ir, facts),
            )
        )
    return out
