"""The command reference, generated from the CLI itself.

Every other document in this repository is written by hand, and the harness
documents (``AGENTS.md`` and the skills it routes to) are what an agent
reads *before* it knows anything. That makes them the worst place for drift: a
flag that quietly disappeared is not a stale sentence, it is an agent running a
command that fails, or worse, silently building a thinner corpus than the tool
can produce because the option it needed was never mentioned.

So the reference is not written. It is generated from the Typer app and checked
in, and a test regenerates it and diffs — the same discipline the corpus itself
gets, where CI rebuilds a world from its ledger and requires it byte-for-byte.
Prose stays hand-written, because a generator cannot explain *why* a flag exists;
but nothing hand-written is allowed to name a command or flag that does not.
"""

from __future__ import annotations

from typing import Any

import typer

from .cli import app

# Deliberately no `import click`. Typer 0.27 vendors click as `typer._click`, so
# a top-level click import fails outright in this installation, and importing the
# private module would tie this file to one Typer version. Every attribute used
# below — `.commands`, `.params`, `.param_type_name`, `.opts` — is stable click
# API reachable through the object Typer hands back, so duck typing costs nothing
# and survives the vendoring changing again.

#: Where the generated reference lives, relative to the repository root. The
#: skill loads this on demand rather than inlining it — the whole surface is far
#: more than an agent needs to read before its first build.
REFERENCE_PATH = ".claude/skills/worldloom/references/commands.md"

_PREAMBLE = """<!-- Generated by `worldloom docs`. Do not edit by hand. -->
<!-- `pytest -q tests/test_harness_docs.py` fails if this drifts from the CLI. -->

# Command reference

Every command and option this installation has. Generated from the CLI, so it
cannot describe a flag that does not exist.

Load this when you need the exact spelling of an option. The procedure, what to
run and in what order, is in `SKILL.md`; this is the lookup table.
"""


def _walk(command: Any, path: tuple[str, ...] = ()) -> list[tuple[tuple[str, ...], Any]]:
    """Every leaf command, depth-first, with its full invocation path.

    Groups are yielded too, because ``narrate`` and ``evals`` carry their own help
    text and an agent that runs the bare group needs to see it.
    """
    found = [(path, command)]
    for name in sorted(getattr(command, "commands", {})):
        found += _walk(command.commands[name], path + (name,))
    return found


def _options(command: Any) -> list[Any]:
    return [
        param
        for param in command.params
        if param.param_type_name == "option" and param.name != "help"
    ]


def commands() -> dict[str, set[str]]:
    """Every command path to the set of option strings it accepts.

    The machine-readable half, used by the drift test to check that no document
    in the repository tells an agent to run something the CLI would reject.
    ``--help`` is dropped: it is accepted everywhere and would only ever mask a
    genuine mistake in a documented example.
    """
    root = typer.main.get_command(app)
    surface: dict[str, set[str]] = {}
    for path, command in _walk(root):
        if not path:
            continue
        flags = {opt for param in _options(command) for opt in param.opts}
        # A group's own options are accepted before the subcommand name, so a
        # documented `worldloom narrate accept --from x` has to check against the
        # union rather than the leaf alone.
        parent = surface.get(" ".join(path[:-1]), set())
        surface[" ".join(path)] = flags | parent
    return surface


def _render_command(path: tuple[str, ...], command: Any) -> list[str]:
    invocation = " ".join(("worldloom", *path))
    lines = [f"### `{invocation}`", ""]

    summary = (command.help or "").strip().splitlines()
    if summary:
        lines += [summary[0].strip(), ""]

    arguments = [p for p in command.params if p.param_type_name == "argument"]
    if arguments:
        rendered = " ".join(f"<{p.name.upper()}>" for p in arguments)
        lines += [f"```\n{invocation} {rendered}\n```", ""]

    options = _options(command)
    if options:
        lines += ["| Option | Purpose |", "| --- | --- |"]
        for param in sorted(options, key=lambda p: p.opts[0]):
            spelling = ", ".join(f"`{opt}`" for opt in param.opts)
            # Pipes would break the table, and a help string is free text that
            # nobody thinks of as markdown when they write it.
            purpose = (param.help or "").replace("|", "\\|").strip()
            lines += [f"| {spelling} | {purpose} |"]
        lines += [""]
    return lines


def reference() -> str:
    """The full generated reference, as markdown."""
    root = typer.main.get_command(app)
    lines = [_PREAMBLE]
    for path, command in _walk(root):
        if not path:
            continue
        lines += _render_command(path, command)
    # A single trailing newline, so the file compares equal to what an editor
    # would leave behind and the diff in CI is about content rather than
    # whitespace.
    return "\n".join(lines).rstrip("\n") + "\n"


__all__ = ["REFERENCE_PATH", "commands", "reference"]
